/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */

export type GetUsers200Item = {
    public_name?: string;
    public_id?: string;
    profile_picture?: string;
};
