/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */
import { HttpResponse, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import type { Article, GetEditorialCategories200Item, GetEditorialFollowers200, GetEditorialMegamenu200 } from "../model";

import {
    getGetEditorialArticlesByCategoryResponseMock,
    getGetEditorialCategoriesResponseMock,
    getGetEditorialFollowersResponseMock,
    getGetEditorialMegamenuResponseMock,
} from "./editorial.faker";

export {
    getGetEditorialFollowersResponseMock,
    getGetEditorialMegamenuResponseMock,
    getGetEditorialCategoriesResponseMock,
    getGetEditorialArticlesByCategoryResponseMock,
} from "./editorial.faker";

export const getGetEditorialFollowersMockHandler = (
    overrideResponse?:
        GetEditorialFollowers200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetEditorialFollowers200> | GetEditorialFollowers200),
    options?: RequestHandlerOptions
) => {
    return http.get(
        "*/api/editorial/followers",
        async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
            return HttpResponse.json(
                overrideResponse !== undefined
                    ? typeof overrideResponse === "function"
                        ? await overrideResponse(info)
                        : overrideResponse
                    : getGetEditorialFollowersResponseMock(),
                { status: 200 }
            );
        },
        options
    );
};

export const getGetEditorialMegamenuMockHandler = (
    overrideResponse?:
        GetEditorialMegamenu200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetEditorialMegamenu200> | GetEditorialMegamenu200),
    options?: RequestHandlerOptions
) => {
    return http.get(
        "*/api/editorial/megamenu",
        async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
            return HttpResponse.json(
                overrideResponse !== undefined
                    ? typeof overrideResponse === "function"
                        ? await overrideResponse(info)
                        : overrideResponse
                    : getGetEditorialMegamenuResponseMock(),
                { status: 200 }
            );
        },
        options
    );
};

export const getGetEditorialCategoriesMockHandler = (
    overrideResponse?:
        | GetEditorialCategories200Item[]
        | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetEditorialCategories200Item[]> | GetEditorialCategories200Item[]),
    options?: RequestHandlerOptions
) => {
    return http.get(
        "*/api/editorial/categories",
        async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
            return HttpResponse.json(
                overrideResponse !== undefined
                    ? typeof overrideResponse === "function"
                        ? await overrideResponse(info)
                        : overrideResponse
                    : getGetEditorialCategoriesResponseMock(),
                { status: 200 }
            );
        },
        options
    );
};

export const getGetEditorialArticlesByCategoryMockHandler = (
    overrideResponse?: Article[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Article[]> | Article[]),
    options?: RequestHandlerOptions
) => {
    return http.get(
        "*/api/editorial/articles/:category",
        async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
            return HttpResponse.json(
                overrideResponse !== undefined
                    ? typeof overrideResponse === "function"
                        ? await overrideResponse(info)
                        : overrideResponse
                    : getGetEditorialArticlesByCategoryResponseMock(),
                { status: 200 }
            );
        },
        options
    );
};
export const getEditorialMock = () => [
    getGetEditorialFollowersMockHandler(),
    getGetEditorialMegamenuMockHandler(),
    getGetEditorialCategoriesMockHandler(),
    getGetEditorialArticlesByCategoryMockHandler(),
];
