/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * API macarte
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker';

import type {
  ApiEditorialCategories200Item,
  ApiEditorialFollowers200,
  ApiEditorialMegamenu200,
  Article
} from '../model';


export const getApiEditorialFollowersResponseMock = (overrideResponse: Partial<Extract<ApiEditorialFollowers200, object>> = {}): ApiEditorialFollowers200 => ({facebook: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), twitter: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), linkedin: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), instagram: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ...overrideResponse})

export const getApiEditorialMegamenuResponseMock = (overrideResponse: Partial<Extract<ApiEditorialMegamenu200, object>> = {}): ApiEditorialMegamenu200 => ({html: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ...overrideResponse})

export const getApiEditorialCategoriesResponseMock = (): ApiEditorialCategories200Item[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({key: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), value: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])})))

export const getApiEditorialArticlesCategoryResponseMock = (): Article[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), category: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), position: faker.helpers.arrayElement([faker.number.float({fractionDigits: 2}), undefined]), title: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), content: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), tags: faker.helpers.arrayElement([Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), undefined]), updated_at: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), updated_by: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), img_url: faker.helpers.arrayElement([faker.internet.url(), undefined]), link_text: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), link_url: faker.helpers.arrayElement([faker.internet.url(), undefined])})))

