/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * API macarte
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import {
  env
} from '../../env';

import type {
  Theme
} from '../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type apiThemesResponse200 = {
  data: Theme[]
  status: 200
}

export type apiThemesResponseSuccess = (apiThemesResponse200) & {
  headers: Headers;
};
;

export type apiThemesResponse = (apiThemesResponseSuccess)

export const getApiThemesUrl = () => {




  return `${env.API_EDITEUR_URL}/api/themes`
}

export const apiThemes = async ( options?: RequestInit): Promise<apiThemesResponse> => {

  const res = await fetch(getApiThemesUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiThemesResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiThemesResponse
}





export const getApiThemesQueryKey = () => {
    return [
    `${env.API_EDITEUR_URL}/api/themes`
    ] as const;
    }


export const getApiThemesQueryOptions = <TData = Awaited<ReturnType<typeof apiThemes>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiThemes>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApiThemesQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof apiThemes>>> = ({ signal }) => apiThemes({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof apiThemes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApiThemesQueryResult = NonNullable<Awaited<ReturnType<typeof apiThemes>>>
export type ApiThemesQueryError = unknown


export function useApiThemes<TData = Awaited<ReturnType<typeof apiThemes>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiThemes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiThemes>>,
          TError,
          Awaited<ReturnType<typeof apiThemes>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiThemes<TData = Awaited<ReturnType<typeof apiThemes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiThemes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiThemes>>,
          TError,
          Awaited<ReturnType<typeof apiThemes>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiThemes<TData = Awaited<ReturnType<typeof apiThemes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiThemes>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApiThemes<TData = Awaited<ReturnType<typeof apiThemes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiThemes>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApiThemesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const prefetchApiThemesQuery = async <TData = Awaited<ReturnType<typeof apiThemes>>, TError = unknown>(
 queryClient: QueryClient,  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiThemes>>, TError, TData>>, fetch?: RequestInit}

  ): Promise<QueryClient> => {

  const queryOptions = getApiThemesQueryOptions(options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





