/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */

export type PostMediasBody = {
    /** image à ajouter à la bibliothèque, le fichier doit faire moins de 2 Mo */
    file: Blob;
    /** Dossier où ajouter l'image */
    folder?: string;
    /** Nom du fichier */
    name?: string;
    /**
     * Id de l'organization
     * @nullable
     */
    organization_id?: string | null;
};
