/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */

export type PutMediaAttributeBody = {
    /** valeur à affecter à l'attribut [folder => peut être null] */
    value?: string;
};
