/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */

export type GetEditorialCategories200Item = {
    /** clé de la catégorie */
    key?: string;
    /** Nom de la catégorie */
    value?: string;
};
