/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * API macarte
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  ApiUsers200,
  UserPublic,
  UserView
} from '../model';


export const getApiMeResponseMock = (): UserView => ({...{locked: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), id: faker.helpers.arrayElement([faker.number.int(), undefined]), medias_limit_size: faker.helpers.arrayElement([faker.number.int(), undefined]), medias_size: faker.helpers.arrayElement([faker.number.int(), undefined]), roles: faker.helpers.arrayElement([Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), undefined])},...{...{email: faker.helpers.arrayElement([faker.internet.email(), undefined]), username: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])},...{public_id: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), public_name: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), twitter_account: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), facebook_account: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), linkedin_account: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), presentation: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), profile_picture: faker.helpers.arrayElement([faker.internet.url(), undefined]), cover_picture: faker.helpers.arrayElement([faker.internet.url(), undefined])},},})

export const getPatchApiMeResponseMock = (): UserView => ({...{locked: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), id: faker.helpers.arrayElement([faker.number.int(), undefined]), medias_limit_size: faker.helpers.arrayElement([faker.number.int(), undefined]), medias_size: faker.helpers.arrayElement([faker.number.int(), undefined]), roles: faker.helpers.arrayElement([Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => (faker.string.alpha({length: {min: 10, max: 20}}))), undefined])},...{...{email: faker.helpers.arrayElement([faker.internet.email(), undefined]), username: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined])},...{public_id: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), public_name: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), twitter_account: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), facebook_account: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), linkedin_account: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), presentation: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), profile_picture: faker.helpers.arrayElement([faker.internet.url(), undefined]), cover_picture: faker.helpers.arrayElement([faker.internet.url(), undefined])},},})

export const getApiUsersPublicPublicIdResponseMock = (overrideResponse: Partial<Extract<UserPublic, object>> = {}): UserPublic => ({public_id: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), public_name: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), twitter_account: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), facebook_account: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), linkedin_account: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), presentation: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), profile_picture: faker.helpers.arrayElement([faker.internet.url(), undefined]), cover_picture: faker.helpers.arrayElement([faker.internet.url(), undefined]), ...overrideResponse})

export const getApiUsersResponseMock = (overrideResponse: Partial<Extract<ApiUsers200, object>> = {}): ApiUsers200 => ({public_name: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), public_id: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), profile_picture: faker.helpers.arrayElement([faker.internet.url(), undefined]), ...overrideResponse})


export const getApiMeMockHandler = (overrideResponse?: UserView | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<UserView> | UserView), options?: RequestHandlerOptions) => {
  return http.get('*/api/me', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getApiMeResponseMock(),
      { status: 200
      })
  }, options)
}

export const getDeleteApiMeMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/me', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 206
      })
  }, options)
}

export const getPatchApiMeMockHandler = (overrideResponse?: UserView | ((info: Parameters<Parameters<typeof http.patch>[1]>[0]) => Promise<UserView> | UserView), options?: RequestHandlerOptions) => {
  return http.patch('*/api/me', async (info: Parameters<Parameters<typeof http.patch>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getPatchApiMeResponseMock(),
      { status: 200
      })
  }, options)
}

export const getApiUsersPublicPublicIdMockHandler = (overrideResponse?: UserPublic | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<UserPublic> | UserPublic), options?: RequestHandlerOptions) => {
  return http.get('*/api/users/public/:publicId', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getApiUsersPublicPublicIdResponseMock(),
      { status: 200
      })
  }, options)
}

export const getApiUsersMockHandler = (overrideResponse?: ApiUsers200 | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<ApiUsers200> | ApiUsers200), options?: RequestHandlerOptions) => {
  return http.get('*/api/users/', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getApiUsersResponseMock(),
      { status: 200
      })
  }, options)
}
export const getUserMock = () => [
  getApiMeMockHandler(),
  getDeleteApiMeMockHandler(),
  getPatchApiMeMockHandler(),
  getApiUsersPublicPublicIdMockHandler(),
  getApiUsersMockHandler()
]
