/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * API macarte
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import {
  env
} from '../../env';

import type {
  ApiUsers200,
  ApiUsersParams,
  BadRequestResponse,
  ForbiddenResponse,
  InvalidResponse,
  NotConnectedResponse,
  NotFoundResponse,
  UserMeEdit,
  UserPublic,
  UserView
} from '../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type apiMeResponse200 = {
  data: UserView
  status: 200
}

export type apiMeResponse401 = {
  data: NotConnectedResponse
  status: 401
}

export type apiMeResponseSuccess = (apiMeResponse200) & {
  headers: Headers;
};
export type apiMeResponseError = (apiMeResponse401) & {
  headers: Headers;
};

export type apiMeResponse = (apiMeResponseSuccess | apiMeResponseError)

export const getApiMeUrl = () => {




  return `${env.API_EDITEUR_URL}/api/me`
}

export const apiMe = async ( options?: RequestInit): Promise<apiMeResponse> => {

  const res = await fetch(getApiMeUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiMeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiMeResponse
}





export const getApiMeQueryKey = () => {
    return [
    `${env.API_EDITEUR_URL}/api/me`
    ] as const;
    }


export const getApiMeQueryOptions = <TData = Awaited<ReturnType<typeof apiMe>>, TError = NotConnectedResponse>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMe>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApiMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof apiMe>>> = ({ signal }) => apiMe({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof apiMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApiMeQueryResult = NonNullable<Awaited<ReturnType<typeof apiMe>>>
export type ApiMeQueryError = NotConnectedResponse


export function useApiMe<TData = Awaited<ReturnType<typeof apiMe>>, TError = NotConnectedResponse>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiMe>>,
          TError,
          Awaited<ReturnType<typeof apiMe>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiMe<TData = Awaited<ReturnType<typeof apiMe>>, TError = NotConnectedResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiMe>>,
          TError,
          Awaited<ReturnType<typeof apiMe>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiMe<TData = Awaited<ReturnType<typeof apiMe>>, TError = NotConnectedResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMe>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApiMe<TData = Awaited<ReturnType<typeof apiMe>>, TError = NotConnectedResponse>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMe>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApiMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const prefetchApiMeQuery = async <TData = Awaited<ReturnType<typeof apiMe>>, TError = NotConnectedResponse>(
 queryClient: QueryClient,  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMe>>, TError, TData>>, fetch?: RequestInit}

  ): Promise<QueryClient> => {

  const queryOptions = getApiMeQueryOptions(options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





export type deleteApiMeResponse206 = {
  data: void
  status: 206
}

export type deleteApiMeResponse401 = {
  data: NotConnectedResponse
  status: 401
}

export type deleteApiMeResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type deleteApiMeResponse451 = {
  data: InvalidResponse
  status: 451
}

export type deleteApiMeResponseSuccess = (deleteApiMeResponse206) & {
  headers: Headers;
};
export type deleteApiMeResponseError = (deleteApiMeResponse401 | deleteApiMeResponse403 | deleteApiMeResponse451) & {
  headers: Headers;
};

export type deleteApiMeResponse = (deleteApiMeResponseSuccess | deleteApiMeResponseError)

export const getDeleteApiMeUrl = () => {




  return `${env.API_EDITEUR_URL}/api/me`
}

/**
 * Supprime en douceur (https://phpreaction.com/support/suppression-en-douceur-soft-delete/) le compte de l'utilisateur connecté
 */
export const deleteApiMe = async ( options?: RequestInit): Promise<deleteApiMeResponse> => {

  const res = await fetch(getDeleteApiMeUrl(),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteApiMeResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteApiMeResponse
}





export const getDeleteApiMeMutationOptions = <TError = NotConnectedResponse | ForbiddenResponse | InvalidResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiMe>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiMe>>, TError,void, TContext> => {

const mutationKey = ['deleteApiMe'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiMe>>, void> = () => {


          return  deleteApiMe(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiMeMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiMe>>>

    export type DeleteApiMeMutationError = NotConnectedResponse | ForbiddenResponse | InvalidResponse

    export const useDeleteApiMe = <TError = NotConnectedResponse | ForbiddenResponse | InvalidResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiMe>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiMe>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getDeleteApiMeMutationOptions(options), queryClient);
    }
    export type patchApiMeResponse200 = {
  data: UserView
  status: 200
}

export type patchApiMeResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type patchApiMeResponse401 = {
  data: NotConnectedResponse
  status: 401
}

export type patchApiMeResponseSuccess = (patchApiMeResponse200) & {
  headers: Headers;
};
export type patchApiMeResponseError = (patchApiMeResponse400 | patchApiMeResponse401) & {
  headers: Headers;
};

export type patchApiMeResponse = (patchApiMeResponseSuccess | patchApiMeResponseError)

export const getPatchApiMeUrl = () => {




  return `${env.API_EDITEUR_URL}/api/me`
}

/**
 * parameter **current_password** is required to patch username, email and new_password<br>
 *                 username, email et public_name sont uniques, la réponse 400 '... already used' peut être renvoyée
 */
export const patchApiMe = async (userMeEdit: UserMeEdit, options?: RequestInit): Promise<patchApiMeResponse> => {

  const res = await fetch(getPatchApiMeUrl(),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(userMeEdit)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: patchApiMeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as patchApiMeResponse
}





export const getPatchApiMeMutationOptions = <TError = BadRequestResponse | NotConnectedResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiMe>>, TError,{data: UserMeEdit}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiMe>>, TError,{data: UserMeEdit}, TContext> => {

const mutationKey = ['patchApiMe'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiMe>>, {data: UserMeEdit}> = (props) => {
          const {data} = props ?? {};

          return  patchApiMe(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchApiMeMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiMe>>>
    export type PatchApiMeMutationBody = UserMeEdit
    export type PatchApiMeMutationError = BadRequestResponse | NotConnectedResponse

    export const usePatchApiMe = <TError = BadRequestResponse | NotConnectedResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiMe>>, TError,{data: UserMeEdit}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiMe>>,
        TError,
        {data: UserMeEdit},
        TContext
      > => {
      return useMutation(getPatchApiMeMutationOptions(options), queryClient);
    }
    export type apiUsersPublicPublicIdResponse200 = {
  data: UserPublic
  status: 200
}

export type apiUsersPublicPublicIdResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type apiUsersPublicPublicIdResponseSuccess = (apiUsersPublicPublicIdResponse200) & {
  headers: Headers;
};
export type apiUsersPublicPublicIdResponseError = (apiUsersPublicPublicIdResponse404) & {
  headers: Headers;
};

export type apiUsersPublicPublicIdResponse = (apiUsersPublicPublicIdResponseSuccess | apiUsersPublicPublicIdResponseError)

export const getApiUsersPublicPublicIdUrl = (publicId: string,) => {




  return `${env.API_EDITEUR_URL}/api/users/public/${publicId}`
}

export const apiUsersPublicPublicId = async (publicId: string, options?: RequestInit): Promise<apiUsersPublicPublicIdResponse> => {

  const res = await fetch(getApiUsersPublicPublicIdUrl(publicId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiUsersPublicPublicIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiUsersPublicPublicIdResponse
}





export const getApiUsersPublicPublicIdQueryKey = (publicId: string,) => {
    return [
    `${env.API_EDITEUR_URL}/api/users/public/${publicId}`
    ] as const;
    }


export const getApiUsersPublicPublicIdQueryOptions = <TData = Awaited<ReturnType<typeof apiUsersPublicPublicId>>, TError = NotFoundResponse>(publicId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiUsersPublicPublicId>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApiUsersPublicPublicIdQueryKey(publicId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof apiUsersPublicPublicId>>> = ({ signal }) => apiUsersPublicPublicId(publicId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: publicId !== null && publicId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof apiUsersPublicPublicId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApiUsersPublicPublicIdQueryResult = NonNullable<Awaited<ReturnType<typeof apiUsersPublicPublicId>>>
export type ApiUsersPublicPublicIdQueryError = NotFoundResponse


export function useApiUsersPublicPublicId<TData = Awaited<ReturnType<typeof apiUsersPublicPublicId>>, TError = NotFoundResponse>(
 publicId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiUsersPublicPublicId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiUsersPublicPublicId>>,
          TError,
          Awaited<ReturnType<typeof apiUsersPublicPublicId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiUsersPublicPublicId<TData = Awaited<ReturnType<typeof apiUsersPublicPublicId>>, TError = NotFoundResponse>(
 publicId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiUsersPublicPublicId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiUsersPublicPublicId>>,
          TError,
          Awaited<ReturnType<typeof apiUsersPublicPublicId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiUsersPublicPublicId<TData = Awaited<ReturnType<typeof apiUsersPublicPublicId>>, TError = NotFoundResponse>(
 publicId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiUsersPublicPublicId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApiUsersPublicPublicId<TData = Awaited<ReturnType<typeof apiUsersPublicPublicId>>, TError = NotFoundResponse>(
 publicId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiUsersPublicPublicId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApiUsersPublicPublicIdQueryOptions(publicId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const prefetchApiUsersPublicPublicIdQuery = async <TData = Awaited<ReturnType<typeof apiUsersPublicPublicId>>, TError = NotFoundResponse>(
 queryClient: QueryClient, publicId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiUsersPublicPublicId>>, TError, TData>>, fetch?: RequestInit}

  ): Promise<QueryClient> => {

  const queryOptions = getApiUsersPublicPublicIdQueryOptions(publicId,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





export type apiUsersResponse200 = {
  data: ApiUsers200
  status: 200
}

export type apiUsersResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type apiUsersResponseSuccess = (apiUsersResponse200) & {
  headers: Headers;
};
export type apiUsersResponseError = (apiUsersResponse400) & {
  headers: Headers;
};

export type apiUsersResponse = (apiUsersResponseSuccess | apiUsersResponseError)

export const getApiUsersUrl = (params: ApiUsersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${env.API_EDITEUR_URL}/api/users/?${stringifiedParams}` : `${env.API_EDITEUR_URL}/api/users/`
}

/**
 * Recherche d'utilisateurs par autocompletion
 */
export const apiUsers = async (params: ApiUsersParams, options?: RequestInit): Promise<apiUsersResponse> => {

  const res = await fetch(getApiUsersUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiUsersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiUsersResponse
}





export const getApiUsersQueryKey = (params?: ApiUsersParams,) => {
    return [
    `${env.API_EDITEUR_URL}/api/users/`, ...(params ? [params] : [])
    ] as const;
    }


export const getApiUsersQueryOptions = <TData = Awaited<ReturnType<typeof apiUsers>>, TError = BadRequestResponse>(params: ApiUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiUsers>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApiUsersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof apiUsers>>> = ({ signal }) => apiUsers(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof apiUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApiUsersQueryResult = NonNullable<Awaited<ReturnType<typeof apiUsers>>>
export type ApiUsersQueryError = BadRequestResponse


export function useApiUsers<TData = Awaited<ReturnType<typeof apiUsers>>, TError = BadRequestResponse>(
 params: ApiUsersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiUsers>>,
          TError,
          Awaited<ReturnType<typeof apiUsers>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiUsers<TData = Awaited<ReturnType<typeof apiUsers>>, TError = BadRequestResponse>(
 params: ApiUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiUsers>>,
          TError,
          Awaited<ReturnType<typeof apiUsers>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiUsers<TData = Awaited<ReturnType<typeof apiUsers>>, TError = BadRequestResponse>(
 params: ApiUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiUsers>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApiUsers<TData = Awaited<ReturnType<typeof apiUsers>>, TError = BadRequestResponse>(
 params: ApiUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiUsers>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApiUsersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const prefetchApiUsersQuery = async <TData = Awaited<ReturnType<typeof apiUsers>>, TError = BadRequestResponse>(
 queryClient: QueryClient, params: ApiUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiUsers>>, TError, TData>>, fetch?: RequestInit}

  ): Promise<QueryClient> => {

  const queryOptions = getApiUsersQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





