/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  Notification
} from '../model';


export const getGetNotificationsResponseMock = (): Notification[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), description: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), scope: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), showFrom: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), showUntil: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), repeatibility: faker.helpers.arrayElement([faker.number.int(), undefined])})))


export const getGetNotificationsMockHandler = (overrideResponse?: Notification[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Notification[]> | Notification[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/notifications', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getGetNotificationsResponseMock(),
      { status: 200
      })
  }, options)
}
export const getNotificationsMock = () => [
  getGetNotificationsMockHandler()
]
