/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * API macarte
 * OpenAPI spec version: 1.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import {
  env
} from '../../env';

import type {
  Notification
} from '../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type apiNotificationsResponse200 = {
  data: Notification[]
  status: 200
}

export type apiNotificationsResponseSuccess = (apiNotificationsResponse200) & {
  headers: Headers;
};
;

export type apiNotificationsResponse = (apiNotificationsResponseSuccess)

export const getApiNotificationsUrl = () => {




  return `${env.API_EDITEUR_URL}/api/notifications`
}

export const apiNotifications = async ( options?: RequestInit): Promise<apiNotificationsResponse> => {

  const res = await fetch(getApiNotificationsUrl(),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiNotificationsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiNotificationsResponse
}





export const getApiNotificationsQueryKey = () => {
    return [
    `${env.API_EDITEUR_URL}/api/notifications`
    ] as const;
    }


export const getApiNotificationsQueryOptions = <TData = Awaited<ReturnType<typeof apiNotifications>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiNotifications>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApiNotificationsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof apiNotifications>>> = ({ signal }) => apiNotifications({ signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof apiNotifications>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApiNotificationsQueryResult = NonNullable<Awaited<ReturnType<typeof apiNotifications>>>
export type ApiNotificationsQueryError = unknown


export function useApiNotifications<TData = Awaited<ReturnType<typeof apiNotifications>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiNotifications>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiNotifications>>,
          TError,
          Awaited<ReturnType<typeof apiNotifications>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiNotifications<TData = Awaited<ReturnType<typeof apiNotifications>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiNotifications>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiNotifications>>,
          TError,
          Awaited<ReturnType<typeof apiNotifications>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiNotifications<TData = Awaited<ReturnType<typeof apiNotifications>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiNotifications>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApiNotifications<TData = Awaited<ReturnType<typeof apiNotifications>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiNotifications>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApiNotificationsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const prefetchApiNotificationsQuery = async <TData = Awaited<ReturnType<typeof apiNotifications>>, TError = unknown>(
 queryClient: QueryClient,  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiNotifications>>, TError, TData>>, fetch?: RequestInit}

  ): Promise<QueryClient> => {

  const queryOptions = getApiNotificationsQueryOptions(options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





