/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import {
  env
} from '../../env';

import type {
  Login,
  NotConnectedResponse,
  PostLogin401,
  PostLogin429,
  PostLoginBody,
  PostTokenRefresh401,
  PostTokenRefreshBody
} from '../model';





export type postLoginResponse200 = {
  data: Login
  status: 200
}

export type postLoginResponse401 = {
  data: PostLogin401
  status: 401
}

export type postLoginResponse429 = {
  data: PostLogin429
  status: 429
}

export type postLoginResponseSuccess = (postLoginResponse200) & {
  headers: Headers;
};
export type postLoginResponseError = (postLoginResponse401 | postLoginResponse429) & {
  headers: Headers;
};

export type postLoginResponse = (postLoginResponseSuccess | postLoginResponseError)

export const getPostLoginUrl = () => {




  return `${env.API_EDITEUR_URL}/api/login`
}

export const postLogin = async (postLoginBody: PostLoginBody, options?: RequestInit): Promise<postLoginResponse> => {
    const formUrlEncoded = new URLSearchParams();
formUrlEncoded.append(`username`, postLoginBody.username);
formUrlEncoded.append(`password`, postLoginBody.password);

  const res = await fetch(getPostLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded', ...options?.headers },
    body: formUrlEncoded
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postLoginResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postLoginResponse
}





export const getPostLoginMutationOptions = <TError = PostLogin401 | PostLogin429,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLogin>>, TError,{data: PostLoginBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postLogin>>, TError,{data: PostLoginBody}, TContext> => {

const mutationKey = ['postLogin'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postLogin>>, {data: PostLoginBody}> = (props) => {
          const {data} = props ?? {};

          return  postLogin(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postLogin>>>
    export type PostLoginMutationBody = PostLoginBody
    export type PostLoginMutationError = PostLogin401 | PostLogin429

    export const usePostLogin = <TError = PostLogin401 | PostLogin429,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLogin>>, TError,{data: PostLoginBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postLogin>>,
        TError,
        {data: PostLoginBody},
        TContext
      > => {
      return useMutation(getPostLoginMutationOptions(options), queryClient);
    }
    export type postTokenRefreshResponse200 = {
  data: Login
  status: 200
}

export type postTokenRefreshResponse401 = {
  data: PostTokenRefresh401
  status: 401
}

export type postTokenRefreshResponseSuccess = (postTokenRefreshResponse200) & {
  headers: Headers;
};
export type postTokenRefreshResponseError = (postTokenRefreshResponse401) & {
  headers: Headers;
};

export type postTokenRefreshResponse = (postTokenRefreshResponseSuccess | postTokenRefreshResponseError)

export const getPostTokenRefreshUrl = () => {




  return `${env.API_EDITEUR_URL}/api/token/refresh`
}

export const postTokenRefresh = async (postTokenRefreshBody: PostTokenRefreshBody, options?: RequestInit): Promise<postTokenRefreshResponse> => {
    const formUrlEncoded = new URLSearchParams();
formUrlEncoded.append(`refresh_token`, postTokenRefreshBody.refresh_token);

  const res = await fetch(getPostTokenRefreshUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded', ...options?.headers },
    body: formUrlEncoded
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postTokenRefreshResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postTokenRefreshResponse
}





export const getPostTokenRefreshMutationOptions = <TError = PostTokenRefresh401,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postTokenRefresh>>, TError,{data: PostTokenRefreshBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postTokenRefresh>>, TError,{data: PostTokenRefreshBody}, TContext> => {

const mutationKey = ['postTokenRefresh'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postTokenRefresh>>, {data: PostTokenRefreshBody}> = (props) => {
          const {data} = props ?? {};

          return  postTokenRefresh(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostTokenRefreshMutationResult = NonNullable<Awaited<ReturnType<typeof postTokenRefresh>>>
    export type PostTokenRefreshMutationBody = PostTokenRefreshBody
    export type PostTokenRefreshMutationError = PostTokenRefresh401

    export const usePostTokenRefresh = <TError = PostTokenRefresh401,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postTokenRefresh>>, TError,{data: PostTokenRefreshBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postTokenRefresh>>,
        TError,
        {data: PostTokenRefreshBody},
        TContext
      > => {
      return useMutation(getPostTokenRefreshMutationOptions(options), queryClient);
    }
    export type postLogoutResponse200 = {
  data: void
  status: 200
}

export type postLogoutResponse401 = {
  data: NotConnectedResponse
  status: 401
}

export type postLogoutResponseSuccess = (postLogoutResponse200) & {
  headers: Headers;
};
export type postLogoutResponseError = (postLogoutResponse401) & {
  headers: Headers;
};

export type postLogoutResponse = (postLogoutResponseSuccess | postLogoutResponseError)

export const getPostLogoutUrl = () => {




  return `${env.API_EDITEUR_URL}/api/logout`
}

export const postLogout = async ( options?: RequestInit): Promise<postLogoutResponse> => {

  const res = await fetch(getPostLogoutUrl(),
  {
    ...options,
    method: 'POST'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postLogoutResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as postLogoutResponse
}





export const getPostLogoutMutationOptions = <TError = NotConnectedResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLogout>>, TError,void, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postLogout>>, TError,void, TContext> => {

const mutationKey = ['postLogout'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postLogout>>, void> = () => {


          return  postLogout(fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof postLogout>>>

    export type PostLogoutMutationError = NotConnectedResponse

    export const usePostLogout = <TError = NotConnectedResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLogout>>, TError,void, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postLogout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostLogoutMutationOptions(options), queryClient);
    }
