/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";

import { HttpResponse, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import type { Login } from "../model";

export const getRefreshTokenResponseMock = (overrideResponse: Partial<Extract<Login, object>> = {}): Login => ({
    token: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    refresh_token: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    ...overrideResponse,
});

export const getPostLoginResponseMock = (overrideResponse: Partial<Extract<Login, object>> = {}): Login => ({
    token: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    refresh_token: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    ...overrideResponse,
});

export const getRefreshTokenMockHandler = (
    overrideResponse?: Login | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Login> | Login),
    options?: RequestHandlerOptions
) => {
    return http.post(
        "*/api/token/refresh",
        async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
            return HttpResponse.json(
                overrideResponse !== undefined
                    ? typeof overrideResponse === "function"
                        ? await overrideResponse(info)
                        : overrideResponse
                    : getRefreshTokenResponseMock(),
                { status: 200 }
            );
        },
        options
    );
};

export const getPostLoginMockHandler = (
    overrideResponse?: Login | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Login> | Login),
    options?: RequestHandlerOptions
) => {
    return http.post(
        "*/api/login",
        async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
            return HttpResponse.json(
                overrideResponse !== undefined
                    ? typeof overrideResponse === "function"
                        ? await overrideResponse(info)
                        : overrideResponse
                    : getPostLoginResponseMock(),
                { status: 200 }
            );
        },
        options
    );
};

export const getPostLogoutMockHandler = (
    overrideResponse?: void | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<void> | void),
    options?: RequestHandlerOptions
) => {
    return http.post(
        "*/api/logout",
        async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
            if (typeof overrideResponse === "function") {
                await overrideResponse(info);
            }

            return new HttpResponse(null, { status: 200 });
        },
        options
    );
};
export const getLoginMock = () => [getRefreshTokenMockHandler(), getPostLoginMockHandler(), getPostLogoutMockHandler()];
