/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * API macarte
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import {
  env
} from '../../env';

import type {
  ApiMapsParams,
  ApiMapsUsersParams,
  BadRequestResponse,
  CreateApiMapsBody,
  CreateApiMapsEditIdFileBody,
  DeletedResponse,
  ForbiddenResponse,
  InvalidResponse,
  MapResearch,
  MapView,
  NotConnectedResponse,
  NotFoundResponse,
  PartialContentResponse,
  PatchApiMapsEditIdBody
} from '../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type apiMapsResponse200 = {
  data: MapResearch
  status: 200
}

export type apiMapsResponse206 = {
  data: PartialContentResponse
  status: 206
}

export type apiMapsResponse401 = {
  data: NotConnectedResponse
  status: 401
}

export type apiMapsResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type apiMapsResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type apiMapsResponseSuccess = (apiMapsResponse200 | apiMapsResponse206) & {
  headers: Headers;
};
export type apiMapsResponseError = (apiMapsResponse401 | apiMapsResponse403 | apiMapsResponse404) & {
  headers: Headers;
};

export type apiMapsResponse = (apiMapsResponseSuccess | apiMapsResponseError)

export const getApiMapsUrl = (params?: ApiMapsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${env.API_EDITEUR_URL}/api/maps?${stringifiedParams}` : `${env.API_EDITEUR_URL}/api/maps`
}

export const apiMaps = async (params?: ApiMapsParams, options?: RequestInit): Promise<apiMapsResponse> => {

  const res = await fetch(getApiMapsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiMapsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiMapsResponse
}





export const getApiMapsQueryKey = (params?: ApiMapsParams,) => {
    return [
    `${env.API_EDITEUR_URL}/api/maps`, ...(params ? [params] : [])
    ] as const;
    }


export const getApiMapsQueryOptions = <TData = Awaited<ReturnType<typeof apiMaps>>, TError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse>(params?: ApiMapsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMaps>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApiMapsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof apiMaps>>> = ({ signal }) => apiMaps(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof apiMaps>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApiMapsQueryResult = NonNullable<Awaited<ReturnType<typeof apiMaps>>>
export type ApiMapsQueryError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse


export function useApiMaps<TData = Awaited<ReturnType<typeof apiMaps>>, TError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse>(
 params: undefined |  ApiMapsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMaps>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiMaps>>,
          TError,
          Awaited<ReturnType<typeof apiMaps>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiMaps<TData = Awaited<ReturnType<typeof apiMaps>>, TError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse>(
 params?: ApiMapsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMaps>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiMaps>>,
          TError,
          Awaited<ReturnType<typeof apiMaps>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiMaps<TData = Awaited<ReturnType<typeof apiMaps>>, TError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse>(
 params?: ApiMapsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMaps>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApiMaps<TData = Awaited<ReturnType<typeof apiMaps>>, TError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse>(
 params?: ApiMapsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMaps>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApiMapsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const prefetchApiMapsQuery = async <TData = Awaited<ReturnType<typeof apiMaps>>, TError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse>(
 queryClient: QueryClient, params?: ApiMapsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMaps>>, TError, TData>>, fetch?: RequestInit}

  ): Promise<QueryClient> => {

  const queryOptions = getApiMapsQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





export type createApiMapsResponse201 = {
  data: MapView
  status: 201
}

export type createApiMapsResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type createApiMapsResponse401 = {
  data: NotConnectedResponse
  status: 401
}

export type createApiMapsResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type createApiMapsResponseSuccess = (createApiMapsResponse201) & {
  headers: Headers;
};
export type createApiMapsResponseError = (createApiMapsResponse400 | createApiMapsResponse401 | createApiMapsResponse404) & {
  headers: Headers;
};

export type createApiMapsResponse = (createApiMapsResponseSuccess | createApiMapsResponseError)

export const getCreateApiMapsUrl = () => {




  return `${env.API_EDITEUR_URL}/api/maps`
}

export const createApiMaps = async (createApiMapsBody: CreateApiMapsBody, options?: RequestInit): Promise<createApiMapsResponse> => {
    const formData = new FormData();
formData.append(`carte`, JSON.stringify(createApiMapsBody.carte));
formData.append(`file`, createApiMapsBody.file);

  const res = await fetch(getCreateApiMapsUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createApiMapsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createApiMapsResponse
}





export const getCreateApiMapsMutationOptions = <TError = BadRequestResponse | NotConnectedResponse | NotFoundResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createApiMaps>>, TError,{data: CreateApiMapsBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createApiMaps>>, TError,{data: CreateApiMapsBody}, TContext> => {

const mutationKey = ['createApiMaps'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createApiMaps>>, {data: CreateApiMapsBody}> = (props) => {
          const {data} = props ?? {};

          return  createApiMaps(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateApiMapsMutationResult = NonNullable<Awaited<ReturnType<typeof createApiMaps>>>
    export type CreateApiMapsMutationBody = CreateApiMapsBody
    export type CreateApiMapsMutationError = BadRequestResponse | NotConnectedResponse | NotFoundResponse

    export const useCreateApiMaps = <TError = BadRequestResponse | NotConnectedResponse | NotFoundResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createApiMaps>>, TError,{data: CreateApiMapsBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createApiMaps>>,
        TError,
        {data: CreateApiMapsBody},
        TContext
      > => {
      return useMutation(getCreateApiMapsMutationOptions(options), queryClient);
    }
    export type apiMapsUsersResponse200 = {
  data: string[]
  status: 200
}

export type apiMapsUsersResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type apiMapsUsersResponseSuccess = (apiMapsUsersResponse200) & {
  headers: Headers;
};
export type apiMapsUsersResponseError = (apiMapsUsersResponse404) & {
  headers: Headers;
};

export type apiMapsUsersResponse = (apiMapsUsersResponseSuccess | apiMapsUsersResponseError)

export const getApiMapsUsersUrl = (params?: ApiMapsUsersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${env.API_EDITEUR_URL}/api/maps/users?${stringifiedParams}` : `${env.API_EDITEUR_URL}/api/maps/users`
}

/**
 * Autocompletion des utilisateurs ayant des cartes publiques correspondant aux critères de recherche
 */
export const apiMapsUsers = async (params?: ApiMapsUsersParams, options?: RequestInit): Promise<apiMapsUsersResponse> => {

  const res = await fetch(getApiMapsUsersUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiMapsUsersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiMapsUsersResponse
}





export const getApiMapsUsersQueryKey = (params?: ApiMapsUsersParams,) => {
    return [
    `${env.API_EDITEUR_URL}/api/maps/users`, ...(params ? [params] : [])
    ] as const;
    }


export const getApiMapsUsersQueryOptions = <TData = Awaited<ReturnType<typeof apiMapsUsers>>, TError = NotFoundResponse>(params?: ApiMapsUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMapsUsers>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApiMapsUsersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof apiMapsUsers>>> = ({ signal }) => apiMapsUsers(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof apiMapsUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApiMapsUsersQueryResult = NonNullable<Awaited<ReturnType<typeof apiMapsUsers>>>
export type ApiMapsUsersQueryError = NotFoundResponse


export function useApiMapsUsers<TData = Awaited<ReturnType<typeof apiMapsUsers>>, TError = NotFoundResponse>(
 params: undefined |  ApiMapsUsersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMapsUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiMapsUsers>>,
          TError,
          Awaited<ReturnType<typeof apiMapsUsers>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiMapsUsers<TData = Awaited<ReturnType<typeof apiMapsUsers>>, TError = NotFoundResponse>(
 params?: ApiMapsUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMapsUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiMapsUsers>>,
          TError,
          Awaited<ReturnType<typeof apiMapsUsers>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiMapsUsers<TData = Awaited<ReturnType<typeof apiMapsUsers>>, TError = NotFoundResponse>(
 params?: ApiMapsUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMapsUsers>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApiMapsUsers<TData = Awaited<ReturnType<typeof apiMapsUsers>>, TError = NotFoundResponse>(
 params?: ApiMapsUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMapsUsers>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApiMapsUsersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const prefetchApiMapsUsersQuery = async <TData = Awaited<ReturnType<typeof apiMapsUsers>>, TError = NotFoundResponse>(
 queryClient: QueryClient, params?: ApiMapsUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMapsUsers>>, TError, TData>>, fetch?: RequestInit}

  ): Promise<QueryClient> => {

  const queryOptions = getApiMapsUsersQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





export type apiMapsViewIdResponse200 = {
  data: MapView
  status: 200
}

export type apiMapsViewIdResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type apiMapsViewIdResponse451 = {
  data: InvalidResponse
  status: 451
}

export type apiMapsViewIdResponseSuccess = (apiMapsViewIdResponse200) & {
  headers: Headers;
};
export type apiMapsViewIdResponseError = (apiMapsViewIdResponse404 | apiMapsViewIdResponse451) & {
  headers: Headers;
};

export type apiMapsViewIdResponse = (apiMapsViewIdResponseSuccess | apiMapsViewIdResponseError)

export const getApiMapsViewIdUrl = (viewId: number | string,) => {




  return `${env.API_EDITEUR_URL}/api/maps/${viewId}`
}

/**
 * Récupérer les metadata de la carte par son identifiant de visualisation
 */
export const apiMapsViewId = async (viewId: number | string, options?: RequestInit): Promise<apiMapsViewIdResponse> => {

  const res = await fetch(getApiMapsViewIdUrl(viewId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiMapsViewIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiMapsViewIdResponse
}





export const getApiMapsViewIdQueryKey = (viewId: number | string,) => {
    return [
    `${env.API_EDITEUR_URL}/api/maps/${viewId}`
    ] as const;
    }


export const getApiMapsViewIdQueryOptions = <TData = Awaited<ReturnType<typeof apiMapsViewId>>, TError = NotFoundResponse | InvalidResponse>(viewId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMapsViewId>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApiMapsViewIdQueryKey(viewId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof apiMapsViewId>>> = ({ signal }) => apiMapsViewId(viewId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: viewId !== null && viewId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof apiMapsViewId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApiMapsViewIdQueryResult = NonNullable<Awaited<ReturnType<typeof apiMapsViewId>>>
export type ApiMapsViewIdQueryError = NotFoundResponse | InvalidResponse


export function useApiMapsViewId<TData = Awaited<ReturnType<typeof apiMapsViewId>>, TError = NotFoundResponse | InvalidResponse>(
 viewId: number | string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMapsViewId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiMapsViewId>>,
          TError,
          Awaited<ReturnType<typeof apiMapsViewId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiMapsViewId<TData = Awaited<ReturnType<typeof apiMapsViewId>>, TError = NotFoundResponse | InvalidResponse>(
 viewId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMapsViewId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiMapsViewId>>,
          TError,
          Awaited<ReturnType<typeof apiMapsViewId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiMapsViewId<TData = Awaited<ReturnType<typeof apiMapsViewId>>, TError = NotFoundResponse | InvalidResponse>(
 viewId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMapsViewId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApiMapsViewId<TData = Awaited<ReturnType<typeof apiMapsViewId>>, TError = NotFoundResponse | InvalidResponse>(
 viewId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMapsViewId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApiMapsViewIdQueryOptions(viewId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const prefetchApiMapsViewIdQuery = async <TData = Awaited<ReturnType<typeof apiMapsViewId>>, TError = NotFoundResponse | InvalidResponse>(
 queryClient: QueryClient, viewId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMapsViewId>>, TError, TData>>, fetch?: RequestInit}

  ): Promise<QueryClient> => {

  const queryOptions = getApiMapsViewIdQueryOptions(viewId,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





export type apiMapsEditIdEditResponse200 = {
  data: MapView
  status: 200
}

export type apiMapsEditIdEditResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type apiMapsEditIdEditResponse451 = {
  data: InvalidResponse
  status: 451
}

export type apiMapsEditIdEditResponseSuccess = (apiMapsEditIdEditResponse200) & {
  headers: Headers;
};
export type apiMapsEditIdEditResponseError = (apiMapsEditIdEditResponse404 | apiMapsEditIdEditResponse451) & {
  headers: Headers;
};

export type apiMapsEditIdEditResponse = (apiMapsEditIdEditResponseSuccess | apiMapsEditIdEditResponseError)

export const getApiMapsEditIdEditUrl = (editId: number | string,) => {




  return `${env.API_EDITEUR_URL}/api/maps/${editId}/edit`
}

/**
 * Récupérer les metadata de la carte par son identifiant d'édition'
 */
export const apiMapsEditIdEdit = async (editId: number | string, options?: RequestInit): Promise<apiMapsEditIdEditResponse> => {

  const res = await fetch(getApiMapsEditIdEditUrl(editId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiMapsEditIdEditResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiMapsEditIdEditResponse
}





export const getApiMapsEditIdEditQueryKey = (editId: number | string,) => {
    return [
    `${env.API_EDITEUR_URL}/api/maps/${editId}/edit`
    ] as const;
    }


export const getApiMapsEditIdEditQueryOptions = <TData = Awaited<ReturnType<typeof apiMapsEditIdEdit>>, TError = NotFoundResponse | InvalidResponse>(editId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMapsEditIdEdit>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApiMapsEditIdEditQueryKey(editId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof apiMapsEditIdEdit>>> = ({ signal }) => apiMapsEditIdEdit(editId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: editId !== null && editId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof apiMapsEditIdEdit>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApiMapsEditIdEditQueryResult = NonNullable<Awaited<ReturnType<typeof apiMapsEditIdEdit>>>
export type ApiMapsEditIdEditQueryError = NotFoundResponse | InvalidResponse


export function useApiMapsEditIdEdit<TData = Awaited<ReturnType<typeof apiMapsEditIdEdit>>, TError = NotFoundResponse | InvalidResponse>(
 editId: number | string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMapsEditIdEdit>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiMapsEditIdEdit>>,
          TError,
          Awaited<ReturnType<typeof apiMapsEditIdEdit>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiMapsEditIdEdit<TData = Awaited<ReturnType<typeof apiMapsEditIdEdit>>, TError = NotFoundResponse | InvalidResponse>(
 editId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMapsEditIdEdit>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiMapsEditIdEdit>>,
          TError,
          Awaited<ReturnType<typeof apiMapsEditIdEdit>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiMapsEditIdEdit<TData = Awaited<ReturnType<typeof apiMapsEditIdEdit>>, TError = NotFoundResponse | InvalidResponse>(
 editId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMapsEditIdEdit>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApiMapsEditIdEdit<TData = Awaited<ReturnType<typeof apiMapsEditIdEdit>>, TError = NotFoundResponse | InvalidResponse>(
 editId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMapsEditIdEdit>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApiMapsEditIdEditQueryOptions(editId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const prefetchApiMapsEditIdEditQuery = async <TData = Awaited<ReturnType<typeof apiMapsEditIdEdit>>, TError = NotFoundResponse | InvalidResponse>(
 queryClient: QueryClient, editId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMapsEditIdEdit>>, TError, TData>>, fetch?: RequestInit}

  ): Promise<QueryClient> => {

  const queryOptions = getApiMapsEditIdEditQueryOptions(editId,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





export type apiMapsViewIdFileResponse200 = {
  data: unknown
  status: 200
}

export type apiMapsViewIdFileResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type apiMapsViewIdFileResponse451 = {
  data: InvalidResponse
  status: 451
}

export type apiMapsViewIdFileResponseSuccess = (apiMapsViewIdFileResponse200) & {
  headers: Headers;
};
export type apiMapsViewIdFileResponseError = (apiMapsViewIdFileResponse404 | apiMapsViewIdFileResponse451) & {
  headers: Headers;
};

export type apiMapsViewIdFileResponse = (apiMapsViewIdFileResponseSuccess | apiMapsViewIdFileResponseError)

export const getApiMapsViewIdFileUrl = (viewId: number | string,) => {




  return `${env.API_EDITEUR_URL}/api/maps/${viewId}/file`
}

/**
 * Récupérer les data de la carte par son identifiant de visualisation
 */
export const apiMapsViewIdFile = async (viewId: number | string, options?: RequestInit): Promise<apiMapsViewIdFileResponse> => {

  const res = await fetch(getApiMapsViewIdFileUrl(viewId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiMapsViewIdFileResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiMapsViewIdFileResponse
}





export const getApiMapsViewIdFileQueryKey = (viewId: number | string,) => {
    return [
    `${env.API_EDITEUR_URL}/api/maps/${viewId}/file`
    ] as const;
    }


export const getApiMapsViewIdFileQueryOptions = <TData = Awaited<ReturnType<typeof apiMapsViewIdFile>>, TError = NotFoundResponse | InvalidResponse>(viewId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMapsViewIdFile>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApiMapsViewIdFileQueryKey(viewId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof apiMapsViewIdFile>>> = ({ signal }) => apiMapsViewIdFile(viewId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: viewId !== null && viewId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof apiMapsViewIdFile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApiMapsViewIdFileQueryResult = NonNullable<Awaited<ReturnType<typeof apiMapsViewIdFile>>>
export type ApiMapsViewIdFileQueryError = NotFoundResponse | InvalidResponse


export function useApiMapsViewIdFile<TData = Awaited<ReturnType<typeof apiMapsViewIdFile>>, TError = NotFoundResponse | InvalidResponse>(
 viewId: number | string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMapsViewIdFile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiMapsViewIdFile>>,
          TError,
          Awaited<ReturnType<typeof apiMapsViewIdFile>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiMapsViewIdFile<TData = Awaited<ReturnType<typeof apiMapsViewIdFile>>, TError = NotFoundResponse | InvalidResponse>(
 viewId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMapsViewIdFile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiMapsViewIdFile>>,
          TError,
          Awaited<ReturnType<typeof apiMapsViewIdFile>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiMapsViewIdFile<TData = Awaited<ReturnType<typeof apiMapsViewIdFile>>, TError = NotFoundResponse | InvalidResponse>(
 viewId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMapsViewIdFile>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApiMapsViewIdFile<TData = Awaited<ReturnType<typeof apiMapsViewIdFile>>, TError = NotFoundResponse | InvalidResponse>(
 viewId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMapsViewIdFile>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApiMapsViewIdFileQueryOptions(viewId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const prefetchApiMapsViewIdFileQuery = async <TData = Awaited<ReturnType<typeof apiMapsViewIdFile>>, TError = NotFoundResponse | InvalidResponse>(
 queryClient: QueryClient, viewId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMapsViewIdFile>>, TError, TData>>, fetch?: RequestInit}

  ): Promise<QueryClient> => {

  const queryOptions = getApiMapsViewIdFileQueryOptions(viewId,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





export type apiMapsEditIdEditFileResponse200 = {
  data: unknown
  status: 200
}

export type apiMapsEditIdEditFileResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type apiMapsEditIdEditFileResponse451 = {
  data: InvalidResponse
  status: 451
}

export type apiMapsEditIdEditFileResponseSuccess = (apiMapsEditIdEditFileResponse200) & {
  headers: Headers;
};
export type apiMapsEditIdEditFileResponseError = (apiMapsEditIdEditFileResponse404 | apiMapsEditIdEditFileResponse451) & {
  headers: Headers;
};

export type apiMapsEditIdEditFileResponse = (apiMapsEditIdEditFileResponseSuccess | apiMapsEditIdEditFileResponseError)

export const getApiMapsEditIdEditFileUrl = (editId: number | string,) => {




  return `${env.API_EDITEUR_URL}/api/maps/${editId}/edit/file`
}

/**
 * Récupérer les data de la carte par son identifiant d'édition
 */
export const apiMapsEditIdEditFile = async (editId: number | string, options?: RequestInit): Promise<apiMapsEditIdEditFileResponse> => {

  const res = await fetch(getApiMapsEditIdEditFileUrl(editId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiMapsEditIdEditFileResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiMapsEditIdEditFileResponse
}





export const getApiMapsEditIdEditFileQueryKey = (editId: number | string,) => {
    return [
    `${env.API_EDITEUR_URL}/api/maps/${editId}/edit/file`
    ] as const;
    }


export const getApiMapsEditIdEditFileQueryOptions = <TData = Awaited<ReturnType<typeof apiMapsEditIdEditFile>>, TError = NotFoundResponse | InvalidResponse>(editId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMapsEditIdEditFile>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApiMapsEditIdEditFileQueryKey(editId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof apiMapsEditIdEditFile>>> = ({ signal }) => apiMapsEditIdEditFile(editId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: editId !== null && editId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof apiMapsEditIdEditFile>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApiMapsEditIdEditFileQueryResult = NonNullable<Awaited<ReturnType<typeof apiMapsEditIdEditFile>>>
export type ApiMapsEditIdEditFileQueryError = NotFoundResponse | InvalidResponse


export function useApiMapsEditIdEditFile<TData = Awaited<ReturnType<typeof apiMapsEditIdEditFile>>, TError = NotFoundResponse | InvalidResponse>(
 editId: number | string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMapsEditIdEditFile>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiMapsEditIdEditFile>>,
          TError,
          Awaited<ReturnType<typeof apiMapsEditIdEditFile>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiMapsEditIdEditFile<TData = Awaited<ReturnType<typeof apiMapsEditIdEditFile>>, TError = NotFoundResponse | InvalidResponse>(
 editId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMapsEditIdEditFile>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiMapsEditIdEditFile>>,
          TError,
          Awaited<ReturnType<typeof apiMapsEditIdEditFile>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiMapsEditIdEditFile<TData = Awaited<ReturnType<typeof apiMapsEditIdEditFile>>, TError = NotFoundResponse | InvalidResponse>(
 editId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMapsEditIdEditFile>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApiMapsEditIdEditFile<TData = Awaited<ReturnType<typeof apiMapsEditIdEditFile>>, TError = NotFoundResponse | InvalidResponse>(
 editId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMapsEditIdEditFile>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApiMapsEditIdEditFileQueryOptions(editId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const prefetchApiMapsEditIdEditFileQuery = async <TData = Awaited<ReturnType<typeof apiMapsEditIdEditFile>>, TError = NotFoundResponse | InvalidResponse>(
 queryClient: QueryClient, editId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMapsEditIdEditFile>>, TError, TData>>, fetch?: RequestInit}

  ): Promise<QueryClient> => {

  const queryOptions = getApiMapsEditIdEditFileQueryOptions(editId,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





export type deleteApiMapsEditIdResponse204 = {
  data: DeletedResponse
  status: 204
}

export type deleteApiMapsEditIdResponse401 = {
  data: NotConnectedResponse
  status: 401
}

export type deleteApiMapsEditIdResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type deleteApiMapsEditIdResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type deleteApiMapsEditIdResponseSuccess = (deleteApiMapsEditIdResponse204) & {
  headers: Headers;
};
export type deleteApiMapsEditIdResponseError = (deleteApiMapsEditIdResponse401 | deleteApiMapsEditIdResponse403 | deleteApiMapsEditIdResponse404) & {
  headers: Headers;
};

export type deleteApiMapsEditIdResponse = (deleteApiMapsEditIdResponseSuccess | deleteApiMapsEditIdResponseError)

export const getDeleteApiMapsEditIdUrl = (editId: number | string,) => {




  return `${env.API_EDITEUR_URL}/api/maps/${editId}`
}

export const deleteApiMapsEditId = async (editId: number | string, options?: RequestInit): Promise<deleteApiMapsEditIdResponse> => {

  const res = await fetch(getDeleteApiMapsEditIdUrl(editId),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteApiMapsEditIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteApiMapsEditIdResponse
}





export const getDeleteApiMapsEditIdMutationOptions = <TError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiMapsEditId>>, TError,{editId: number | string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiMapsEditId>>, TError,{editId: number | string}, TContext> => {

const mutationKey = ['deleteApiMapsEditId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiMapsEditId>>, {editId: number | string}> = (props) => {
          const {editId} = props ?? {};

          return  deleteApiMapsEditId(editId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiMapsEditIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiMapsEditId>>>

    export type DeleteApiMapsEditIdMutationError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse

    export const useDeleteApiMapsEditId = <TError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiMapsEditId>>, TError,{editId: number | string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiMapsEditId>>,
        TError,
        {editId: number | string},
        TContext
      > => {
      return useMutation(getDeleteApiMapsEditIdMutationOptions(options), queryClient);
    }
    export type patchApiMapsEditIdResponse200 = {
  data: MapView
  status: 200
}

export type patchApiMapsEditIdResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type patchApiMapsEditIdResponse401 = {
  data: NotConnectedResponse
  status: 401
}

export type patchApiMapsEditIdResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type patchApiMapsEditIdResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type patchApiMapsEditIdResponseSuccess = (patchApiMapsEditIdResponse200) & {
  headers: Headers;
};
export type patchApiMapsEditIdResponseError = (patchApiMapsEditIdResponse400 | patchApiMapsEditIdResponse401 | patchApiMapsEditIdResponse403 | patchApiMapsEditIdResponse404) & {
  headers: Headers;
};

export type patchApiMapsEditIdResponse = (patchApiMapsEditIdResponseSuccess | patchApiMapsEditIdResponseError)

export const getPatchApiMapsEditIdUrl = (editId: number | string,) => {




  return `${env.API_EDITEUR_URL}/api/maps/${editId}`
}

export const patchApiMapsEditId = async (editId: number | string,
    patchApiMapsEditIdBody: PatchApiMapsEditIdBody, options?: RequestInit): Promise<patchApiMapsEditIdResponse> => {

  const res = await fetch(getPatchApiMapsEditIdUrl(editId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(patchApiMapsEditIdBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: patchApiMapsEditIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as patchApiMapsEditIdResponse
}





export const getPatchApiMapsEditIdMutationOptions = <TError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse | NotFoundResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiMapsEditId>>, TError,{editId: number | string;data: PatchApiMapsEditIdBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof patchApiMapsEditId>>, TError,{editId: number | string;data: PatchApiMapsEditIdBody}, TContext> => {

const mutationKey = ['patchApiMapsEditId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchApiMapsEditId>>, {editId: number | string;data: PatchApiMapsEditIdBody}> = (props) => {
          const {editId,data} = props ?? {};

          return  patchApiMapsEditId(editId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchApiMapsEditIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchApiMapsEditId>>>
    export type PatchApiMapsEditIdMutationBody = PatchApiMapsEditIdBody
    export type PatchApiMapsEditIdMutationError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse | NotFoundResponse

    export const usePatchApiMapsEditId = <TError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse | NotFoundResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchApiMapsEditId>>, TError,{editId: number | string;data: PatchApiMapsEditIdBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchApiMapsEditId>>,
        TError,
        {editId: number | string;data: PatchApiMapsEditIdBody},
        TContext
      > => {
      return useMutation(getPatchApiMapsEditIdMutationOptions(options), queryClient);
    }
    export type createApiMapsEditIdFileResponse200 = {
  data: void
  status: 200
}

export type createApiMapsEditIdFileResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type createApiMapsEditIdFileResponseSuccess = (createApiMapsEditIdFileResponse200) & {
  headers: Headers;
};
export type createApiMapsEditIdFileResponseError = (createApiMapsEditIdFileResponse404) & {
  headers: Headers;
};

export type createApiMapsEditIdFileResponse = (createApiMapsEditIdFileResponseSuccess | createApiMapsEditIdFileResponseError)

export const getCreateApiMapsEditIdFileUrl = (editId: number | string,) => {




  return `${env.API_EDITEUR_URL}/api/maps/${editId}/file`
}

export const createApiMapsEditIdFile = async (editId: number | string,
    createApiMapsEditIdFileBody: CreateApiMapsEditIdFileBody, options?: RequestInit): Promise<createApiMapsEditIdFileResponse> => {
    const formData = new FormData();
formData.append(`file`, createApiMapsEditIdFileBody.file);

  const res = await fetch(getCreateApiMapsEditIdFileUrl(editId),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createApiMapsEditIdFileResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as createApiMapsEditIdFileResponse
}





export const getCreateApiMapsEditIdFileMutationOptions = <TError = NotFoundResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createApiMapsEditIdFile>>, TError,{editId: number | string;data: CreateApiMapsEditIdFileBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createApiMapsEditIdFile>>, TError,{editId: number | string;data: CreateApiMapsEditIdFileBody}, TContext> => {

const mutationKey = ['createApiMapsEditIdFile'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createApiMapsEditIdFile>>, {editId: number | string;data: CreateApiMapsEditIdFileBody}> = (props) => {
          const {editId,data} = props ?? {};

          return  createApiMapsEditIdFile(editId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateApiMapsEditIdFileMutationResult = NonNullable<Awaited<ReturnType<typeof createApiMapsEditIdFile>>>
    export type CreateApiMapsEditIdFileMutationBody = CreateApiMapsEditIdFileBody
    export type CreateApiMapsEditIdFileMutationError = NotFoundResponse

    export const useCreateApiMapsEditIdFile = <TError = NotFoundResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createApiMapsEditIdFile>>, TError,{editId: number | string;data: CreateApiMapsEditIdFileBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createApiMapsEditIdFile>>,
        TError,
        {editId: number | string;data: CreateApiMapsEditIdFileBody},
        TContext
      > => {
      return useMutation(getCreateApiMapsEditIdFileMutationOptions(options), queryClient);
    }
