/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import {
  env
} from '../../env';

import type {
  BadRequestResponse,
  DeletedResponse,
  ForbiddenResponse,
  GetMapsParams,
  GetMapsUsersParams,
  InvalidResponse,
  MapResearch,
  MapView,
  NotConnectedResponse,
  NotFoundResponse,
  PartialContentResponse,
  PatchMapByEditIdBody,
  PostMapBody,
  PostMapFileByEditIdBody
} from '../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type getMapsResponse200 = {
  data: MapResearch
  status: 200
}

export type getMapsResponse206 = {
  data: PartialContentResponse
  status: 206
}

export type getMapsResponse401 = {
  data: NotConnectedResponse
  status: 401
}

export type getMapsResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type getMapsResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getMapsResponseSuccess = (getMapsResponse200 | getMapsResponse206) & {
  headers: Headers;
};
export type getMapsResponseError = (getMapsResponse401 | getMapsResponse403 | getMapsResponse404) & {
  headers: Headers;
};

export type getMapsResponse = (getMapsResponseSuccess | getMapsResponseError)

export const getGetMapsUrl = (params?: GetMapsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${env.API_EDITEUR_URL}/api/maps?${stringifiedParams}` : `${env.API_EDITEUR_URL}/api/maps`
}

export const getMaps = async (params?: GetMapsParams, options?: RequestInit): Promise<getMapsResponse> => {

  const res = await fetch(getGetMapsUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMapsResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMapsResponse
}





export const getGetMapsQueryKey = (params?: GetMapsParams,) => {
    return [
    `${env.API_EDITEUR_URL}/api/maps`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetMapsQueryOptions = <TData = Awaited<ReturnType<typeof getMaps>>, TError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse>(params?: GetMapsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMaps>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMapsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMaps>>> = ({ signal }) => getMaps(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMaps>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMapsQueryResult = NonNullable<Awaited<ReturnType<typeof getMaps>>>
export type GetMapsQueryError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse


export function useGetMaps<TData = Awaited<ReturnType<typeof getMaps>>, TError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse>(
 params: undefined |  GetMapsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMaps>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMaps>>,
          TError,
          Awaited<ReturnType<typeof getMaps>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMaps<TData = Awaited<ReturnType<typeof getMaps>>, TError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse>(
 params?: GetMapsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMaps>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMaps>>,
          TError,
          Awaited<ReturnType<typeof getMaps>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMaps<TData = Awaited<ReturnType<typeof getMaps>>, TError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse>(
 params?: GetMapsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMaps>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMaps<TData = Awaited<ReturnType<typeof getMaps>>, TError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse>(
 params?: GetMapsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMaps>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMapsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const prefetchGetMapsQuery = async <TData = Awaited<ReturnType<typeof getMaps>>, TError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse>(
 queryClient: QueryClient, params?: GetMapsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMaps>>, TError, TData>>, fetch?: RequestInit}

  ): Promise<QueryClient> => {

  const queryOptions = getGetMapsQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





export type postMapResponse201 = {
  data: MapView
  status: 201
}

export type postMapResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type postMapResponse401 = {
  data: NotConnectedResponse
  status: 401
}

export type postMapResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type postMapResponseSuccess = (postMapResponse201) & {
  headers: Headers;
};
export type postMapResponseError = (postMapResponse400 | postMapResponse401 | postMapResponse404) & {
  headers: Headers;
};

export type postMapResponse = (postMapResponseSuccess | postMapResponseError)

export const getPostMapUrl = () => {




  return `${env.API_EDITEUR_URL}/api/maps`
}

export const postMap = async (postMapBody: PostMapBody, options?: RequestInit): Promise<postMapResponse> => {
    const formData = new FormData();
formData.append(`carte`, JSON.stringify(postMapBody.carte));
formData.append(`file`, postMapBody.file);

  const res = await fetch(getPostMapUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postMapResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as postMapResponse
}





export const getPostMapMutationOptions = <TError = BadRequestResponse | NotConnectedResponse | NotFoundResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postMap>>, TError,{data: PostMapBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postMap>>, TError,{data: PostMapBody}, TContext> => {

const mutationKey = ['postMap'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postMap>>, {data: PostMapBody}> = (props) => {
          const {data} = props ?? {};

          return  postMap(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostMapMutationResult = NonNullable<Awaited<ReturnType<typeof postMap>>>
    export type PostMapMutationBody = PostMapBody
    export type PostMapMutationError = BadRequestResponse | NotConnectedResponse | NotFoundResponse

    export const usePostMap = <TError = BadRequestResponse | NotConnectedResponse | NotFoundResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postMap>>, TError,{data: PostMapBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postMap>>,
        TError,
        {data: PostMapBody},
        TContext
      > => {
      return useMutation(getPostMapMutationOptions(options), queryClient);
    }
    export type getMapsUsersResponse200 = {
  data: string[]
  status: 200
}

export type getMapsUsersResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getMapsUsersResponseSuccess = (getMapsUsersResponse200) & {
  headers: Headers;
};
export type getMapsUsersResponseError = (getMapsUsersResponse404) & {
  headers: Headers;
};

export type getMapsUsersResponse = (getMapsUsersResponseSuccess | getMapsUsersResponseError)

export const getGetMapsUsersUrl = (params?: GetMapsUsersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${env.API_EDITEUR_URL}/api/maps/users?${stringifiedParams}` : `${env.API_EDITEUR_URL}/api/maps/users`
}

/**
 * Autocompletion des utilisateurs ayant des cartes publiques correspondant aux critères de recherche
 */
export const getMapsUsers = async (params?: GetMapsUsersParams, options?: RequestInit): Promise<getMapsUsersResponse> => {

  const res = await fetch(getGetMapsUsersUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMapsUsersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMapsUsersResponse
}





export const getGetMapsUsersQueryKey = (params?: GetMapsUsersParams,) => {
    return [
    `${env.API_EDITEUR_URL}/api/maps/users`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetMapsUsersQueryOptions = <TData = Awaited<ReturnType<typeof getMapsUsers>>, TError = NotFoundResponse>(params?: GetMapsUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMapsUsers>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMapsUsersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMapsUsers>>> = ({ signal }) => getMapsUsers(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMapsUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMapsUsersQueryResult = NonNullable<Awaited<ReturnType<typeof getMapsUsers>>>
export type GetMapsUsersQueryError = NotFoundResponse


export function useGetMapsUsers<TData = Awaited<ReturnType<typeof getMapsUsers>>, TError = NotFoundResponse>(
 params: undefined |  GetMapsUsersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMapsUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMapsUsers>>,
          TError,
          Awaited<ReturnType<typeof getMapsUsers>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMapsUsers<TData = Awaited<ReturnType<typeof getMapsUsers>>, TError = NotFoundResponse>(
 params?: GetMapsUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMapsUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMapsUsers>>,
          TError,
          Awaited<ReturnType<typeof getMapsUsers>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMapsUsers<TData = Awaited<ReturnType<typeof getMapsUsers>>, TError = NotFoundResponse>(
 params?: GetMapsUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMapsUsers>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMapsUsers<TData = Awaited<ReturnType<typeof getMapsUsers>>, TError = NotFoundResponse>(
 params?: GetMapsUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMapsUsers>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMapsUsersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const prefetchGetMapsUsersQuery = async <TData = Awaited<ReturnType<typeof getMapsUsers>>, TError = NotFoundResponse>(
 queryClient: QueryClient, params?: GetMapsUsersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMapsUsers>>, TError, TData>>, fetch?: RequestInit}

  ): Promise<QueryClient> => {

  const queryOptions = getGetMapsUsersQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





export type getMapByViewIdResponse200 = {
  data: MapView
  status: 200
}

export type getMapByViewIdResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getMapByViewIdResponse451 = {
  data: InvalidResponse
  status: 451
}

export type getMapByViewIdResponseSuccess = (getMapByViewIdResponse200) & {
  headers: Headers;
};
export type getMapByViewIdResponseError = (getMapByViewIdResponse404 | getMapByViewIdResponse451) & {
  headers: Headers;
};

export type getMapByViewIdResponse = (getMapByViewIdResponseSuccess | getMapByViewIdResponseError)

export const getGetMapByViewIdUrl = (viewId: number | string,) => {




  return `${env.API_EDITEUR_URL}/api/maps/${viewId}`
}

/**
 * Récupérer les metadata de la carte par son identifiant de visualisation
 */
export const getMapByViewId = async (viewId: number | string, options?: RequestInit): Promise<getMapByViewIdResponse> => {

  const res = await fetch(getGetMapByViewIdUrl(viewId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMapByViewIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMapByViewIdResponse
}





export const getGetMapByViewIdQueryKey = (viewId: number | string,) => {
    return [
    `${env.API_EDITEUR_URL}/api/maps/${viewId}`
    ] as const;
    }


export const getGetMapByViewIdQueryOptions = <TData = Awaited<ReturnType<typeof getMapByViewId>>, TError = NotFoundResponse | InvalidResponse>(viewId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMapByViewId>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMapByViewIdQueryKey(viewId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMapByViewId>>> = ({ signal }) => getMapByViewId(viewId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: viewId !== null && viewId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMapByViewId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMapByViewIdQueryResult = NonNullable<Awaited<ReturnType<typeof getMapByViewId>>>
export type GetMapByViewIdQueryError = NotFoundResponse | InvalidResponse


export function useGetMapByViewId<TData = Awaited<ReturnType<typeof getMapByViewId>>, TError = NotFoundResponse | InvalidResponse>(
 viewId: number | string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMapByViewId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMapByViewId>>,
          TError,
          Awaited<ReturnType<typeof getMapByViewId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMapByViewId<TData = Awaited<ReturnType<typeof getMapByViewId>>, TError = NotFoundResponse | InvalidResponse>(
 viewId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMapByViewId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMapByViewId>>,
          TError,
          Awaited<ReturnType<typeof getMapByViewId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMapByViewId<TData = Awaited<ReturnType<typeof getMapByViewId>>, TError = NotFoundResponse | InvalidResponse>(
 viewId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMapByViewId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMapByViewId<TData = Awaited<ReturnType<typeof getMapByViewId>>, TError = NotFoundResponse | InvalidResponse>(
 viewId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMapByViewId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMapByViewIdQueryOptions(viewId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const prefetchGetMapByViewIdQuery = async <TData = Awaited<ReturnType<typeof getMapByViewId>>, TError = NotFoundResponse | InvalidResponse>(
 queryClient: QueryClient, viewId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMapByViewId>>, TError, TData>>, fetch?: RequestInit}

  ): Promise<QueryClient> => {

  const queryOptions = getGetMapByViewIdQueryOptions(viewId,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





export type getMapEditByEditIdResponse200 = {
  data: MapView
  status: 200
}

export type getMapEditByEditIdResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getMapEditByEditIdResponse451 = {
  data: InvalidResponse
  status: 451
}

export type getMapEditByEditIdResponseSuccess = (getMapEditByEditIdResponse200) & {
  headers: Headers;
};
export type getMapEditByEditIdResponseError = (getMapEditByEditIdResponse404 | getMapEditByEditIdResponse451) & {
  headers: Headers;
};

export type getMapEditByEditIdResponse = (getMapEditByEditIdResponseSuccess | getMapEditByEditIdResponseError)

export const getGetMapEditByEditIdUrl = (editId: number | string,) => {




  return `${env.API_EDITEUR_URL}/api/maps/${editId}/edit`
}

/**
 * Récupérer les metadata de la carte par son identifiant d'édition
 */
export const getMapEditByEditId = async (editId: number | string, options?: RequestInit): Promise<getMapEditByEditIdResponse> => {

  const res = await fetch(getGetMapEditByEditIdUrl(editId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMapEditByEditIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMapEditByEditIdResponse
}





export const getGetMapEditByEditIdQueryKey = (editId: number | string,) => {
    return [
    `${env.API_EDITEUR_URL}/api/maps/${editId}/edit`
    ] as const;
    }


export const getGetMapEditByEditIdQueryOptions = <TData = Awaited<ReturnType<typeof getMapEditByEditId>>, TError = NotFoundResponse | InvalidResponse>(editId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMapEditByEditId>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMapEditByEditIdQueryKey(editId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMapEditByEditId>>> = ({ signal }) => getMapEditByEditId(editId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: editId !== null && editId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMapEditByEditId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMapEditByEditIdQueryResult = NonNullable<Awaited<ReturnType<typeof getMapEditByEditId>>>
export type GetMapEditByEditIdQueryError = NotFoundResponse | InvalidResponse


export function useGetMapEditByEditId<TData = Awaited<ReturnType<typeof getMapEditByEditId>>, TError = NotFoundResponse | InvalidResponse>(
 editId: number | string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMapEditByEditId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMapEditByEditId>>,
          TError,
          Awaited<ReturnType<typeof getMapEditByEditId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMapEditByEditId<TData = Awaited<ReturnType<typeof getMapEditByEditId>>, TError = NotFoundResponse | InvalidResponse>(
 editId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMapEditByEditId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMapEditByEditId>>,
          TError,
          Awaited<ReturnType<typeof getMapEditByEditId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMapEditByEditId<TData = Awaited<ReturnType<typeof getMapEditByEditId>>, TError = NotFoundResponse | InvalidResponse>(
 editId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMapEditByEditId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMapEditByEditId<TData = Awaited<ReturnType<typeof getMapEditByEditId>>, TError = NotFoundResponse | InvalidResponse>(
 editId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMapEditByEditId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMapEditByEditIdQueryOptions(editId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const prefetchGetMapEditByEditIdQuery = async <TData = Awaited<ReturnType<typeof getMapEditByEditId>>, TError = NotFoundResponse | InvalidResponse>(
 queryClient: QueryClient, editId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMapEditByEditId>>, TError, TData>>, fetch?: RequestInit}

  ): Promise<QueryClient> => {

  const queryOptions = getGetMapEditByEditIdQueryOptions(editId,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





export type getMapFileByViewIdResponse200 = {
  data: unknown
  status: 200
}

export type getMapFileByViewIdResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getMapFileByViewIdResponse451 = {
  data: InvalidResponse
  status: 451
}

export type getMapFileByViewIdResponseSuccess = (getMapFileByViewIdResponse200) & {
  headers: Headers;
};
export type getMapFileByViewIdResponseError = (getMapFileByViewIdResponse404 | getMapFileByViewIdResponse451) & {
  headers: Headers;
};

export type getMapFileByViewIdResponse = (getMapFileByViewIdResponseSuccess | getMapFileByViewIdResponseError)

export const getGetMapFileByViewIdUrl = (viewId: number | string,) => {




  return `${env.API_EDITEUR_URL}/api/maps/${viewId}/file`
}

/**
 * Récupérer les data de la carte par son identifiant de visualisation
 */
export const getMapFileByViewId = async (viewId: number | string, options?: RequestInit): Promise<getMapFileByViewIdResponse> => {

  const res = await fetch(getGetMapFileByViewIdUrl(viewId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMapFileByViewIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMapFileByViewIdResponse
}





export const getGetMapFileByViewIdQueryKey = (viewId: number | string,) => {
    return [
    `${env.API_EDITEUR_URL}/api/maps/${viewId}/file`
    ] as const;
    }


export const getGetMapFileByViewIdQueryOptions = <TData = Awaited<ReturnType<typeof getMapFileByViewId>>, TError = NotFoundResponse | InvalidResponse>(viewId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMapFileByViewId>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMapFileByViewIdQueryKey(viewId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMapFileByViewId>>> = ({ signal }) => getMapFileByViewId(viewId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: viewId !== null && viewId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMapFileByViewId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMapFileByViewIdQueryResult = NonNullable<Awaited<ReturnType<typeof getMapFileByViewId>>>
export type GetMapFileByViewIdQueryError = NotFoundResponse | InvalidResponse


export function useGetMapFileByViewId<TData = Awaited<ReturnType<typeof getMapFileByViewId>>, TError = NotFoundResponse | InvalidResponse>(
 viewId: number | string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMapFileByViewId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMapFileByViewId>>,
          TError,
          Awaited<ReturnType<typeof getMapFileByViewId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMapFileByViewId<TData = Awaited<ReturnType<typeof getMapFileByViewId>>, TError = NotFoundResponse | InvalidResponse>(
 viewId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMapFileByViewId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMapFileByViewId>>,
          TError,
          Awaited<ReturnType<typeof getMapFileByViewId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMapFileByViewId<TData = Awaited<ReturnType<typeof getMapFileByViewId>>, TError = NotFoundResponse | InvalidResponse>(
 viewId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMapFileByViewId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMapFileByViewId<TData = Awaited<ReturnType<typeof getMapFileByViewId>>, TError = NotFoundResponse | InvalidResponse>(
 viewId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMapFileByViewId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMapFileByViewIdQueryOptions(viewId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const prefetchGetMapFileByViewIdQuery = async <TData = Awaited<ReturnType<typeof getMapFileByViewId>>, TError = NotFoundResponse | InvalidResponse>(
 queryClient: QueryClient, viewId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMapFileByViewId>>, TError, TData>>, fetch?: RequestInit}

  ): Promise<QueryClient> => {

  const queryOptions = getGetMapFileByViewIdQueryOptions(viewId,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





export type getMapEditFileByEditIdResponse200 = {
  data: unknown
  status: 200
}

export type getMapEditFileByEditIdResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type getMapEditFileByEditIdResponse451 = {
  data: InvalidResponse
  status: 451
}

export type getMapEditFileByEditIdResponseSuccess = (getMapEditFileByEditIdResponse200) & {
  headers: Headers;
};
export type getMapEditFileByEditIdResponseError = (getMapEditFileByEditIdResponse404 | getMapEditFileByEditIdResponse451) & {
  headers: Headers;
};

export type getMapEditFileByEditIdResponse = (getMapEditFileByEditIdResponseSuccess | getMapEditFileByEditIdResponseError)

export const getGetMapEditFileByEditIdUrl = (editId: number | string,) => {




  return `${env.API_EDITEUR_URL}/api/maps/${editId}/edit/file`
}

/**
 * Récupérer les data de la carte par son identifiant d'édition
 */
export const getMapEditFileByEditId = async (editId: number | string, options?: RequestInit): Promise<getMapEditFileByEditIdResponse> => {

  const res = await fetch(getGetMapEditFileByEditIdUrl(editId),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getMapEditFileByEditIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getMapEditFileByEditIdResponse
}





export const getGetMapEditFileByEditIdQueryKey = (editId: number | string,) => {
    return [
    `${env.API_EDITEUR_URL}/api/maps/${editId}/edit/file`
    ] as const;
    }


export const getGetMapEditFileByEditIdQueryOptions = <TData = Awaited<ReturnType<typeof getMapEditFileByEditId>>, TError = NotFoundResponse | InvalidResponse>(editId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMapEditFileByEditId>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMapEditFileByEditIdQueryKey(editId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMapEditFileByEditId>>> = ({ signal }) => getMapEditFileByEditId(editId, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: editId !== null && editId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMapEditFileByEditId>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMapEditFileByEditIdQueryResult = NonNullable<Awaited<ReturnType<typeof getMapEditFileByEditId>>>
export type GetMapEditFileByEditIdQueryError = NotFoundResponse | InvalidResponse


export function useGetMapEditFileByEditId<TData = Awaited<ReturnType<typeof getMapEditFileByEditId>>, TError = NotFoundResponse | InvalidResponse>(
 editId: number | string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMapEditFileByEditId>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMapEditFileByEditId>>,
          TError,
          Awaited<ReturnType<typeof getMapEditFileByEditId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMapEditFileByEditId<TData = Awaited<ReturnType<typeof getMapEditFileByEditId>>, TError = NotFoundResponse | InvalidResponse>(
 editId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMapEditFileByEditId>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMapEditFileByEditId>>,
          TError,
          Awaited<ReturnType<typeof getMapEditFileByEditId>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMapEditFileByEditId<TData = Awaited<ReturnType<typeof getMapEditFileByEditId>>, TError = NotFoundResponse | InvalidResponse>(
 editId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMapEditFileByEditId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMapEditFileByEditId<TData = Awaited<ReturnType<typeof getMapEditFileByEditId>>, TError = NotFoundResponse | InvalidResponse>(
 editId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMapEditFileByEditId>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMapEditFileByEditIdQueryOptions(editId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const prefetchGetMapEditFileByEditIdQuery = async <TData = Awaited<ReturnType<typeof getMapEditFileByEditId>>, TError = NotFoundResponse | InvalidResponse>(
 queryClient: QueryClient, editId: number | string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMapEditFileByEditId>>, TError, TData>>, fetch?: RequestInit}

  ): Promise<QueryClient> => {

  const queryOptions = getGetMapEditFileByEditIdQueryOptions(editId,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





export type deleteMapByEditIdResponse204 = {
  data: DeletedResponse
  status: 204
}

export type deleteMapByEditIdResponse401 = {
  data: NotConnectedResponse
  status: 401
}

export type deleteMapByEditIdResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type deleteMapByEditIdResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type deleteMapByEditIdResponseSuccess = (deleteMapByEditIdResponse204) & {
  headers: Headers;
};
export type deleteMapByEditIdResponseError = (deleteMapByEditIdResponse401 | deleteMapByEditIdResponse403 | deleteMapByEditIdResponse404) & {
  headers: Headers;
};

export type deleteMapByEditIdResponse = (deleteMapByEditIdResponseSuccess | deleteMapByEditIdResponseError)

export const getDeleteMapByEditIdUrl = (editId: number | string,) => {




  return `${env.API_EDITEUR_URL}/api/maps/${editId}`
}

export const deleteMapByEditId = async (editId: number | string, options?: RequestInit): Promise<deleteMapByEditIdResponse> => {

  const res = await fetch(getDeleteMapByEditIdUrl(editId),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteMapByEditIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteMapByEditIdResponse
}





export const getDeleteMapByEditIdMutationOptions = <TError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMapByEditId>>, TError,{editId: number | string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteMapByEditId>>, TError,{editId: number | string}, TContext> => {

const mutationKey = ['deleteMapByEditId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteMapByEditId>>, {editId: number | string}> = (props) => {
          const {editId} = props ?? {};

          return  deleteMapByEditId(editId,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteMapByEditIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteMapByEditId>>>

    export type DeleteMapByEditIdMutationError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse

    export const useDeleteMapByEditId = <TError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteMapByEditId>>, TError,{editId: number | string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteMapByEditId>>,
        TError,
        {editId: number | string},
        TContext
      > => {
      return useMutation(getDeleteMapByEditIdMutationOptions(options), queryClient);
    }
    export type patchMapByEditIdResponse200 = {
  data: MapView
  status: 200
}

export type patchMapByEditIdResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type patchMapByEditIdResponse401 = {
  data: NotConnectedResponse
  status: 401
}

export type patchMapByEditIdResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type patchMapByEditIdResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type patchMapByEditIdResponseSuccess = (patchMapByEditIdResponse200) & {
  headers: Headers;
};
export type patchMapByEditIdResponseError = (patchMapByEditIdResponse400 | patchMapByEditIdResponse401 | patchMapByEditIdResponse403 | patchMapByEditIdResponse404) & {
  headers: Headers;
};

export type patchMapByEditIdResponse = (patchMapByEditIdResponseSuccess | patchMapByEditIdResponseError)

export const getPatchMapByEditIdUrl = (editId: number | string,) => {




  return `${env.API_EDITEUR_URL}/api/maps/${editId}`
}

export const patchMapByEditId = async (editId: number | string,
    patchMapByEditIdBody: PatchMapByEditIdBody, options?: RequestInit): Promise<patchMapByEditIdResponse> => {

  const res = await fetch(getPatchMapByEditIdUrl(editId),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(patchMapByEditIdBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: patchMapByEditIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as patchMapByEditIdResponse
}





export const getPatchMapByEditIdMutationOptions = <TError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse | NotFoundResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchMapByEditId>>, TError,{editId: number | string;data: PatchMapByEditIdBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof patchMapByEditId>>, TError,{editId: number | string;data: PatchMapByEditIdBody}, TContext> => {

const mutationKey = ['patchMapByEditId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof patchMapByEditId>>, {editId: number | string;data: PatchMapByEditIdBody}> = (props) => {
          const {editId,data} = props ?? {};

          return  patchMapByEditId(editId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PatchMapByEditIdMutationResult = NonNullable<Awaited<ReturnType<typeof patchMapByEditId>>>
    export type PatchMapByEditIdMutationBody = PatchMapByEditIdBody
    export type PatchMapByEditIdMutationError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse | NotFoundResponse

    export const usePatchMapByEditId = <TError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse | NotFoundResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof patchMapByEditId>>, TError,{editId: number | string;data: PatchMapByEditIdBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof patchMapByEditId>>,
        TError,
        {editId: number | string;data: PatchMapByEditIdBody},
        TContext
      > => {
      return useMutation(getPatchMapByEditIdMutationOptions(options), queryClient);
    }
    export type postMapFileByEditIdResponse200 = {
  data: void
  status: 200
}

export type postMapFileByEditIdResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type postMapFileByEditIdResponseSuccess = (postMapFileByEditIdResponse200) & {
  headers: Headers;
};
export type postMapFileByEditIdResponseError = (postMapFileByEditIdResponse404) & {
  headers: Headers;
};

export type postMapFileByEditIdResponse = (postMapFileByEditIdResponseSuccess | postMapFileByEditIdResponseError)

export const getPostMapFileByEditIdUrl = (editId: number | string,) => {




  return `${env.API_EDITEUR_URL}/api/maps/${editId}/file`
}

export const postMapFileByEditId = async (editId: number | string,
    postMapFileByEditIdBody: PostMapFileByEditIdBody, options?: RequestInit): Promise<postMapFileByEditIdResponse> => {
    const formData = new FormData();
formData.append(`file`, postMapFileByEditIdBody.file);

  const res = await fetch(getPostMapFileByEditIdUrl(editId),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: postMapFileByEditIdResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as postMapFileByEditIdResponse
}





export const getPostMapFileByEditIdMutationOptions = <TError = NotFoundResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postMapFileByEditId>>, TError,{editId: number | string;data: PostMapFileByEditIdBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof postMapFileByEditId>>, TError,{editId: number | string;data: PostMapFileByEditIdBody}, TContext> => {

const mutationKey = ['postMapFileByEditId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postMapFileByEditId>>, {editId: number | string;data: PostMapFileByEditIdBody}> = (props) => {
          const {editId,data} = props ?? {};

          return  postMapFileByEditId(editId,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostMapFileByEditIdMutationResult = NonNullable<Awaited<ReturnType<typeof postMapFileByEditId>>>
    export type PostMapFileByEditIdMutationBody = PostMapFileByEditIdBody
    export type PostMapFileByEditIdMutationError = NotFoundResponse

    export const usePostMapFileByEditId = <TError = NotFoundResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postMapFileByEditId>>, TError,{editId: number | string;data: PostMapFileByEditIdBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postMapFileByEditId>>,
        TError,
        {editId: number | string;data: PostMapFileByEditIdBody},
        TContext
      > => {
      return useMutation(getPostMapFileByEditIdMutationOptions(options), queryClient);
    }
