/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query";

import { env } from "../../env";

import type {
    BadRequestResponse,
    DeletedResponse,
    ForbiddenResponse,
    GetUserMediaFoldersParams,
    GetUserMediasParams,
    InvalidResponse,
    Media,
    MediaList,
    NotConnectedResponse,
    NotFoundResponse,
    PostMediaBody,
    PostMediaFileById200,
    PostMediaFileByIdBody,
    PutMediaAttribute200,
    PutMediaAttributeBody,
    TooLargeResponse,
} from "../model";

import { fetchWithAuth } from ".././fetchWithAuth";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
    const result = { queryKey } as T & { queryKey: K };
    for (const key of Object.keys(query)) {
        // The explicit queryKey always wins, matching the previous
        // `{ ...query, queryKey }` spread where it was set last.
        if (key === "queryKey") continue;
        Object.defineProperty(result, key, {
            enumerable: true,
            configurable: true,
            get: () => (query as Record<string, unknown>)[key],
        });
    }
    return result;
};

export type getUserMediasResponse200 = {
    data: MediaList;
    status: 200;
};

export type getUserMediasResponse206 = {
    data: MediaList;
    status: 206;
};

export type getUserMediasResponse401 = {
    data: NotConnectedResponse;
    status: 401;
};

export type getUserMediasResponse403 = {
    data: ForbiddenResponse;
    status: 403;
};

export type getUserMediasResponseSuccess = (getUserMediasResponse200 | getUserMediasResponse206) & {
    headers: Headers;
};
export type getUserMediasResponseError = (getUserMediasResponse401 | getUserMediasResponse403) & {
    headers: Headers;
};

export type getUserMediasResponse = getUserMediasResponseSuccess | getUserMediasResponseError;

export const getGetUserMediasUrl = (params?: GetUserMediasParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : String(value));
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0 ? `${env.API_EDITOR_URL}/api/medias?${stringifiedParams}` : `${env.API_EDITOR_URL}/api/medias`;
};

/**
 * Renvoie les medias de l'utilisateur connecté
 */
export const getUserMedias = async (params?: GetUserMediasParams, options?: RequestInit): Promise<getUserMediasResponse> => {
    return fetchWithAuth<getUserMediasResponse>(getGetUserMediasUrl(params), {
        ...options,
        method: "GET",
    });
};

export const getGetUserMediasQueryKey = (params?: GetUserMediasParams) => {
    return [`${env.API_EDITOR_URL}/api/medias`, ...(params ? [params] : [])] as const;
};

export const getGetUserMediasQueryOptions = <TData = Awaited<ReturnType<typeof getUserMedias>>, TError = NotConnectedResponse | ForbiddenResponse>(
    params?: GetUserMediasParams,
    options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserMedias>>, TError, TData>>; request?: SecondParameter<typeof fetchWithAuth> }
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetUserMediasQueryKey(params);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserMedias>>> = ({ signal }) => getUserMedias(params, { signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getUserMedias>>, TError, TData> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };
};

export type GetUserMediasQueryResult = NonNullable<Awaited<ReturnType<typeof getUserMedias>>>;
export type GetUserMediasQueryError = NotConnectedResponse | ForbiddenResponse;

export function useGetUserMedias<TData = Awaited<ReturnType<typeof getUserMedias>>, TError = NotConnectedResponse | ForbiddenResponse>(
    params: undefined | GetUserMediasParams,
    options: {
        query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserMedias>>, TError, TData>> &
            Pick<DefinedInitialDataOptions<Awaited<ReturnType<typeof getUserMedias>>, TError, Awaited<ReturnType<typeof getUserMedias>>>, "initialData">;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUserMedias<TData = Awaited<ReturnType<typeof getUserMedias>>, TError = NotConnectedResponse | ForbiddenResponse>(
    params?: GetUserMediasParams,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserMedias>>, TError, TData>> &
            Pick<UndefinedInitialDataOptions<Awaited<ReturnType<typeof getUserMedias>>, TError, Awaited<ReturnType<typeof getUserMedias>>>, "initialData">;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUserMedias<TData = Awaited<ReturnType<typeof getUserMedias>>, TError = NotConnectedResponse | ForbiddenResponse>(
    params?: GetUserMediasParams,
    options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserMedias>>, TError, TData>>; request?: SecondParameter<typeof fetchWithAuth> },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetUserMedias<TData = Awaited<ReturnType<typeof getUserMedias>>, TError = NotConnectedResponse | ForbiddenResponse>(
    params?: GetUserMediasParams,
    options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserMedias>>, TError, TData>>; request?: SecondParameter<typeof fetchWithAuth> },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const queryOptions = getGetUserMediasQueryOptions(params, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

    return withQueryKey(query, queryOptions.queryKey);
}

export const prefetchGetUserMediasQuery = async <TData = Awaited<ReturnType<typeof getUserMedias>>, TError = NotConnectedResponse | ForbiddenResponse>(
    queryClient: QueryClient,
    params?: GetUserMediasParams,
    options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserMedias>>, TError, TData>>; request?: SecondParameter<typeof fetchWithAuth> }
): Promise<QueryClient> => {
    const queryOptions = getGetUserMediasQueryOptions(params, options);

    await queryClient.prefetchQuery(queryOptions);

    return queryClient;
};

export type postMediaResponse201 = {
    data: Media;
    status: 201;
};

export type postMediaResponse400 = {
    data: BadRequestResponse;
    status: 400;
};

export type postMediaResponse401 = {
    data: NotConnectedResponse;
    status: 401;
};

export type postMediaResponse403 = {
    data: ForbiddenResponse;
    status: 403;
};

export type postMediaResponse413 = {
    data: TooLargeResponse;
    status: 413;
};

export type postMediaResponseSuccess = postMediaResponse201 & {
    headers: Headers;
};
export type postMediaResponseError = (postMediaResponse400 | postMediaResponse401 | postMediaResponse403 | postMediaResponse413) & {
    headers: Headers;
};

export type postMediaResponse = postMediaResponseSuccess | postMediaResponseError;

export const getPostMediaUrl = () => {
    return `${env.API_EDITOR_URL}/api/medias`;
};

/**
 * Ajoute un media à l'utilisateur connecté ou à l'organisation d'identifiant organization_id si renseigné
 */
export const postMedia = async (postMediaBody: PostMediaBody, options?: RequestInit): Promise<postMediaResponse> => {
    const formData = new FormData();
    formData.append(`file`, postMediaBody.file);
    if (postMediaBody.folder !== undefined) {
        formData.append(`folder`, postMediaBody.folder);
    }
    if (postMediaBody.name !== undefined) {
        formData.append(`name`, postMediaBody.name);
    }
    if (postMediaBody.organization_id !== undefined && postMediaBody.organization_id !== null) {
        formData.append(`organization_id`, postMediaBody.organization_id);
    }

    return fetchWithAuth<postMediaResponse>(getPostMediaUrl(), {
        ...options,
        method: "POST",
        body: formData,
    });
};

export const getPostMediaMutationOptions = <
    TError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse | TooLargeResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof postMedia>>, TError, { data: PostMediaBody }, TContext>;
    request?: SecondParameter<typeof fetchWithAuth>;
}): UseMutationOptions<Awaited<ReturnType<typeof postMedia>>, TError, { data: PostMediaBody }, TContext> => {
    const mutationKey = ["postMedia"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<Awaited<ReturnType<typeof postMedia>>, { data: PostMediaBody }> = (props) => {
        const { data } = props ?? {};

        return postMedia(data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type PostMediaMutationResult = NonNullable<Awaited<ReturnType<typeof postMedia>>>;
export type PostMediaMutationBody = PostMediaBody;
export type PostMediaMutationError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse | TooLargeResponse;

export const usePostMedia = <TError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse | TooLargeResponse, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<Awaited<ReturnType<typeof postMedia>>, TError, { data: PostMediaBody }, TContext>;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof postMedia>>, TError, { data: PostMediaBody }, TContext> => {
    return useMutation(getPostMediaMutationOptions(options), queryClient);
};
export type getUserMediaFoldersResponse200 = {
    data: string[];
    status: 200;
};

export type getUserMediaFoldersResponse401 = {
    data: NotConnectedResponse;
    status: 401;
};

export type getUserMediaFoldersResponseSuccess = getUserMediaFoldersResponse200 & {
    headers: Headers;
};
export type getUserMediaFoldersResponseError = getUserMediaFoldersResponse401 & {
    headers: Headers;
};

export type getUserMediaFoldersResponse = getUserMediaFoldersResponseSuccess | getUserMediaFoldersResponseError;

export const getGetUserMediaFoldersUrl = (params?: GetUserMediaFoldersParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : String(value));
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0 ? `${env.API_EDITOR_URL}/api/medias/folders?${stringifiedParams}` : `${env.API_EDITOR_URL}/api/medias/folders`;
};

/**
 * Renvoie les dossiers d'images de l'utilisateur
 */
export const getUserMediaFolders = async (params?: GetUserMediaFoldersParams, options?: RequestInit): Promise<getUserMediaFoldersResponse> => {
    return fetchWithAuth<getUserMediaFoldersResponse>(getGetUserMediaFoldersUrl(params), {
        ...options,
        method: "GET",
    });
};

export const getGetUserMediaFoldersQueryKey = (params?: GetUserMediaFoldersParams) => {
    return [`${env.API_EDITOR_URL}/api/medias/folders`, ...(params ? [params] : [])] as const;
};

export const getGetUserMediaFoldersQueryOptions = <TData = Awaited<ReturnType<typeof getUserMediaFolders>>, TError = NotConnectedResponse>(
    params?: GetUserMediaFoldersParams,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserMediaFolders>>, TError, TData>>;
        request?: SecondParameter<typeof fetchWithAuth>;
    }
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetUserMediaFoldersQueryKey(params);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserMediaFolders>>> = ({ signal }) => getUserMediaFolders(params, { signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getUserMediaFolders>>, TError, TData> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };
};

export type GetUserMediaFoldersQueryResult = NonNullable<Awaited<ReturnType<typeof getUserMediaFolders>>>;
export type GetUserMediaFoldersQueryError = NotConnectedResponse;

export function useGetUserMediaFolders<TData = Awaited<ReturnType<typeof getUserMediaFolders>>, TError = NotConnectedResponse>(
    params: undefined | GetUserMediaFoldersParams,
    options: {
        query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserMediaFolders>>, TError, TData>> &
            Pick<
                DefinedInitialDataOptions<Awaited<ReturnType<typeof getUserMediaFolders>>, TError, Awaited<ReturnType<typeof getUserMediaFolders>>>,
                "initialData"
            >;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUserMediaFolders<TData = Awaited<ReturnType<typeof getUserMediaFolders>>, TError = NotConnectedResponse>(
    params?: GetUserMediaFoldersParams,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserMediaFolders>>, TError, TData>> &
            Pick<
                UndefinedInitialDataOptions<Awaited<ReturnType<typeof getUserMediaFolders>>, TError, Awaited<ReturnType<typeof getUserMediaFolders>>>,
                "initialData"
            >;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetUserMediaFolders<TData = Awaited<ReturnType<typeof getUserMediaFolders>>, TError = NotConnectedResponse>(
    params?: GetUserMediaFoldersParams,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserMediaFolders>>, TError, TData>>;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetUserMediaFolders<TData = Awaited<ReturnType<typeof getUserMediaFolders>>, TError = NotConnectedResponse>(
    params?: GetUserMediaFoldersParams,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserMediaFolders>>, TError, TData>>;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const queryOptions = getGetUserMediaFoldersQueryOptions(params, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

    return withQueryKey(query, queryOptions.queryKey);
}

export const prefetchGetUserMediaFoldersQuery = async <TData = Awaited<ReturnType<typeof getUserMediaFolders>>, TError = NotConnectedResponse>(
    queryClient: QueryClient,
    params?: GetUserMediaFoldersParams,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getUserMediaFolders>>, TError, TData>>;
        request?: SecondParameter<typeof fetchWithAuth>;
    }
): Promise<QueryClient> => {
    const queryOptions = getGetUserMediaFoldersQueryOptions(params, options);

    await queryClient.prefetchQuery(queryOptions);

    return queryClient;
};

export type getImageByFilenameResponse200 = {
    data: void;
    status: 200;
};

export type getImageByFilenameResponse404 = {
    data: NotFoundResponse;
    status: 404;
};

export type getImageByFilenameResponse451 = {
    data: InvalidResponse;
    status: 451;
};

export type getImageByFilenameResponseSuccess = getImageByFilenameResponse200 & {
    headers: Headers;
};
export type getImageByFilenameResponseError = (getImageByFilenameResponse404 | getImageByFilenameResponse451) & {
    headers: Headers;
};

export type getImageByFilenameResponse = getImageByFilenameResponseSuccess | getImageByFilenameResponseError;

export const getGetImageByFilenameUrl = (filename: string) => {
    return `${env.API_EDITOR_URL}/api/image/${filename}`;
};

/**
 * Renvoie l'image au format binaire, l'extension n'est pas prise en compte (ex : abc1234).
 * Préfixer le filename par 'thumb_' pour recevoir la miniature (200px sur la plus grande dimension).
 */
export const getImageByFilename = async (filename: string, options?: RequestInit): Promise<getImageByFilenameResponse> => {
    return fetchWithAuth<getImageByFilenameResponse>(getGetImageByFilenameUrl(filename), {
        ...options,
        method: "GET",
    });
};

export const getGetImageByFilenameQueryKey = (filename: string) => {
    return [`${env.API_EDITOR_URL}/api/image/${filename}`] as const;
};

export const getGetImageByFilenameQueryOptions = <TData = Awaited<ReturnType<typeof getImageByFilename>>, TError = NotFoundResponse | InvalidResponse>(
    filename: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getImageByFilename>>, TError, TData>>;
        request?: SecondParameter<typeof fetchWithAuth>;
    }
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetImageByFilenameQueryKey(filename);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getImageByFilename>>> = ({ signal }) => getImageByFilename(filename, { signal, ...requestOptions });

    return { queryKey, queryFn, enabled: filename !== null && filename !== undefined, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getImageByFilename>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetImageByFilenameQueryResult = NonNullable<Awaited<ReturnType<typeof getImageByFilename>>>;
export type GetImageByFilenameQueryError = NotFoundResponse | InvalidResponse;

export function useGetImageByFilename<TData = Awaited<ReturnType<typeof getImageByFilename>>, TError = NotFoundResponse | InvalidResponse>(
    filename: string,
    options: {
        query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getImageByFilename>>, TError, TData>> &
            Pick<
                DefinedInitialDataOptions<Awaited<ReturnType<typeof getImageByFilename>>, TError, Awaited<ReturnType<typeof getImageByFilename>>>,
                "initialData"
            >;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetImageByFilename<TData = Awaited<ReturnType<typeof getImageByFilename>>, TError = NotFoundResponse | InvalidResponse>(
    filename: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getImageByFilename>>, TError, TData>> &
            Pick<
                UndefinedInitialDataOptions<Awaited<ReturnType<typeof getImageByFilename>>, TError, Awaited<ReturnType<typeof getImageByFilename>>>,
                "initialData"
            >;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetImageByFilename<TData = Awaited<ReturnType<typeof getImageByFilename>>, TError = NotFoundResponse | InvalidResponse>(
    filename: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getImageByFilename>>, TError, TData>>;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetImageByFilename<TData = Awaited<ReturnType<typeof getImageByFilename>>, TError = NotFoundResponse | InvalidResponse>(
    filename: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getImageByFilename>>, TError, TData>>;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const queryOptions = getGetImageByFilenameQueryOptions(filename, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

    return withQueryKey(query, queryOptions.queryKey);
}

export const prefetchGetImageByFilenameQuery = async <TData = Awaited<ReturnType<typeof getImageByFilename>>, TError = NotFoundResponse | InvalidResponse>(
    queryClient: QueryClient,
    filename: string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getImageByFilename>>, TError, TData>>;
        request?: SecondParameter<typeof fetchWithAuth>;
    }
): Promise<QueryClient> => {
    const queryOptions = getGetImageByFilenameQueryOptions(filename, options);

    await queryClient.prefetchQuery(queryOptions);

    return queryClient;
};

export type deleteMediaByIdResponse204 = {
    data: DeletedResponse;
    status: 204;
};

export type deleteMediaByIdResponse401 = {
    data: NotConnectedResponse;
    status: 401;
};

export type deleteMediaByIdResponse403 = {
    data: ForbiddenResponse;
    status: 403;
};

export type deleteMediaByIdResponse404 = {
    data: NotFoundResponse;
    status: 404;
};

export type deleteMediaByIdResponse451 = {
    data: InvalidResponse;
    status: 451;
};

export type deleteMediaByIdResponseSuccess = deleteMediaByIdResponse204 & {
    headers: Headers;
};
export type deleteMediaByIdResponseError = (
    deleteMediaByIdResponse401 | deleteMediaByIdResponse403 | deleteMediaByIdResponse404 | deleteMediaByIdResponse451
) & {
    headers: Headers;
};

export type deleteMediaByIdResponse = deleteMediaByIdResponseSuccess | deleteMediaByIdResponseError;

export const getDeleteMediaByIdUrl = (id: number | string) => {
    return `${env.API_EDITOR_URL}/api/medias/${id}`;
};

/**
 * Supprime un media de l'utilisateur connecté. Un média non valide ne peut pas être supprimé
 */
export const deleteMediaById = async (id: number | string, options?: RequestInit): Promise<deleteMediaByIdResponse> => {
    return fetchWithAuth<deleteMediaByIdResponse>(getDeleteMediaByIdUrl(id), {
        ...options,
        method: "DELETE",
    });
};

export const getDeleteMediaByIdMutationOptions = <
    TError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse | InvalidResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteMediaById>>, TError, { id: number | string }, TContext>;
    request?: SecondParameter<typeof fetchWithAuth>;
}): UseMutationOptions<Awaited<ReturnType<typeof deleteMediaById>>, TError, { id: number | string }, TContext> => {
    const mutationKey = ["deleteMediaById"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteMediaById>>, { id: number | string }> = (props) => {
        const { id } = props ?? {};

        return deleteMediaById(id, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type DeleteMediaByIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteMediaById>>>;

export type DeleteMediaByIdMutationError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse | InvalidResponse;

export const useDeleteMediaById = <TError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse | InvalidResponse, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteMediaById>>, TError, { id: number | string }, TContext>;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof deleteMediaById>>, TError, { id: number | string }, TContext> => {
    return useMutation(getDeleteMediaByIdMutationOptions(options), queryClient);
};
export type putMediaAttributeResponse200 = {
    data: PutMediaAttribute200;
    status: 200;
};

export type putMediaAttributeResponse400 = {
    data: BadRequestResponse;
    status: 400;
};

export type putMediaAttributeResponse401 = {
    data: NotConnectedResponse;
    status: 401;
};

export type putMediaAttributeResponse403 = {
    data: ForbiddenResponse;
    status: 403;
};

export type putMediaAttributeResponse404 = {
    data: NotFoundResponse;
    status: 404;
};

export type putMediaAttributeResponseSuccess = putMediaAttributeResponse200 & {
    headers: Headers;
};
export type putMediaAttributeResponseError = (
    putMediaAttributeResponse400 | putMediaAttributeResponse401 | putMediaAttributeResponse403 | putMediaAttributeResponse404
) & {
    headers: Headers;
};

export type putMediaAttributeResponse = putMediaAttributeResponseSuccess | putMediaAttributeResponseError;

export const getPutMediaAttributeUrl = (id: number | string, attribute: string) => {
    return `${env.API_EDITOR_URL}/api/medias/${id}/${attribute}`;
};

/**
 * Affecte value à l'attribut du media d'identifiant id (attribute dans ['folder', 'name'])
 */
export const putMediaAttribute = async (
    id: number | string,
    attribute: string,
    putMediaAttributeBody: PutMediaAttributeBody,
    options?: RequestInit
): Promise<putMediaAttributeResponse> => {
    return fetchWithAuth<putMediaAttributeResponse>(getPutMediaAttributeUrl(id, attribute), {
        ...options,
        method: "PUT",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(putMediaAttributeBody),
    });
};

export const getPutMediaAttributeMutationOptions = <
    TError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse | NotFoundResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof putMediaAttribute>>,
        TError,
        { id: number | string; attribute: string; data: PutMediaAttributeBody },
        TContext
    >;
    request?: SecondParameter<typeof fetchWithAuth>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof putMediaAttribute>>,
    TError,
    { id: number | string; attribute: string; data: PutMediaAttributeBody },
    TContext
> => {
    const mutationKey = ["putMediaAttribute"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof putMediaAttribute>>,
        { id: number | string; attribute: string; data: PutMediaAttributeBody }
    > = (props) => {
        const { id, attribute, data } = props ?? {};

        return putMediaAttribute(id, attribute, data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type PutMediaAttributeMutationResult = NonNullable<Awaited<ReturnType<typeof putMediaAttribute>>>;
export type PutMediaAttributeMutationBody = PutMediaAttributeBody;
export type PutMediaAttributeMutationError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse | NotFoundResponse;

export const usePutMediaAttribute = <TError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse | NotFoundResponse, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof putMediaAttribute>>,
            TError,
            { id: number | string; attribute: string; data: PutMediaAttributeBody },
            TContext
        >;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof putMediaAttribute>>,
    TError,
    { id: number | string; attribute: string; data: PutMediaAttributeBody },
    TContext
> => {
    return useMutation(getPutMediaAttributeMutationOptions(options), queryClient);
};
export type postMediaFileByIdResponse200 = {
    data: PostMediaFileById200;
    status: 200;
};

export type postMediaFileByIdResponse400 = {
    data: BadRequestResponse;
    status: 400;
};

export type postMediaFileByIdResponse401 = {
    data: NotConnectedResponse;
    status: 401;
};

export type postMediaFileByIdResponse403 = {
    data: ForbiddenResponse;
    status: 403;
};

export type postMediaFileByIdResponse404 = {
    data: NotFoundResponse;
    status: 404;
};

export type postMediaFileByIdResponse413 = {
    data: TooLargeResponse;
    status: 413;
};

export type postMediaFileByIdResponseSuccess = postMediaFileByIdResponse200 & {
    headers: Headers;
};
export type postMediaFileByIdResponseError = (
    postMediaFileByIdResponse400 | postMediaFileByIdResponse401 | postMediaFileByIdResponse403 | postMediaFileByIdResponse404 | postMediaFileByIdResponse413
) & {
    headers: Headers;
};

export type postMediaFileByIdResponse = postMediaFileByIdResponseSuccess | postMediaFileByIdResponseError;

export const getPostMediaFileByIdUrl = (id: number | string) => {
    return `${env.API_EDITOR_URL}/api/medias/${id}/file`;
};

/**
 * Modifie l'image associée au media
 */
export const postMediaFileById = async (
    id: number | string,
    postMediaFileByIdBody: PostMediaFileByIdBody,
    options?: RequestInit
): Promise<postMediaFileByIdResponse> => {
    const formData = new FormData();
    formData.append(`file`, postMediaFileByIdBody.file);

    return fetchWithAuth<postMediaFileByIdResponse>(getPostMediaFileByIdUrl(id), {
        ...options,
        method: "POST",
        body: formData,
    });
};

export const getPostMediaFileByIdMutationOptions = <
    TError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse | NotFoundResponse | TooLargeResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof postMediaFileById>>, TError, { id: number | string; data: PostMediaFileByIdBody }, TContext>;
    request?: SecondParameter<typeof fetchWithAuth>;
}): UseMutationOptions<Awaited<ReturnType<typeof postMediaFileById>>, TError, { id: number | string; data: PostMediaFileByIdBody }, TContext> => {
    const mutationKey = ["postMediaFileById"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<Awaited<ReturnType<typeof postMediaFileById>>, { id: number | string; data: PostMediaFileByIdBody }> = (props) => {
        const { id, data } = props ?? {};

        return postMediaFileById(id, data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type PostMediaFileByIdMutationResult = NonNullable<Awaited<ReturnType<typeof postMediaFileById>>>;
export type PostMediaFileByIdMutationBody = PostMediaFileByIdBody;
export type PostMediaFileByIdMutationError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse | NotFoundResponse | TooLargeResponse;

export const usePostMediaFileById = <
    TError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse | NotFoundResponse | TooLargeResponse,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<Awaited<ReturnType<typeof postMediaFileById>>, TError, { id: number | string; data: PostMediaFileByIdBody }, TContext>;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof postMediaFileById>>, TError, { id: number | string; data: PostMediaFileByIdBody }, TContext> => {
    return useMutation(getPostMediaFileByIdMutationOptions(options), queryClient);
};
