/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * API macarte
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import {
  env
} from '../../env';

import type {
  ApiMediasFoldersParams,
  ApiMediasParams,
  BadRequestResponse,
  CreateApiMediasBody,
  CreateApiMediasIdFile200,
  CreateApiMediasIdFileBody,
  DeletedResponse,
  ForbiddenResponse,
  InvalidResponse,
  Media,
  MediaList,
  NotConnectedResponse,
  NotFoundResponse,
  TooLargeResponse,
  UpdateApiMediasIdAttribute200,
  UpdateApiMediasIdAttributeBody
} from '../model';





const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export type apiMediasResponse200 = {
  data: MediaList[]
  status: 200
}

export type apiMediasResponse401 = {
  data: NotConnectedResponse
  status: 401
}

export type apiMediasResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type apiMediasResponseSuccess = (apiMediasResponse200) & {
  headers: Headers;
};
export type apiMediasResponseError = (apiMediasResponse401 | apiMediasResponse403) & {
  headers: Headers;
};

export type apiMediasResponse = (apiMediasResponseSuccess | apiMediasResponseError)

export const getApiMediasUrl = (params?: ApiMediasParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${env.API_EDITEUR_URL}/api/medias?${stringifiedParams}` : `${env.API_EDITEUR_URL}/api/medias`
}

/**
 * Renvoie les medias de l'utilisateur connecté
 */
export const apiMedias = async (params?: ApiMediasParams, options?: RequestInit): Promise<apiMediasResponse> => {

  const res = await fetch(getApiMediasUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiMediasResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiMediasResponse
}





export const getApiMediasQueryKey = (params?: ApiMediasParams,) => {
    return [
    `${env.API_EDITEUR_URL}/api/medias`, ...(params ? [params] : [])
    ] as const;
    }


export const getApiMediasQueryOptions = <TData = Awaited<ReturnType<typeof apiMedias>>, TError = NotConnectedResponse | ForbiddenResponse>(params?: ApiMediasParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMedias>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApiMediasQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof apiMedias>>> = ({ signal }) => apiMedias(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof apiMedias>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApiMediasQueryResult = NonNullable<Awaited<ReturnType<typeof apiMedias>>>
export type ApiMediasQueryError = NotConnectedResponse | ForbiddenResponse


export function useApiMedias<TData = Awaited<ReturnType<typeof apiMedias>>, TError = NotConnectedResponse | ForbiddenResponse>(
 params: undefined |  ApiMediasParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMedias>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiMedias>>,
          TError,
          Awaited<ReturnType<typeof apiMedias>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiMedias<TData = Awaited<ReturnType<typeof apiMedias>>, TError = NotConnectedResponse | ForbiddenResponse>(
 params?: ApiMediasParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMedias>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiMedias>>,
          TError,
          Awaited<ReturnType<typeof apiMedias>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiMedias<TData = Awaited<ReturnType<typeof apiMedias>>, TError = NotConnectedResponse | ForbiddenResponse>(
 params?: ApiMediasParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMedias>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApiMedias<TData = Awaited<ReturnType<typeof apiMedias>>, TError = NotConnectedResponse | ForbiddenResponse>(
 params?: ApiMediasParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMedias>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApiMediasQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const prefetchApiMediasQuery = async <TData = Awaited<ReturnType<typeof apiMedias>>, TError = NotConnectedResponse | ForbiddenResponse>(
 queryClient: QueryClient, params?: ApiMediasParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMedias>>, TError, TData>>, fetch?: RequestInit}

  ): Promise<QueryClient> => {

  const queryOptions = getApiMediasQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





export type createApiMediasResponse201 = {
  data: Media
  status: 201
}

export type createApiMediasResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type createApiMediasResponse401 = {
  data: NotConnectedResponse
  status: 401
}

export type createApiMediasResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type createApiMediasResponse413 = {
  data: TooLargeResponse
  status: 413
}

export type createApiMediasResponseSuccess = (createApiMediasResponse201) & {
  headers: Headers;
};
export type createApiMediasResponseError = (createApiMediasResponse400 | createApiMediasResponse401 | createApiMediasResponse403 | createApiMediasResponse413) & {
  headers: Headers;
};

export type createApiMediasResponse = (createApiMediasResponseSuccess | createApiMediasResponseError)

export const getCreateApiMediasUrl = () => {




  return `${env.API_EDITEUR_URL}/api/medias`
}

/**
 * Ajoute un media à l'utilisateur connecté ou à l'organisation d'identifiant organization_id si renseigné
 */
export const createApiMedias = async (createApiMediasBody: CreateApiMediasBody, options?: RequestInit): Promise<createApiMediasResponse> => {
    const formData = new FormData();
formData.append(`file`, createApiMediasBody.file);
if(createApiMediasBody.folder !== undefined) {
 formData.append(`folder`, createApiMediasBody.folder);
 }
if(createApiMediasBody.name !== undefined) {
 formData.append(`name`, createApiMediasBody.name);
 }
if(createApiMediasBody.organization_id !== undefined && createApiMediasBody.organization_id !== null) {
 formData.append(`organization_id`, createApiMediasBody.organization_id);
 }

  const res = await fetch(getCreateApiMediasUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createApiMediasResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createApiMediasResponse
}





export const getCreateApiMediasMutationOptions = <TError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse | TooLargeResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createApiMedias>>, TError,{data: CreateApiMediasBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createApiMedias>>, TError,{data: CreateApiMediasBody}, TContext> => {

const mutationKey = ['createApiMedias'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createApiMedias>>, {data: CreateApiMediasBody}> = (props) => {
          const {data} = props ?? {};

          return  createApiMedias(data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateApiMediasMutationResult = NonNullable<Awaited<ReturnType<typeof createApiMedias>>>
    export type CreateApiMediasMutationBody = CreateApiMediasBody
    export type CreateApiMediasMutationError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse | TooLargeResponse

    export const useCreateApiMedias = <TError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse | TooLargeResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createApiMedias>>, TError,{data: CreateApiMediasBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createApiMedias>>,
        TError,
        {data: CreateApiMediasBody},
        TContext
      > => {
      return useMutation(getCreateApiMediasMutationOptions(options), queryClient);
    }
    export type apiMediasFoldersResponse200 = {
  data: string[]
  status: 200
}

export type apiMediasFoldersResponse401 = {
  data: NotConnectedResponse
  status: 401
}

export type apiMediasFoldersResponseSuccess = (apiMediasFoldersResponse200) & {
  headers: Headers;
};
export type apiMediasFoldersResponseError = (apiMediasFoldersResponse401) & {
  headers: Headers;
};

export type apiMediasFoldersResponse = (apiMediasFoldersResponseSuccess | apiMediasFoldersResponseError)

export const getApiMediasFoldersUrl = (params?: ApiMediasFoldersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `${env.API_EDITEUR_URL}/api/medias/folders?${stringifiedParams}` : `${env.API_EDITEUR_URL}/api/medias/folders`
}

/**
 * Renvoie dossiers d'images de l'utilsiateur
 */
export const apiMediasFolders = async (params?: ApiMediasFoldersParams, options?: RequestInit): Promise<apiMediasFoldersResponse> => {

  const res = await fetch(getApiMediasFoldersUrl(params),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiMediasFoldersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as apiMediasFoldersResponse
}





export const getApiMediasFoldersQueryKey = (params?: ApiMediasFoldersParams,) => {
    return [
    `${env.API_EDITEUR_URL}/api/medias/folders`, ...(params ? [params] : [])
    ] as const;
    }


export const getApiMediasFoldersQueryOptions = <TData = Awaited<ReturnType<typeof apiMediasFolders>>, TError = NotConnectedResponse>(params?: ApiMediasFoldersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMediasFolders>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApiMediasFoldersQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof apiMediasFolders>>> = ({ signal }) => apiMediasFolders(params, { signal, ...fetchOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof apiMediasFolders>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApiMediasFoldersQueryResult = NonNullable<Awaited<ReturnType<typeof apiMediasFolders>>>
export type ApiMediasFoldersQueryError = NotConnectedResponse


export function useApiMediasFolders<TData = Awaited<ReturnType<typeof apiMediasFolders>>, TError = NotConnectedResponse>(
 params: undefined |  ApiMediasFoldersParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMediasFolders>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiMediasFolders>>,
          TError,
          Awaited<ReturnType<typeof apiMediasFolders>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiMediasFolders<TData = Awaited<ReturnType<typeof apiMediasFolders>>, TError = NotConnectedResponse>(
 params?: ApiMediasFoldersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMediasFolders>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiMediasFolders>>,
          TError,
          Awaited<ReturnType<typeof apiMediasFolders>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiMediasFolders<TData = Awaited<ReturnType<typeof apiMediasFolders>>, TError = NotConnectedResponse>(
 params?: ApiMediasFoldersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMediasFolders>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApiMediasFolders<TData = Awaited<ReturnType<typeof apiMediasFolders>>, TError = NotConnectedResponse>(
 params?: ApiMediasFoldersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMediasFolders>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApiMediasFoldersQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const prefetchApiMediasFoldersQuery = async <TData = Awaited<ReturnType<typeof apiMediasFolders>>, TError = NotConnectedResponse>(
 queryClient: QueryClient, params?: ApiMediasFoldersParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiMediasFolders>>, TError, TData>>, fetch?: RequestInit}

  ): Promise<QueryClient> => {

  const queryOptions = getApiMediasFoldersQueryOptions(params,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





export type apiImageFilenameResponse200 = {
  data: void
  status: 200
}

export type apiImageFilenameResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type apiImageFilenameResponse451 = {
  data: InvalidResponse
  status: 451
}

export type apiImageFilenameResponseSuccess = (apiImageFilenameResponse200) & {
  headers: Headers;
};
export type apiImageFilenameResponseError = (apiImageFilenameResponse404 | apiImageFilenameResponse451) & {
  headers: Headers;
};

export type apiImageFilenameResponse = (apiImageFilenameResponseSuccess | apiImageFilenameResponseError)

export const getApiImageFilenameUrl = (filename: string,) => {




  return `${env.API_EDITEUR_URL}/api/image/${filename}`
}

/**
 * Renvoie l'image au format binaire, l'extension n'est pas prise en compte (ex : abc1234) <br>
 *                 Préfixer le filename par 'thumb_' pour recevoir la miniature (200px sur la plus grande dimension)
 *      *
 */
export const apiImageFilename = async (filename: string, options?: RequestInit): Promise<apiImageFilenameResponse> => {

  const res = await fetch(getApiImageFilenameUrl(filename),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: apiImageFilenameResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as apiImageFilenameResponse
}





export const getApiImageFilenameQueryKey = (filename: string,) => {
    return [
    `${env.API_EDITEUR_URL}/api/image/${filename}`
    ] as const;
    }


export const getApiImageFilenameQueryOptions = <TData = Awaited<ReturnType<typeof apiImageFilename>>, TError = NotFoundResponse | InvalidResponse>(filename: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiImageFilename>>, TError, TData>>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getApiImageFilenameQueryKey(filename);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof apiImageFilename>>> = ({ signal }) => apiImageFilename(filename, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: filename !== null && filename !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof apiImageFilename>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ApiImageFilenameQueryResult = NonNullable<Awaited<ReturnType<typeof apiImageFilename>>>
export type ApiImageFilenameQueryError = NotFoundResponse | InvalidResponse


export function useApiImageFilename<TData = Awaited<ReturnType<typeof apiImageFilename>>, TError = NotFoundResponse | InvalidResponse>(
 filename: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiImageFilename>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiImageFilename>>,
          TError,
          Awaited<ReturnType<typeof apiImageFilename>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiImageFilename<TData = Awaited<ReturnType<typeof apiImageFilename>>, TError = NotFoundResponse | InvalidResponse>(
 filename: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiImageFilename>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiImageFilename>>,
          TError,
          Awaited<ReturnType<typeof apiImageFilename>>
        > , 'initialData'
      >, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useApiImageFilename<TData = Awaited<ReturnType<typeof apiImageFilename>>, TError = NotFoundResponse | InvalidResponse>(
 filename: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiImageFilename>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useApiImageFilename<TData = Awaited<ReturnType<typeof apiImageFilename>>, TError = NotFoundResponse | InvalidResponse>(
 filename: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiImageFilename>>, TError, TData>>, fetch?: RequestInit}
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getApiImageFilenameQueryOptions(filename,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

export const prefetchApiImageFilenameQuery = async <TData = Awaited<ReturnType<typeof apiImageFilename>>, TError = NotFoundResponse | InvalidResponse>(
 queryClient: QueryClient, filename: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof apiImageFilename>>, TError, TData>>, fetch?: RequestInit}

  ): Promise<QueryClient> => {

  const queryOptions = getApiImageFilenameQueryOptions(filename,options)

  await queryClient.prefetchQuery(queryOptions);

  return queryClient;
}





export type deleteApiMediasIdResponse204 = {
  data: DeletedResponse
  status: 204
}

export type deleteApiMediasIdResponse401 = {
  data: NotConnectedResponse
  status: 401
}

export type deleteApiMediasIdResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type deleteApiMediasIdResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type deleteApiMediasIdResponse451 = {
  data: InvalidResponse
  status: 451
}

export type deleteApiMediasIdResponseSuccess = (deleteApiMediasIdResponse204) & {
  headers: Headers;
};
export type deleteApiMediasIdResponseError = (deleteApiMediasIdResponse401 | deleteApiMediasIdResponse403 | deleteApiMediasIdResponse404 | deleteApiMediasIdResponse451) & {
  headers: Headers;
};

export type deleteApiMediasIdResponse = (deleteApiMediasIdResponseSuccess | deleteApiMediasIdResponseError)

export const getDeleteApiMediasIdUrl = (id: number | string,) => {




  return `${env.API_EDITEUR_URL}/api/medias/${id}`
}

/**
 * Supprime un media de l'utilisateur connecté. Un média non valide ne peut pas être supprimé
 */
export const deleteApiMediasId = async (id: number | string, options?: RequestInit): Promise<deleteApiMediasIdResponse> => {

  const res = await fetch(getDeleteApiMediasIdUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteApiMediasIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as deleteApiMediasIdResponse
}





export const getDeleteApiMediasIdMutationOptions = <TError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse | InvalidResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiMediasId>>, TError,{id: number | string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteApiMediasId>>, TError,{id: number | string}, TContext> => {

const mutationKey = ['deleteApiMediasId'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteApiMediasId>>, {id: number | string}> = (props) => {
          const {id} = props ?? {};

          return  deleteApiMediasId(id,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteApiMediasIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteApiMediasId>>>

    export type DeleteApiMediasIdMutationError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse | InvalidResponse

    export const useDeleteApiMediasId = <TError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse | InvalidResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteApiMediasId>>, TError,{id: number | string}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteApiMediasId>>,
        TError,
        {id: number | string},
        TContext
      > => {
      return useMutation(getDeleteApiMediasIdMutationOptions(options), queryClient);
    }
    export type updateApiMediasIdAttributeResponse200 = {
  data: UpdateApiMediasIdAttribute200
  status: 200
}

export type updateApiMediasIdAttributeResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type updateApiMediasIdAttributeResponse401 = {
  data: NotConnectedResponse
  status: 401
}

export type updateApiMediasIdAttributeResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type updateApiMediasIdAttributeResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type updateApiMediasIdAttributeResponseSuccess = (updateApiMediasIdAttributeResponse200) & {
  headers: Headers;
};
export type updateApiMediasIdAttributeResponseError = (updateApiMediasIdAttributeResponse400 | updateApiMediasIdAttributeResponse401 | updateApiMediasIdAttributeResponse403 | updateApiMediasIdAttributeResponse404) & {
  headers: Headers;
};

export type updateApiMediasIdAttributeResponse = (updateApiMediasIdAttributeResponseSuccess | updateApiMediasIdAttributeResponseError)

export const getUpdateApiMediasIdAttributeUrl = (id: number | string,
    attribute: string,) => {




  return `${env.API_EDITEUR_URL}/api/medias/${id}/${attribute}`
}

/**
 * Affecte value à l'attribut du media d'identifiant id (attibute dans ['folder', 'name'])
 */
export const updateApiMediasIdAttribute = async (id: number | string,
    attribute: string,
    updateApiMediasIdAttributeBody: UpdateApiMediasIdAttributeBody, options?: RequestInit): Promise<updateApiMediasIdAttributeResponse> => {

  const res = await fetch(getUpdateApiMediasIdAttributeUrl(id,attribute),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateApiMediasIdAttributeBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: updateApiMediasIdAttributeResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as updateApiMediasIdAttributeResponse
}





export const getUpdateApiMediasIdAttributeMutationOptions = <TError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse | NotFoundResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateApiMediasIdAttribute>>, TError,{id: number | string;attribute: string;data: UpdateApiMediasIdAttributeBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof updateApiMediasIdAttribute>>, TError,{id: number | string;attribute: string;data: UpdateApiMediasIdAttributeBody}, TContext> => {

const mutationKey = ['updateApiMediasIdAttribute'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateApiMediasIdAttribute>>, {id: number | string;attribute: string;data: UpdateApiMediasIdAttributeBody}> = (props) => {
          const {id,attribute,data} = props ?? {};

          return  updateApiMediasIdAttribute(id,attribute,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateApiMediasIdAttributeMutationResult = NonNullable<Awaited<ReturnType<typeof updateApiMediasIdAttribute>>>
    export type UpdateApiMediasIdAttributeMutationBody = UpdateApiMediasIdAttributeBody
    export type UpdateApiMediasIdAttributeMutationError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse | NotFoundResponse

    export const useUpdateApiMediasIdAttribute = <TError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse | NotFoundResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateApiMediasIdAttribute>>, TError,{id: number | string;attribute: string;data: UpdateApiMediasIdAttributeBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateApiMediasIdAttribute>>,
        TError,
        {id: number | string;attribute: string;data: UpdateApiMediasIdAttributeBody},
        TContext
      > => {
      return useMutation(getUpdateApiMediasIdAttributeMutationOptions(options), queryClient);
    }
    export type createApiMediasIdFileResponse200 = {
  data: CreateApiMediasIdFile200
  status: 200
}

export type createApiMediasIdFileResponse400 = {
  data: BadRequestResponse
  status: 400
}

export type createApiMediasIdFileResponse401 = {
  data: NotConnectedResponse
  status: 401
}

export type createApiMediasIdFileResponse403 = {
  data: ForbiddenResponse
  status: 403
}

export type createApiMediasIdFileResponse404 = {
  data: NotFoundResponse
  status: 404
}

export type createApiMediasIdFileResponse413 = {
  data: TooLargeResponse
  status: 413
}

export type createApiMediasIdFileResponseSuccess = (createApiMediasIdFileResponse200) & {
  headers: Headers;
};
export type createApiMediasIdFileResponseError = (createApiMediasIdFileResponse400 | createApiMediasIdFileResponse401 | createApiMediasIdFileResponse403 | createApiMediasIdFileResponse404 | createApiMediasIdFileResponse413) & {
  headers: Headers;
};

export type createApiMediasIdFileResponse = (createApiMediasIdFileResponseSuccess | createApiMediasIdFileResponseError)

export const getCreateApiMediasIdFileUrl = (id: number | string,) => {




  return `${env.API_EDITEUR_URL}/api/medias/${id}/file`
}

/**
 * Modifie l'image' associé au media
 */
export const createApiMediasIdFile = async (id: number | string,
    createApiMediasIdFileBody: CreateApiMediasIdFileBody, options?: RequestInit): Promise<createApiMediasIdFileResponse> => {
    const formData = new FormData();
formData.append(`file`, createApiMediasIdFileBody.file);

  const res = await fetch(getCreateApiMediasIdFileUrl(id),
  {
    ...options,
    method: 'POST'
    ,
    body: formData
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createApiMediasIdFileResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createApiMediasIdFileResponse
}





export const getCreateApiMediasIdFileMutationOptions = <TError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse | NotFoundResponse | TooLargeResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createApiMediasIdFile>>, TError,{id: number | string;data: CreateApiMediasIdFileBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createApiMediasIdFile>>, TError,{id: number | string;data: CreateApiMediasIdFileBody}, TContext> => {

const mutationKey = ['createApiMediasIdFile'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createApiMediasIdFile>>, {id: number | string;data: CreateApiMediasIdFileBody}> = (props) => {
          const {id,data} = props ?? {};

          return  createApiMediasIdFile(id,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateApiMediasIdFileMutationResult = NonNullable<Awaited<ReturnType<typeof createApiMediasIdFile>>>
    export type CreateApiMediasIdFileMutationBody = CreateApiMediasIdFileBody
    export type CreateApiMediasIdFileMutationError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse | NotFoundResponse | TooLargeResponse

    export const useCreateApiMediasIdFile = <TError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse | NotFoundResponse | TooLargeResponse,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createApiMediasIdFile>>, TError,{id: number | string;data: CreateApiMediasIdFileBody}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createApiMediasIdFile>>,
        TError,
        {id: number | string;data: CreateApiMediasIdFileBody},
        TContext
      > => {
      return useMutation(getCreateApiMediasIdFileMutationOptions(options), queryClient);
    }
