/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * API macarte
 * OpenAPI spec version: 1.0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  CreateApiMediasIdFile200,
  DeletedResponse,
  Media,
  MediaList,
  UpdateApiMediasIdAttribute200
} from '../model';


export const getApiMediasResponseMock = (): MediaList[] => (Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({medias: faker.helpers.arrayElement([Array.from({ length: faker.number.int({min: 1, max: 10}) }, (_, i) => i + 1).map(() => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), name: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), file: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), owner: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), organization_id: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), organization: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), uploaded_at: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), size: faker.helpers.arrayElement([faker.number.int(), undefined]), folder: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), valid: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), view_url: faker.helpers.arrayElement([faker.internet.url(), undefined]), thumb_url: faker.helpers.arrayElement([faker.internet.url(), undefined])})), undefined]), count: faker.helpers.arrayElement([faker.number.int(), undefined]), limit: faker.helpers.arrayElement([faker.number.int(), undefined]), offset: faker.helpers.arrayElement([faker.number.int(), undefined])})))

export const getCreateApiMediasResponseMock = (overrideResponse: Partial<Extract<Media, object>> = {}): Media => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), name: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), file: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), owner: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), organization_id: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), organization: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), uploaded_at: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + 'Z', undefined]), size: faker.helpers.arrayElement([faker.number.int(), undefined]), folder: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), valid: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]), view_url: faker.helpers.arrayElement([faker.internet.url(), undefined]), thumb_url: faker.helpers.arrayElement([faker.internet.url(), undefined]), ...overrideResponse})

export const getApiMediasFoldersResponseMock = (): string[] => (Array.from({length: faker.number.int({min: 1, max: 10})}, () => faker.word.sample()))

export const getDeleteApiMediasIdResponseMock = (overrideResponse: Partial<Extract<DeletedResponse, object>> = {}): DeletedResponse => ({code: faker.helpers.arrayElement([faker.number.int(), undefined]), message: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ...overrideResponse})

export const getUpdateApiMediasIdAttributeResponseMock = (overrideResponse: Partial<Extract<UpdateApiMediasIdAttribute200, object>> = {}): UpdateApiMediasIdAttribute200 => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), attribute: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), value: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ...overrideResponse})

export const getCreateApiMediasIdFileResponseMock = (overrideResponse: Partial<Extract<CreateApiMediasIdFile200, object>> = {}): CreateApiMediasIdFile200 => ({id: faker.helpers.arrayElement([faker.number.int(), undefined]), attribute: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), view_url: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), thumb_url: faker.helpers.arrayElement([faker.string.alpha({length: {min: 10, max: 20}}), undefined]), ...overrideResponse})


export const getApiMediasMockHandler = (overrideResponse?: MediaList[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<MediaList[]> | MediaList[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/medias', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getApiMediasResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreateApiMediasMockHandler = (overrideResponse?: Media | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Media> | Media), options?: RequestHandlerOptions) => {
  return http.post('*/api/medias', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateApiMediasResponseMock(),
      { status: 201
      })
  }, options)
}

export const getApiMediasFoldersMockHandler = (overrideResponse?: string[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<string[]> | string[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/medias/folders', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getApiMediasFoldersResponseMock(),
      { status: 200
      })
  }, options)
}

export const getApiImageFilenameMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.get('*/api/image/:filename', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
  if (typeof overrideResponse === 'function') {await overrideResponse(info); }

    return new HttpResponse(null,
      { status: 200
      })
  }, options)
}

export const getDeleteApiMediasIdMockHandler = (overrideResponse?: DeletedResponse | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<DeletedResponse> | DeletedResponse), options?: RequestHandlerOptions) => {
  return http.delete('*/api/medias/:id', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getDeleteApiMediasIdResponseMock(),
      { status: 204
      })
  }, options)
}

export const getUpdateApiMediasIdAttributeMockHandler = (overrideResponse?: UpdateApiMediasIdAttribute200 | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<UpdateApiMediasIdAttribute200> | UpdateApiMediasIdAttribute200), options?: RequestHandlerOptions) => {
  return http.put('*/api/medias/:id/:attribute', async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getUpdateApiMediasIdAttributeResponseMock(),
      { status: 200
      })
  }, options)
}

export const getCreateApiMediasIdFileMockHandler = (overrideResponse?: CreateApiMediasIdFile200 | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<CreateApiMediasIdFile200> | CreateApiMediasIdFile200), options?: RequestHandlerOptions) => {
  return http.post('*/api/medias/:id/file', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {


    return HttpResponse.json(overrideResponse !== undefined
    ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
    : getCreateApiMediasIdFileResponseMock(),
      { status: 200
      })
  }, options)
}
export const getMediaMock = () => [
  getApiMediasMockHandler(),
  getCreateApiMediasMockHandler(),
  getApiMediasFoldersMockHandler(),
  getApiImageFilenameMockHandler(),
  getDeleteApiMediasIdMockHandler(),
  getUpdateApiMediasIdAttributeMockHandler(),
  getCreateApiMediasIdFileMockHandler()
]
