/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */

export type GetOrganizationsRoles200Item = {
    /** clé du rôle */
    key?: string;
    /** Nom du rôle */
    value?: string;
};
