/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */

export type PutOrganizationsByIdJoinLinkByRole200 = {
    /** identifiant de l'organisation modifiée */
    id?: number;
    /** attribut modifié */
    attribute?: string;
    /** nouvelle valeur affectée à l'attribut */
    value?: string;
};
