/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * API macarte
 * OpenAPI spec version: 1.0
 */

export type CreateApiOrganizationsIdMembersUserId200Item = {
  /** Identifiant public de l'organisation */
  organization_id?: string;
  /** Identifiant public de l'utilisateur */
  user_id?: string;
  /** Nom public de l'utilisateur */
  user_public_name?: string;
  /** Role de l'utilisateur dans l'organisation */
  user_role?: string;
  /** si false, l'opération a été effectuée, mais le mail d'information à l'utilisateur n'a pas été envoyé */
  email_sent?: boolean;
};
