/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * API macarte
 * OpenAPI spec version: 1.0
 */

export type GetApiOrganizationsRoles200Item = {
  /** clé du role */
  key?: string;
  /** Nom du role */
  value?: string;
};
