/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * API macarte
 * OpenAPI spec version: 1.0
 */

export type GetApiEditorialFollowers200 = {
  facebook?: string;
  twitter?: string;
  linkedin?: string;
  instagram?: string;
};
