/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * API macarte
 * OpenAPI spec version: 1.0
 */
import type { LimitParameter } from './limitParameter';

export type GetApiMapsUsersParams = {
/**
 * Thème des cartes (nom du thème ou 'Non défini')
 */
theme?: string;
/**
 * string que le public_name des utilisateurs doit inclure
 */
public_name?: string;
/**
 * Un ou plusieurs mots que doivent contenir le titre, la description ou le thème <br>
 *                     S'il y a plusieurs mots, la recherche l'interprètera comme un ET
 */
query?: string;
/**
 * Nombre maximum d'objets à retourner
 */
limit?: LimitParameter;
};
