/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * API macarte
 * OpenAPI spec version: 1.0
 */
import type { LimitParameter } from './limitParameter';
import type { OffsetParameter } from './offsetParameter';

export type GetApiMediasParams = {
/**
 * Name contient cette valeur
 */
name?: string;
/**
 * Identifiant du média recherché
 */
id?: number;
/**
 * Identifiant public de l'organisation, renvoie la liste de ses médias
 */
organization_id?: number;
/**
 * Si 'true', limite la recherche aux médias invalidés par les administrateurs
 */
valid?: boolean;
/**
 * tri des medias, parmi ['size', 'date']
 */
sort?: boolean;
/**
 * Le nombre d'objets à ignorer avant de commencer à collecter l'ensemble de résultats
 */
offset?: OffsetParameter;
/**
 * Nombre maximum d'objets à retourner
 */
limit?: LimitParameter;
};
