/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * API macarte
 * OpenAPI spec version: 1.0
 */

export type GetApiEditorialCategories200Item = {
  /** clé de la catégorie */
  key?: string;
  /** Nomde la catégorie */
  value?: string;
};
