/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */

export type GetOrganizationsMe200Item = {
  /** identifiant de l'organisation */
  public_id?: string;
  /** Nom de l'organisation */
  name?: string;
  /** Logo de l'organisation */
  profile_picture?: string;
  /** Image de couverture */
  cover_picture?: string;
  /** Role de l'utilisateur dans l'organisation */
  user_role?: string;
  /** l'utilisateur est actif dans l'organisation */
  active?: boolean;
};
