/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * API macarte
 * OpenAPI spec version: 1.0
 */

export type MapResearchUsersItem = {
  /** Nom public de l'utilisateur */
  user?: string;
  /** Nombre de cartes */
  count?: number;
};
