/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */
import type { Media } from './media';

/**
 * Liste de médias
 */
export interface MediaList {
  medias?: Media[];
  /** Nombre de cartes correspondant à la recherche */
  count?: number;
  /** Nombre de cartes recues dans la requete */
  limit?: number;
  /** Nombre de cartes à passer avant de ls inclure dans la requete */
  offset?: number;
}
