/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * API macarte
 * OpenAPI spec version: 1.0
 */
import type { MapAdd } from './mapAdd';

export type PatchApiMapsEditIdBody = MapAdd & {
  /** Demande à modifier l'id de modification */
  new_edit_id?: boolean;
};
