/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * API macarte
 * OpenAPI spec version: 1.0
 */

export type PostApiMediasIdFileBody = {
  /** image à associer à la bibliothèque, le fichier doit faire moins de 2 Mo */
  file: Blob;
};
