/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * API macarte
 * OpenAPI spec version: 1.0
 */

export type PutApiOrganizationsIdJoinLinkRole200 = {
  /** identifiant de l'organisation modifiée */
  id?: number;
  /** attribut modifié */
  attribute?: string;
  /** nouvelle valeur affectée à l'attribut */
  value?: string;
};
