/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * API macarte
 * OpenAPI spec version: 1.0
 */

export type PutApiOrganizationsIdJoinLinkRoleBody = {
  /** true : crée le lien, false : supprime le lien */
  value?: boolean;
};
