/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */

/**
 * Theme
 */
export interface Theme {
    /** Id du thème */
    id?: number;
    /** Nom complet du thème */
    name?: string;
}
