/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * API macarte
 * OpenAPI spec version: 1.0
 */

export type UpdateApiMediasIdAttributeBody = {
  /** valeur à affecter à l'attribut [folder => peut être null] */
  value?: string;
};
