/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */

export type UpdateOrganizationsByIdMembersByUseridRole200 = {
  /** Identifiant public de l'organisation */
  organization_id?: string;
  /** Identifiant public de l'utilisateur */
  user_id?: string;
  /** Nom public de l'utilisateur */
  user_public_name?: string;
  /** Role de l'utilisateur dans l'organisation */
  user_role?: string;
  /** false si le mail d'information n'a pas pu être envoyé */
  mail_sent?: boolean;
};
