/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * API macarte
 * OpenAPI spec version: 1.0
 */

export type UpdateApiOrganizationsIdMembersUserIdRoleBody = {
  /** role de l'utilisateur, required, parmi ['member', 'editor', 'owner'] */
  value?: string;
};
