/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */
import type { UserEdit } from './userEdit';

export type UserMeEdit = UserEdit & {
  current_password?: string;
  new_password?: string;
};
