/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */
import type { UserEdit } from './userEdit';

export type UserView = UserEdit & {
  /** Compte bloqué */
  locked?: boolean;
  id?: number;
  /** Taille globale limite des images uploadées (en octet) */
  medias_limit_size?: number;
  /** Taille globale des images uploadées (en octet) */
  medias_size?: number;
  roles?: string[];
};
