/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */
import { faker } from "@faker-js/faker";

import type {
    AddMemberToOrganization200,
    DeletedResponse,
    GetOrganizationLinksById200,
    GetOrganizationsMe200Item,
    GetOrganizationsRoles200Item,
    Organization,
    PutOrganizationAttribute200,
    PutOrganizationJoinLinkRole200,
    PutOrganizationMemberRole200,
} from "../model";

export const getGetOrganizationsRolesResponseMock = (): GetOrganizationsRoles200Item[] =>
    Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
        key: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
        value: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    }));

export const getGetOrganizationsMeResponseMock = (): GetOrganizationsMe200Item[] =>
    Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
        public_id: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
        name: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
        profile_picture: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
        cover_picture: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
        user_role: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
        active: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
    }));

export const getGetOrganizationsByIdActivateResponseMock = (overrideResponse: Partial<Extract<Organization, object>> = {}): Organization => ({
    public_id: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    name: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    presentation: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]), undefined]),
    profile_picture: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.internet.url(), null]), undefined]),
    cover_picture: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.internet.url(), null]), undefined]),
    created_at: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + "Z", undefined]),
    updated_at: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + "Z", undefined]),
    premium: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]), undefined]),
    nb_members: faker.helpers.arrayElement([faker.number.int(), undefined]),
    nb_shared_maps: faker.helpers.arrayElement([faker.number.int(), undefined]),
    nb_views: faker.helpers.arrayElement([faker.number.int(), undefined]),
    locked: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
    media_size_limit: faker.helpers.arrayElement([faker.number.int(), undefined]),
    medias_size: faker.helpers.arrayElement([faker.number.int(), undefined]),
    members: faker.helpers.arrayElement([
        Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
            public_name: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
            public_id: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
            registered_at: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + "Z", undefined]),
            role: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
            promoted_at: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + "Z", undefined]),
            active: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
            profile_picture: faker.helpers.arrayElement([faker.internet.url(), undefined]),
        })),
        undefined,
    ]),
    ...overrideResponse,
});

export const getGetOrganizationsByIdResponseMock = (overrideResponse: Partial<Extract<Organization, object>> = {}): Organization => ({
    public_id: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    name: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    presentation: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]), undefined]),
    profile_picture: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.internet.url(), null]), undefined]),
    cover_picture: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.internet.url(), null]), undefined]),
    created_at: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + "Z", undefined]),
    updated_at: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + "Z", undefined]),
    premium: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]), undefined]),
    nb_members: faker.helpers.arrayElement([faker.number.int(), undefined]),
    nb_shared_maps: faker.helpers.arrayElement([faker.number.int(), undefined]),
    nb_views: faker.helpers.arrayElement([faker.number.int(), undefined]),
    locked: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
    media_size_limit: faker.helpers.arrayElement([faker.number.int(), undefined]),
    medias_size: faker.helpers.arrayElement([faker.number.int(), undefined]),
    members: faker.helpers.arrayElement([
        Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
            public_name: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
            public_id: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
            registered_at: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + "Z", undefined]),
            role: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
            promoted_at: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + "Z", undefined]),
            active: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
            profile_picture: faker.helpers.arrayElement([faker.internet.url(), undefined]),
        })),
        undefined,
    ]),
    ...overrideResponse,
});

export const getDeleteOrganizationResponseMock = (overrideResponse: Partial<Extract<DeletedResponse, object>> = {}): DeletedResponse => ({
    code: faker.helpers.arrayElement([faker.number.int(), undefined]),
    message: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    ...overrideResponse,
});

export const getPostOrganizationResponseMock = (overrideResponse: Partial<Extract<Organization, object>> = {}): Organization => ({
    public_id: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    name: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    presentation: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]), undefined]),
    profile_picture: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.internet.url(), null]), undefined]),
    cover_picture: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.internet.url(), null]), undefined]),
    created_at: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + "Z", undefined]),
    updated_at: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + "Z", undefined]),
    premium: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]), undefined]),
    nb_members: faker.helpers.arrayElement([faker.number.int(), undefined]),
    nb_shared_maps: faker.helpers.arrayElement([faker.number.int(), undefined]),
    nb_views: faker.helpers.arrayElement([faker.number.int(), undefined]),
    locked: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
    media_size_limit: faker.helpers.arrayElement([faker.number.int(), undefined]),
    medias_size: faker.helpers.arrayElement([faker.number.int(), undefined]),
    members: faker.helpers.arrayElement([
        Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
            public_name: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
            public_id: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
            registered_at: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + "Z", undefined]),
            role: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
            promoted_at: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + "Z", undefined]),
            active: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
            profile_picture: faker.helpers.arrayElement([faker.internet.url(), undefined]),
        })),
        undefined,
    ]),
    ...overrideResponse,
});

export const getPutOrganizationAttributeResponseMock = (
    overrideResponse: Partial<Extract<PutOrganizationAttribute200, object>> = {}
): PutOrganizationAttribute200 => ({
    id: faker.helpers.arrayElement([faker.number.int(), undefined]),
    attribute: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    value: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    ...overrideResponse,
});

export const getPutOrganizationJoinLinkRoleResponseMock = (
    overrideResponse: Partial<Extract<PutOrganizationJoinLinkRole200, object>> = {}
): PutOrganizationJoinLinkRole200 => ({
    id: faker.helpers.arrayElement([faker.number.int(), undefined]),
    attribute: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    value: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    ...overrideResponse,
});

export const getJoinOrganizationByIdResponseMock = (overrideResponse: Partial<Extract<Organization, object>> = {}): Organization => ({
    public_id: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    name: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    presentation: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]), undefined]),
    profile_picture: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.internet.url(), null]), undefined]),
    cover_picture: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.internet.url(), null]), undefined]),
    created_at: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + "Z", undefined]),
    updated_at: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + "Z", undefined]),
    premium: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]), undefined]),
    nb_members: faker.helpers.arrayElement([faker.number.int(), undefined]),
    nb_shared_maps: faker.helpers.arrayElement([faker.number.int(), undefined]),
    nb_views: faker.helpers.arrayElement([faker.number.int(), undefined]),
    locked: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
    media_size_limit: faker.helpers.arrayElement([faker.number.int(), undefined]),
    medias_size: faker.helpers.arrayElement([faker.number.int(), undefined]),
    members: faker.helpers.arrayElement([
        Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
            public_name: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
            public_id: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
            registered_at: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + "Z", undefined]),
            role: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
            promoted_at: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 19) + "Z", undefined]),
            active: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
            profile_picture: faker.helpers.arrayElement([faker.internet.url(), undefined]),
        })),
        undefined,
    ]),
    ...overrideResponse,
});

export const getGetOrganizationLinksByIdResponseMock = (
    overrideResponse: Partial<Extract<GetOrganizationLinksById200, object>> = {}
): GetOrganizationLinksById200 => ({
    link_as_member: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]), undefined]),
    link_as_editor: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]), undefined]),
    mail_pattern: faker.helpers.arrayElement([faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), null]), undefined]),
    ...overrideResponse,
});

export const getAddMemberToOrganizationResponseMock = (
    overrideResponse: Partial<Extract<AddMemberToOrganization200, object>> = {}
): AddMemberToOrganization200 => ({
    organization_id: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    user_id: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    user_public_name: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    user_role: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    mail_sent: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
    ...overrideResponse,
});

export const getDeleteOrganizationMemberResponseMock = (overrideResponse: Partial<Extract<DeletedResponse, object>> = {}): DeletedResponse => ({
    code: faker.helpers.arrayElement([faker.number.int(), undefined]),
    message: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    ...overrideResponse,
});

export const getPutOrganizationMemberRoleResponseMock = (
    overrideResponse: Partial<Extract<PutOrganizationMemberRole200, object>> = {}
): PutOrganizationMemberRole200 => ({
    organization_id: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    user_id: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    user_public_name: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    user_role: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    mail_sent: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
    ...overrideResponse,
});
