/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */
import { HttpResponse, http } from "msw";
import type { RequestHandlerOptions } from "msw";

import type {
    AddMemberToOrganization200,
    DeletedResponse,
    GetOrganizationLinksById200,
    GetOrganizationsMe200Item,
    GetOrganizationsRoles200Item,
    Organization,
    PutOrganizationAttribute200,
    PutOrganizationJoinLinkRole200,
    PutOrganizationMemberRole200,
} from "../model";

import {
    getAddMemberToOrganizationResponseMock,
    getDeleteOrganizationMemberResponseMock,
    getDeleteOrganizationResponseMock,
    getGetOrganizationLinksByIdResponseMock,
    getGetOrganizationsByIdActivateResponseMock,
    getGetOrganizationsByIdResponseMock,
    getGetOrganizationsMeResponseMock,
    getGetOrganizationsRolesResponseMock,
    getJoinOrganizationByIdResponseMock,
    getPostOrganizationResponseMock,
    getPutOrganizationAttributeResponseMock,
    getPutOrganizationJoinLinkRoleResponseMock,
    getPutOrganizationMemberRoleResponseMock,
} from "./organization.faker";

export {
    getGetOrganizationsRolesResponseMock,
    getGetOrganizationsMeResponseMock,
    getGetOrganizationsByIdActivateResponseMock,
    getGetOrganizationsByIdResponseMock,
    getDeleteOrganizationResponseMock,
    getPostOrganizationResponseMock,
    getPutOrganizationAttributeResponseMock,
    getPutOrganizationJoinLinkRoleResponseMock,
    getJoinOrganizationByIdResponseMock,
    getGetOrganizationLinksByIdResponseMock,
    getAddMemberToOrganizationResponseMock,
    getDeleteOrganizationMemberResponseMock,
    getPutOrganizationMemberRoleResponseMock,
} from "./organization.faker";

export const getGetOrganizationsRolesMockHandler = (
    overrideResponse?:
        | GetOrganizationsRoles200Item[]
        | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetOrganizationsRoles200Item[]> | GetOrganizationsRoles200Item[]),
    options?: RequestHandlerOptions
) => {
    return http.get(
        "*/api/organizations/roles",
        async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
            return HttpResponse.json(
                overrideResponse !== undefined
                    ? typeof overrideResponse === "function"
                        ? await overrideResponse(info)
                        : overrideResponse
                    : getGetOrganizationsRolesResponseMock(),
                { status: 200 }
            );
        },
        options
    );
};

export const getGetOrganizationsMeMockHandler = (
    overrideResponse?:
        | GetOrganizationsMe200Item[]
        | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetOrganizationsMe200Item[]> | GetOrganizationsMe200Item[]),
    options?: RequestHandlerOptions
) => {
    return http.get(
        "*/api/organizations/me",
        async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
            return HttpResponse.json(
                overrideResponse !== undefined
                    ? typeof overrideResponse === "function"
                        ? await overrideResponse(info)
                        : overrideResponse
                    : getGetOrganizationsMeResponseMock(),
                { status: 200 }
            );
        },
        options
    );
};

export const getGetOrganizationsByIdActivateMockHandler = (
    overrideResponse?: Organization | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Organization> | Organization),
    options?: RequestHandlerOptions
) => {
    return http.get(
        "*/api/organizations/:id/activate",
        async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
            return HttpResponse.json(
                overrideResponse !== undefined
                    ? typeof overrideResponse === "function"
                        ? await overrideResponse(info)
                        : overrideResponse
                    : getGetOrganizationsByIdActivateResponseMock(),
                { status: 200 }
            );
        },
        options
    );
};

export const getGetOrganizationsByIdMockHandler = (
    overrideResponse?: Organization | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Organization> | Organization),
    options?: RequestHandlerOptions
) => {
    return http.get(
        "*/api/organizations/:id",
        async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
            return HttpResponse.json(
                overrideResponse !== undefined
                    ? typeof overrideResponse === "function"
                        ? await overrideResponse(info)
                        : overrideResponse
                    : getGetOrganizationsByIdResponseMock(),
                { status: 200 }
            );
        },
        options
    );
};

export const getDeleteOrganizationMockHandler = (
    overrideResponse?: DeletedResponse | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<DeletedResponse> | DeletedResponse),
    options?: RequestHandlerOptions
) => {
    return http.delete(
        "*/api/organizations/:id",
        async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
            return HttpResponse.json(
                overrideResponse !== undefined
                    ? typeof overrideResponse === "function"
                        ? await overrideResponse(info)
                        : overrideResponse
                    : getDeleteOrganizationResponseMock(),
                { status: 204 }
            );
        },
        options
    );
};

export const getPostOrganizationMockHandler = (
    overrideResponse?: Organization | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Organization> | Organization),
    options?: RequestHandlerOptions
) => {
    return http.post(
        "*/api/organizations",
        async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
            return HttpResponse.json(
                overrideResponse !== undefined
                    ? typeof overrideResponse === "function"
                        ? await overrideResponse(info)
                        : overrideResponse
                    : getPostOrganizationResponseMock(),
                { status: 201 }
            );
        },
        options
    );
};

export const getPutOrganizationAttributeMockHandler = (
    overrideResponse?:
        | PutOrganizationAttribute200
        | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<PutOrganizationAttribute200> | PutOrganizationAttribute200),
    options?: RequestHandlerOptions
) => {
    return http.put(
        "*/api/organizations/:id/:attribute",
        async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {
            return HttpResponse.json(
                overrideResponse !== undefined
                    ? typeof overrideResponse === "function"
                        ? await overrideResponse(info)
                        : overrideResponse
                    : getPutOrganizationAttributeResponseMock(),
                { status: 200 }
            );
        },
        options
    );
};

export const getPutOrganizationJoinLinkRoleMockHandler = (
    overrideResponse?:
        | PutOrganizationJoinLinkRole200
        | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<PutOrganizationJoinLinkRole200> | PutOrganizationJoinLinkRole200),
    options?: RequestHandlerOptions
) => {
    return http.put(
        "*/api/organizations/:id/join-link/:role",
        async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {
            return HttpResponse.json(
                overrideResponse !== undefined
                    ? typeof overrideResponse === "function"
                        ? await overrideResponse(info)
                        : overrideResponse
                    : getPutOrganizationJoinLinkRoleResponseMock(),
                { status: 200 }
            );
        },
        options
    );
};

export const getJoinOrganizationByIdMockHandler = (
    overrideResponse?: Organization | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Organization> | Organization),
    options?: RequestHandlerOptions
) => {
    return http.get(
        "*/api/organizations/join/:id",
        async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
            return HttpResponse.json(
                overrideResponse !== undefined
                    ? typeof overrideResponse === "function"
                        ? await overrideResponse(info)
                        : overrideResponse
                    : getJoinOrganizationByIdResponseMock(),
                { status: 200 }
            );
        },
        options
    );
};

export const getGetOrganizationLinksByIdMockHandler = (
    overrideResponse?:
        | GetOrganizationLinksById200
        | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetOrganizationLinksById200> | GetOrganizationLinksById200),
    options?: RequestHandlerOptions
) => {
    return http.get(
        "*/api/organizations/links/:id",
        async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
            return HttpResponse.json(
                overrideResponse !== undefined
                    ? typeof overrideResponse === "function"
                        ? await overrideResponse(info)
                        : overrideResponse
                    : getGetOrganizationLinksByIdResponseMock(),
                { status: 200 }
            );
        },
        options
    );
};

export const getAddMemberToOrganizationMockHandler = (
    overrideResponse?:
        | AddMemberToOrganization200
        | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<AddMemberToOrganization200> | AddMemberToOrganization200),
    options?: RequestHandlerOptions
) => {
    return http.post(
        "*/api/organizations/:id/members/:userId",
        async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
            return HttpResponse.json(
                overrideResponse !== undefined
                    ? typeof overrideResponse === "function"
                        ? await overrideResponse(info)
                        : overrideResponse
                    : getAddMemberToOrganizationResponseMock(),
                { status: 200 }
            );
        },
        options
    );
};

export const getDeleteOrganizationMemberMockHandler = (
    overrideResponse?: DeletedResponse | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<DeletedResponse> | DeletedResponse),
    options?: RequestHandlerOptions
) => {
    return http.delete(
        "*/api/organizations/:id/members/:userId",
        async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
            return HttpResponse.json(
                overrideResponse !== undefined
                    ? typeof overrideResponse === "function"
                        ? await overrideResponse(info)
                        : overrideResponse
                    : getDeleteOrganizationMemberResponseMock(),
                { status: 204 }
            );
        },
        options
    );
};

export const getPutOrganizationMemberRoleMockHandler = (
    overrideResponse?:
        | PutOrganizationMemberRole200
        | ((info: Parameters<Parameters<typeof http.put>[1]>[0]) => Promise<PutOrganizationMemberRole200> | PutOrganizationMemberRole200),
    options?: RequestHandlerOptions
) => {
    return http.put(
        "*/api/organizations/:id/members/:userId/role",
        async (info: Parameters<Parameters<typeof http.put>[1]>[0]) => {
            return HttpResponse.json(
                overrideResponse !== undefined
                    ? typeof overrideResponse === "function"
                        ? await overrideResponse(info)
                        : overrideResponse
                    : getPutOrganizationMemberRoleResponseMock(),
                { status: 200 }
            );
        },
        options
    );
};
export const getOrganizationMock = () => [
    getGetOrganizationsRolesMockHandler(),
    getGetOrganizationsMeMockHandler(),
    getGetOrganizationsByIdActivateMockHandler(),
    getGetOrganizationsByIdMockHandler(),
    getDeleteOrganizationMockHandler(),
    getPostOrganizationMockHandler(),
    getPutOrganizationAttributeMockHandler(),
    getPutOrganizationJoinLinkRoleMockHandler(),
    getJoinOrganizationByIdMockHandler(),
    getGetOrganizationLinksByIdMockHandler(),
    getAddMemberToOrganizationMockHandler(),
    getDeleteOrganizationMemberMockHandler(),
    getPutOrganizationMemberRoleMockHandler(),
];
