/**
 * Generated by orval 🍺
 * Do not edit manually.
 * MaCarte API
 * Documentation OpenAPI de l'API MaCarte
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query";

import { apiURL } from "../../env";

import type {
    AddMemberToOrganization200,
    AddMemberToOrganizationBody,
    BadRequestResponse,
    DeletedResponse,
    ForbiddenResponse,
    GetOrganizationLinksById200,
    GetOrganizationsMe200Item,
    GetOrganizationsRoles200Item,
    NotConnectedResponse,
    NotFoundResponse,
    Organization,
    PostOrganizationBody,
    PutOrganizationAttribute200,
    PutOrganizationAttributeBody,
    PutOrganizationJoinLinkRole200,
    PutOrganizationJoinLinkRoleBody,
    PutOrganizationMemberRole200,
    PutOrganizationMemberRoleBody,
} from "../model";

import { fetchWithAuth } from ".././fetchWithAuth";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
    const result = { queryKey } as T & { queryKey: K };
    for (const key of Object.keys(query)) {
        // The explicit queryKey always wins, matching the previous
        // `{ ...query, queryKey }` spread where it was set last.
        if (key === "queryKey") continue;
        Object.defineProperty(result, key, {
            enumerable: true,
            configurable: true,
            get: () => (query as Record<string, unknown>)[key],
        });
    }
    return result;
};

export type getOrganizationsRolesResponse200 = {
    data: GetOrganizationsRoles200Item[];
    status: 200;
};

export type getOrganizationsRolesResponseSuccess = getOrganizationsRolesResponse200 & {
    headers: Headers;
};
export type getOrganizationsRolesResponse = getOrganizationsRolesResponseSuccess;

export const getGetOrganizationsRolesUrl = () => {
    return `${apiURL}/api/organizations/roles`;
};

export const getOrganizationsRoles = async (options?: Parameters<typeof fetchWithAuth>[1]): Promise<getOrganizationsRolesResponse> => {
    return fetchWithAuth<getOrganizationsRolesResponse>(getGetOrganizationsRolesUrl(), {
        ...options,
        method: "GET",
    });
};

export const getGetOrganizationsRolesQueryKey = () => {
    return [`${apiURL}/api/organizations/roles`] as const;
};

export const getGetOrganizationsRolesQueryOptions = <TData = Awaited<ReturnType<typeof getOrganizationsRoles>>, TError = unknown>(options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsRoles>>, TError, TData>>;
    request?: SecondParameter<typeof fetchWithAuth>;
}) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetOrganizationsRolesQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrganizationsRoles>>> = ({ signal }) => getOrganizationsRoles({ signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsRoles>>, TError, TData> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };
};

export type GetOrganizationsRolesQueryResult = NonNullable<Awaited<ReturnType<typeof getOrganizationsRoles>>>;
export type GetOrganizationsRolesQueryError = unknown;

export function useGetOrganizationsRoles<TData = Awaited<ReturnType<typeof getOrganizationsRoles>>, TError = unknown>(
    options: {
        query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsRoles>>, TError, TData>> &
            Pick<
                DefinedInitialDataOptions<Awaited<ReturnType<typeof getOrganizationsRoles>>, TError, Awaited<ReturnType<typeof getOrganizationsRoles>>>,
                "initialData"
            >;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetOrganizationsRoles<TData = Awaited<ReturnType<typeof getOrganizationsRoles>>, TError = unknown>(
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsRoles>>, TError, TData>> &
            Pick<
                UndefinedInitialDataOptions<Awaited<ReturnType<typeof getOrganizationsRoles>>, TError, Awaited<ReturnType<typeof getOrganizationsRoles>>>,
                "initialData"
            >;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetOrganizationsRoles<TData = Awaited<ReturnType<typeof getOrganizationsRoles>>, TError = unknown>(
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsRoles>>, TError, TData>>;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetOrganizationsRoles<TData = Awaited<ReturnType<typeof getOrganizationsRoles>>, TError = unknown>(
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsRoles>>, TError, TData>>;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const queryOptions = getGetOrganizationsRolesQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

    return withQueryKey(query, queryOptions.queryKey);
}

export const prefetchGetOrganizationsRolesQuery = async <TData = Awaited<ReturnType<typeof getOrganizationsRoles>>, TError = unknown>(
    queryClient: QueryClient,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsRoles>>, TError, TData>>;
        request?: SecondParameter<typeof fetchWithAuth>;
    }
): Promise<QueryClient> => {
    const queryOptions = getGetOrganizationsRolesQueryOptions(options);

    await queryClient.prefetchQuery(queryOptions);

    return queryClient;
};

export type getOrganizationsMeResponse200 = {
    data: GetOrganizationsMe200Item[];
    status: 200;
};

export type getOrganizationsMeResponse401 = {
    data: NotConnectedResponse;
    status: 401;
};

export type getOrganizationsMeResponseSuccess = getOrganizationsMeResponse200 & {
    headers: Headers;
};
export type getOrganizationsMeResponseError = getOrganizationsMeResponse401 & {
    headers: Headers;
};

export type getOrganizationsMeResponse = getOrganizationsMeResponseSuccess | getOrganizationsMeResponseError;

export const getGetOrganizationsMeUrl = () => {
    return `${apiURL}/api/organizations/me`;
};

export const getOrganizationsMe = async (options?: Parameters<typeof fetchWithAuth>[1]): Promise<getOrganizationsMeResponse> => {
    return fetchWithAuth<getOrganizationsMeResponse>(getGetOrganizationsMeUrl(), {
        ...options,
        method: "GET",
    });
};

export const getGetOrganizationsMeQueryKey = () => {
    return [`${apiURL}/api/organizations/me`] as const;
};

export const getGetOrganizationsMeQueryOptions = <TData = Awaited<ReturnType<typeof getOrganizationsMe>>, TError = NotConnectedResponse>(options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsMe>>, TError, TData>>;
    request?: SecondParameter<typeof fetchWithAuth>;
}) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetOrganizationsMeQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrganizationsMe>>> = ({ signal }) => getOrganizationsMe({ signal, ...requestOptions });

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsMe>>, TError, TData> & {
        queryKey: DataTag<QueryKey, TData, TError>;
    };
};

export type GetOrganizationsMeQueryResult = NonNullable<Awaited<ReturnType<typeof getOrganizationsMe>>>;
export type GetOrganizationsMeQueryError = NotConnectedResponse;

export function useGetOrganizationsMe<TData = Awaited<ReturnType<typeof getOrganizationsMe>>, TError = NotConnectedResponse>(
    options: {
        query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsMe>>, TError, TData>> &
            Pick<
                DefinedInitialDataOptions<Awaited<ReturnType<typeof getOrganizationsMe>>, TError, Awaited<ReturnType<typeof getOrganizationsMe>>>,
                "initialData"
            >;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetOrganizationsMe<TData = Awaited<ReturnType<typeof getOrganizationsMe>>, TError = NotConnectedResponse>(
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsMe>>, TError, TData>> &
            Pick<
                UndefinedInitialDataOptions<Awaited<ReturnType<typeof getOrganizationsMe>>, TError, Awaited<ReturnType<typeof getOrganizationsMe>>>,
                "initialData"
            >;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetOrganizationsMe<TData = Awaited<ReturnType<typeof getOrganizationsMe>>, TError = NotConnectedResponse>(
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsMe>>, TError, TData>>;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetOrganizationsMe<TData = Awaited<ReturnType<typeof getOrganizationsMe>>, TError = NotConnectedResponse>(
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsMe>>, TError, TData>>;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const queryOptions = getGetOrganizationsMeQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

    return withQueryKey(query, queryOptions.queryKey);
}

export const prefetchGetOrganizationsMeQuery = async <TData = Awaited<ReturnType<typeof getOrganizationsMe>>, TError = NotConnectedResponse>(
    queryClient: QueryClient,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsMe>>, TError, TData>>;
        request?: SecondParameter<typeof fetchWithAuth>;
    }
): Promise<QueryClient> => {
    const queryOptions = getGetOrganizationsMeQueryOptions(options);

    await queryClient.prefetchQuery(queryOptions);

    return queryClient;
};

export type getOrganizationsByIdActivateResponse200 = {
    data: Organization;
    status: 200;
};

export type getOrganizationsByIdActivateResponse400 = {
    data: BadRequestResponse;
    status: 400;
};

export type getOrganizationsByIdActivateResponse401 = {
    data: NotConnectedResponse;
    status: 401;
};

export type getOrganizationsByIdActivateResponseSuccess = getOrganizationsByIdActivateResponse200 & {
    headers: Headers;
};
export type getOrganizationsByIdActivateResponseError = (getOrganizationsByIdActivateResponse400 | getOrganizationsByIdActivateResponse401) & {
    headers: Headers;
};

export type getOrganizationsByIdActivateResponse = getOrganizationsByIdActivateResponseSuccess | getOrganizationsByIdActivateResponseError;

export const getGetOrganizationsByIdActivateUrl = (id: number | string) => {
    return `${apiURL}/api/organizations/${id}/activate`;
};

/**
 * Active l'utilisateur invité dans l'organisation
 */
export const getOrganizationsByIdActivate = async (
    id: number | string,
    options?: Parameters<typeof fetchWithAuth>[1]
): Promise<getOrganizationsByIdActivateResponse> => {
    return fetchWithAuth<getOrganizationsByIdActivateResponse>(getGetOrganizationsByIdActivateUrl(id), {
        ...options,
        method: "GET",
    });
};

export const getGetOrganizationsByIdActivateQueryKey = (id: number | string) => {
    return [`${apiURL}/api/organizations/${id}/activate`] as const;
};

export const getGetOrganizationsByIdActivateQueryOptions = <
    TData = Awaited<ReturnType<typeof getOrganizationsByIdActivate>>,
    TError = BadRequestResponse | NotConnectedResponse,
>(
    id: number | string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsByIdActivate>>, TError, TData>>;
        request?: SecondParameter<typeof fetchWithAuth>;
    }
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetOrganizationsByIdActivateQueryKey(id);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrganizationsByIdActivate>>> = ({ signal }) =>
        getOrganizationsByIdActivate(id, { signal, ...requestOptions });

    return { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getOrganizationsByIdActivate>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetOrganizationsByIdActivateQueryResult = NonNullable<Awaited<ReturnType<typeof getOrganizationsByIdActivate>>>;
export type GetOrganizationsByIdActivateQueryError = BadRequestResponse | NotConnectedResponse;

export function useGetOrganizationsByIdActivate<
    TData = Awaited<ReturnType<typeof getOrganizationsByIdActivate>>,
    TError = BadRequestResponse | NotConnectedResponse,
>(
    id: number | string,
    options: {
        query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsByIdActivate>>, TError, TData>> &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getOrganizationsByIdActivate>>,
                    TError,
                    Awaited<ReturnType<typeof getOrganizationsByIdActivate>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetOrganizationsByIdActivate<
    TData = Awaited<ReturnType<typeof getOrganizationsByIdActivate>>,
    TError = BadRequestResponse | NotConnectedResponse,
>(
    id: number | string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsByIdActivate>>, TError, TData>> &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getOrganizationsByIdActivate>>,
                    TError,
                    Awaited<ReturnType<typeof getOrganizationsByIdActivate>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetOrganizationsByIdActivate<
    TData = Awaited<ReturnType<typeof getOrganizationsByIdActivate>>,
    TError = BadRequestResponse | NotConnectedResponse,
>(
    id: number | string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsByIdActivate>>, TError, TData>>;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetOrganizationsByIdActivate<
    TData = Awaited<ReturnType<typeof getOrganizationsByIdActivate>>,
    TError = BadRequestResponse | NotConnectedResponse,
>(
    id: number | string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsByIdActivate>>, TError, TData>>;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const queryOptions = getGetOrganizationsByIdActivateQueryOptions(id, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

    return withQueryKey(query, queryOptions.queryKey);
}

export const prefetchGetOrganizationsByIdActivateQuery = async <
    TData = Awaited<ReturnType<typeof getOrganizationsByIdActivate>>,
    TError = BadRequestResponse | NotConnectedResponse,
>(
    queryClient: QueryClient,
    id: number | string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsByIdActivate>>, TError, TData>>;
        request?: SecondParameter<typeof fetchWithAuth>;
    }
): Promise<QueryClient> => {
    const queryOptions = getGetOrganizationsByIdActivateQueryOptions(id, options);

    await queryClient.prefetchQuery(queryOptions);

    return queryClient;
};

export type getOrganizationsByIdResponse200 = {
    data: Organization;
    status: 200;
};

export type getOrganizationsByIdResponse404 = {
    data: NotFoundResponse;
    status: 404;
};

export type getOrganizationsByIdResponseSuccess = getOrganizationsByIdResponse200 & {
    headers: Headers;
};
export type getOrganizationsByIdResponseError = getOrganizationsByIdResponse404 & {
    headers: Headers;
};

export type getOrganizationsByIdResponse = getOrganizationsByIdResponseSuccess | getOrganizationsByIdResponseError;

export const getGetOrganizationsByIdUrl = (id: number | string) => {
    return `${apiURL}/api/organizations/${id}`;
};

/**
 * Récupérer les données de l'organisation. NB : si pas membre, seul un décompte des membres est fourni.
 */
export const getOrganizationsById = async (id: number | string, options?: Parameters<typeof fetchWithAuth>[1]): Promise<getOrganizationsByIdResponse> => {
    return fetchWithAuth<getOrganizationsByIdResponse>(getGetOrganizationsByIdUrl(id), {
        ...options,
        method: "GET",
    });
};

export const getGetOrganizationsByIdQueryKey = (id: number | string) => {
    return [`${apiURL}/api/organizations/${id}`] as const;
};

export const getGetOrganizationsByIdQueryOptions = <TData = Awaited<ReturnType<typeof getOrganizationsById>>, TError = NotFoundResponse>(
    id: number | string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsById>>, TError, TData>>;
        request?: SecondParameter<typeof fetchWithAuth>;
    }
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetOrganizationsByIdQueryKey(id);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrganizationsById>>> = ({ signal }) => getOrganizationsById(id, { signal, ...requestOptions });

    return { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getOrganizationsById>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetOrganizationsByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getOrganizationsById>>>;
export type GetOrganizationsByIdQueryError = NotFoundResponse;

export function useGetOrganizationsById<TData = Awaited<ReturnType<typeof getOrganizationsById>>, TError = NotFoundResponse>(
    id: number | string,
    options: {
        query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsById>>, TError, TData>> &
            Pick<
                DefinedInitialDataOptions<Awaited<ReturnType<typeof getOrganizationsById>>, TError, Awaited<ReturnType<typeof getOrganizationsById>>>,
                "initialData"
            >;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetOrganizationsById<TData = Awaited<ReturnType<typeof getOrganizationsById>>, TError = NotFoundResponse>(
    id: number | string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsById>>, TError, TData>> &
            Pick<
                UndefinedInitialDataOptions<Awaited<ReturnType<typeof getOrganizationsById>>, TError, Awaited<ReturnType<typeof getOrganizationsById>>>,
                "initialData"
            >;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetOrganizationsById<TData = Awaited<ReturnType<typeof getOrganizationsById>>, TError = NotFoundResponse>(
    id: number | string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsById>>, TError, TData>>;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetOrganizationsById<TData = Awaited<ReturnType<typeof getOrganizationsById>>, TError = NotFoundResponse>(
    id: number | string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsById>>, TError, TData>>;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const queryOptions = getGetOrganizationsByIdQueryOptions(id, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

    return withQueryKey(query, queryOptions.queryKey);
}

export const prefetchGetOrganizationsByIdQuery = async <TData = Awaited<ReturnType<typeof getOrganizationsById>>, TError = NotFoundResponse>(
    queryClient: QueryClient,
    id: number | string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationsById>>, TError, TData>>;
        request?: SecondParameter<typeof fetchWithAuth>;
    }
): Promise<QueryClient> => {
    const queryOptions = getGetOrganizationsByIdQueryOptions(id, options);

    await queryClient.prefetchQuery(queryOptions);

    return queryClient;
};

export type deleteOrganizationResponse204 = {
    data: DeletedResponse;
    status: 204;
};

export type deleteOrganizationResponse401 = {
    data: NotConnectedResponse;
    status: 401;
};

export type deleteOrganizationResponse403 = {
    data: ForbiddenResponse;
    status: 403;
};

export type deleteOrganizationResponse404 = {
    data: NotFoundResponse;
    status: 404;
};

export type deleteOrganizationResponseSuccess = deleteOrganizationResponse204 & {
    headers: Headers;
};
export type deleteOrganizationResponseError = (deleteOrganizationResponse401 | deleteOrganizationResponse403 | deleteOrganizationResponse404) & {
    headers: Headers;
};

export type deleteOrganizationResponse = deleteOrganizationResponseSuccess | deleteOrganizationResponseError;

export const getDeleteOrganizationUrl = (id: number | string) => {
    return `${apiURL}/api/organizations/${id}`;
};

/**
 * Supprime l'organisation d'identifiant id
 */
export const deleteOrganization = async (id: number | string, options?: Parameters<typeof fetchWithAuth>[1]): Promise<deleteOrganizationResponse> => {
    return fetchWithAuth<deleteOrganizationResponse>(getDeleteOrganizationUrl(id), {
        ...options,
        method: "DELETE",
    });
};

export const getDeleteOrganizationMutationKey = () => ["deleteOrganization"] as const;

export const getDeleteOrganizationMutationOptions = <TError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteOrganization>>, TError, DeleteOrganizationMutationVariables, TContext>;
    request?: SecondParameter<typeof fetchWithAuth>;
}): UseMutationOptions<Awaited<ReturnType<typeof deleteOrganization>>, TError, DeleteOrganizationMutationVariables, TContext> => {
    const mutationKey = getDeleteOrganizationMutationKey();
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteOrganization>>, DeleteOrganizationMutationVariables> = (props) => {
        const { id } = props ?? {};

        return deleteOrganization(id, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type DeleteOrganizationMutationResult = NonNullable<Awaited<ReturnType<typeof deleteOrganization>>>;

export type DeleteOrganizationMutationError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse;
export type DeleteOrganizationMutationVariables = { id: number | string };

export const useDeleteOrganization = <TError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteOrganization>>, TError, DeleteOrganizationMutationVariables, TContext>;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof deleteOrganization>>, TError, DeleteOrganizationMutationVariables, TContext> => {
    return useMutation(getDeleteOrganizationMutationOptions(options), queryClient);
};
export type postOrganizationResponse201 = {
    data: Organization;
    status: 201;
};

export type postOrganizationResponse400 = {
    data: BadRequestResponse;
    status: 400;
};

export type postOrganizationResponse401 = {
    data: NotConnectedResponse;
    status: 401;
};

export type postOrganizationResponse403 = {
    data: ForbiddenResponse;
    status: 403;
};

export type postOrganizationResponseSuccess = postOrganizationResponse201 & {
    headers: Headers;
};
export type postOrganizationResponseError = (postOrganizationResponse400 | postOrganizationResponse401 | postOrganizationResponse403) & {
    headers: Headers;
};

export type postOrganizationResponse = postOrganizationResponseSuccess | postOrganizationResponseError;

export const getPostOrganizationUrl = () => {
    return `${apiURL}/api/organizations`;
};

/**
 * Créer une organisation - L'utilisateur connecté devient un propriétaire
 */
export const postOrganization = async (
    postOrganizationBody: PostOrganizationBody,
    options?: Parameters<typeof fetchWithAuth>[1]
): Promise<postOrganizationResponse> => {
    const getHeaders = (h?: NonNullable<RequestInit["headers"]>): Record<string, string | readonly string[]> => {
        if (!h) return {};
        if (h instanceof Headers) return Object.fromEntries(h.entries());
        if (Symbol.iterator in h) {
            return Object.fromEntries(Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]));
        }
        const headers: Record<string, string | readonly string[]> = {};
        for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
            if (value !== undefined) headers[name] = value;
        }
        return headers;
    };
    return fetchWithAuth<postOrganizationResponse>(getPostOrganizationUrl(), {
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...getHeaders(options?.headers) },
        body: JSON.stringify(postOrganizationBody),
    });
};

export const getPostOrganizationMutationKey = () => ["postOrganization"] as const;

export const getPostOrganizationMutationOptions = <TError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof postOrganization>>, TError, PostOrganizationMutationVariables, TContext>;
    request?: SecondParameter<typeof fetchWithAuth>;
}): UseMutationOptions<Awaited<ReturnType<typeof postOrganization>>, TError, PostOrganizationMutationVariables, TContext> => {
    const mutationKey = getPostOrganizationMutationKey();
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<Awaited<ReturnType<typeof postOrganization>>, PostOrganizationMutationVariables> = (props) => {
        const { data } = props ?? {};

        return postOrganization(data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type PostOrganizationMutationResult = NonNullable<Awaited<ReturnType<typeof postOrganization>>>;
export type PostOrganizationMutationBody = PostOrganizationBody;
export type PostOrganizationMutationError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse;
export type PostOrganizationMutationVariables = { data: PostOrganizationBody };

export const usePostOrganization = <TError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<Awaited<ReturnType<typeof postOrganization>>, TError, PostOrganizationMutationVariables, TContext>;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof postOrganization>>, TError, PostOrganizationMutationVariables, TContext> => {
    return useMutation(getPostOrganizationMutationOptions(options), queryClient);
};
export type putOrganizationAttributeResponse200 = {
    data: PutOrganizationAttribute200;
    status: 200;
};

export type putOrganizationAttributeResponse400 = {
    data: BadRequestResponse;
    status: 400;
};

export type putOrganizationAttributeResponse401 = {
    data: NotConnectedResponse;
    status: 401;
};

export type putOrganizationAttributeResponse403 = {
    data: ForbiddenResponse;
    status: 403;
};

export type putOrganizationAttributeResponse404 = {
    data: NotFoundResponse;
    status: 404;
};

export type putOrganizationAttributeResponseSuccess = putOrganizationAttributeResponse200 & {
    headers: Headers;
};
export type putOrganizationAttributeResponseError = (
    putOrganizationAttributeResponse400 | putOrganizationAttributeResponse401 | putOrganizationAttributeResponse403 | putOrganizationAttributeResponse404
) & {
    headers: Headers;
};

export type putOrganizationAttributeResponse = putOrganizationAttributeResponseSuccess | putOrganizationAttributeResponseError;

export const getPutOrganizationAttributeUrl = (id: number | string, attribute: string) => {
    return `${apiURL}/api/organizations/${id}/${attribute}`;
};

/**
 * Affecte value à l'attribut de l'organisation d'identifiant public_id
 */
export const putOrganizationAttribute = async (
    id: number | string,
    attribute: string,
    putOrganizationAttributeBody: PutOrganizationAttributeBody,
    options?: Parameters<typeof fetchWithAuth>[1]
): Promise<putOrganizationAttributeResponse> => {
    const getHeaders = (h?: NonNullable<RequestInit["headers"]>): Record<string, string | readonly string[]> => {
        if (!h) return {};
        if (h instanceof Headers) return Object.fromEntries(h.entries());
        if (Symbol.iterator in h) {
            return Object.fromEntries(Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]));
        }
        const headers: Record<string, string | readonly string[]> = {};
        for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
            if (value !== undefined) headers[name] = value;
        }
        return headers;
    };
    return fetchWithAuth<putOrganizationAttributeResponse>(getPutOrganizationAttributeUrl(id, attribute), {
        ...options,
        method: "PUT",
        headers: { "Content-Type": "application/json", ...getHeaders(options?.headers) },
        body: JSON.stringify(putOrganizationAttributeBody),
    });
};

export const getPutOrganizationAttributeMutationKey = () => ["putOrganizationAttribute"] as const;

export const getPutOrganizationAttributeMutationOptions = <
    TError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse | NotFoundResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof putOrganizationAttribute>>, TError, PutOrganizationAttributeMutationVariables, TContext>;
    request?: SecondParameter<typeof fetchWithAuth>;
}): UseMutationOptions<Awaited<ReturnType<typeof putOrganizationAttribute>>, TError, PutOrganizationAttributeMutationVariables, TContext> => {
    const mutationKey = getPutOrganizationAttributeMutationKey();
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<Awaited<ReturnType<typeof putOrganizationAttribute>>, PutOrganizationAttributeMutationVariables> = (props) => {
        const { id, attribute, data } = props ?? {};

        return putOrganizationAttribute(id, attribute, data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type PutOrganizationAttributeMutationResult = NonNullable<Awaited<ReturnType<typeof putOrganizationAttribute>>>;
export type PutOrganizationAttributeMutationBody = PutOrganizationAttributeBody;
export type PutOrganizationAttributeMutationError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse | NotFoundResponse;
export type PutOrganizationAttributeMutationVariables = { id: number | string; attribute: string; data: PutOrganizationAttributeBody };

export const usePutOrganizationAttribute = <TError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse | NotFoundResponse, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<Awaited<ReturnType<typeof putOrganizationAttribute>>, TError, PutOrganizationAttributeMutationVariables, TContext>;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof putOrganizationAttribute>>, TError, PutOrganizationAttributeMutationVariables, TContext> => {
    return useMutation(getPutOrganizationAttributeMutationOptions(options), queryClient);
};
export type putOrganizationJoinLinkRoleResponse200 = {
    data: PutOrganizationJoinLinkRole200;
    status: 200;
};

export type putOrganizationJoinLinkRoleResponse401 = {
    data: NotConnectedResponse;
    status: 401;
};

export type putOrganizationJoinLinkRoleResponse403 = {
    data: ForbiddenResponse;
    status: 403;
};

export type putOrganizationJoinLinkRoleResponse404 = {
    data: NotFoundResponse;
    status: 404;
};

export type putOrganizationJoinLinkRoleResponseSuccess = putOrganizationJoinLinkRoleResponse200 & {
    headers: Headers;
};
export type putOrganizationJoinLinkRoleResponseError = (
    putOrganizationJoinLinkRoleResponse401 | putOrganizationJoinLinkRoleResponse403 | putOrganizationJoinLinkRoleResponse404
) & {
    headers: Headers;
};

export type putOrganizationJoinLinkRoleResponse = putOrganizationJoinLinkRoleResponseSuccess | putOrganizationJoinLinkRoleResponseError;

export const getPutOrganizationJoinLinkRoleUrl = (id: number | string, role: string) => {
    return `${apiURL}/api/organizations/${id}/join-link/${role}`;
};

/**
 * Modifie le lien d'accès à l'organisation
 */
export const putOrganizationJoinLinkRole = async (
    id: number | string,
    role: string,
    putOrganizationJoinLinkRoleBody: PutOrganizationJoinLinkRoleBody,
    options?: Parameters<typeof fetchWithAuth>[1]
): Promise<putOrganizationJoinLinkRoleResponse> => {
    const getHeaders = (h?: NonNullable<RequestInit["headers"]>): Record<string, string | readonly string[]> => {
        if (!h) return {};
        if (h instanceof Headers) return Object.fromEntries(h.entries());
        if (Symbol.iterator in h) {
            return Object.fromEntries(Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]));
        }
        const headers: Record<string, string | readonly string[]> = {};
        for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
            if (value !== undefined) headers[name] = value;
        }
        return headers;
    };
    return fetchWithAuth<putOrganizationJoinLinkRoleResponse>(getPutOrganizationJoinLinkRoleUrl(id, role), {
        ...options,
        method: "PUT",
        headers: { "Content-Type": "application/json", ...getHeaders(options?.headers) },
        body: JSON.stringify(putOrganizationJoinLinkRoleBody),
    });
};

export const getPutOrganizationJoinLinkRoleMutationKey = () => ["putOrganizationJoinLinkRole"] as const;

export const getPutOrganizationJoinLinkRoleMutationOptions = <
    TError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof putOrganizationJoinLinkRole>>, TError, PutOrganizationJoinLinkRoleMutationVariables, TContext>;
    request?: SecondParameter<typeof fetchWithAuth>;
}): UseMutationOptions<Awaited<ReturnType<typeof putOrganizationJoinLinkRole>>, TError, PutOrganizationJoinLinkRoleMutationVariables, TContext> => {
    const mutationKey = getPutOrganizationJoinLinkRoleMutationKey();
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<Awaited<ReturnType<typeof putOrganizationJoinLinkRole>>, PutOrganizationJoinLinkRoleMutationVariables> = (props) => {
        const { id, role, data } = props ?? {};

        return putOrganizationJoinLinkRole(id, role, data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type PutOrganizationJoinLinkRoleMutationResult = NonNullable<Awaited<ReturnType<typeof putOrganizationJoinLinkRole>>>;
export type PutOrganizationJoinLinkRoleMutationBody = PutOrganizationJoinLinkRoleBody;
export type PutOrganizationJoinLinkRoleMutationError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse;
export type PutOrganizationJoinLinkRoleMutationVariables = { id: number | string; role: string; data: PutOrganizationJoinLinkRoleBody };

export const usePutOrganizationJoinLinkRole = <TError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<Awaited<ReturnType<typeof putOrganizationJoinLinkRole>>, TError, PutOrganizationJoinLinkRoleMutationVariables, TContext>;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof putOrganizationJoinLinkRole>>, TError, PutOrganizationJoinLinkRoleMutationVariables, TContext> => {
    return useMutation(getPutOrganizationJoinLinkRoleMutationOptions(options), queryClient);
};
export type joinOrganizationByIdResponse200 = {
    data: Organization;
    status: 200;
};

export type joinOrganizationByIdResponse400 = {
    data: BadRequestResponse;
    status: 400;
};

export type joinOrganizationByIdResponse401 = {
    data: NotConnectedResponse;
    status: 401;
};

export type joinOrganizationByIdResponse403 = {
    data: ForbiddenResponse;
    status: 403;
};

export type joinOrganizationByIdResponse404 = {
    data: NotFoundResponse;
    status: 404;
};

export type joinOrganizationByIdResponseSuccess = joinOrganizationByIdResponse200 & {
    headers: Headers;
};
export type joinOrganizationByIdResponseError = (
    joinOrganizationByIdResponse400 | joinOrganizationByIdResponse401 | joinOrganizationByIdResponse403 | joinOrganizationByIdResponse404
) & {
    headers: Headers;
};

export type joinOrganizationByIdResponse = joinOrganizationByIdResponseSuccess | joinOrganizationByIdResponseError;

export const getJoinOrganizationByIdUrl = (id: number | string) => {
    return `${apiURL}/api/organizations/join/${id}`;
};

/**
 * L'utilisateur s'ajoute à l'organisation via le jeton id
 */
export const joinOrganizationById = async (id: number | string, options?: Parameters<typeof fetchWithAuth>[1]): Promise<joinOrganizationByIdResponse> => {
    return fetchWithAuth<joinOrganizationByIdResponse>(getJoinOrganizationByIdUrl(id), {
        ...options,
        method: "GET",
    });
};

export const getJoinOrganizationByIdQueryKey = (id: number | string) => {
    return [`${apiURL}/api/organizations/join/${id}`] as const;
};

export const getJoinOrganizationByIdQueryOptions = <
    TData = Awaited<ReturnType<typeof joinOrganizationById>>,
    TError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse | NotFoundResponse,
>(
    id: number | string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof joinOrganizationById>>, TError, TData>>;
        request?: SecondParameter<typeof fetchWithAuth>;
    }
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getJoinOrganizationByIdQueryKey(id);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof joinOrganizationById>>> = ({ signal }) => joinOrganizationById(id, { signal, ...requestOptions });

    return { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof joinOrganizationById>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type JoinOrganizationByIdQueryResult = NonNullable<Awaited<ReturnType<typeof joinOrganizationById>>>;
export type JoinOrganizationByIdQueryError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse | NotFoundResponse;

export function useJoinOrganizationById<
    TData = Awaited<ReturnType<typeof joinOrganizationById>>,
    TError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse | NotFoundResponse,
>(
    id: number | string,
    options: {
        query: Partial<UseQueryOptions<Awaited<ReturnType<typeof joinOrganizationById>>, TError, TData>> &
            Pick<
                DefinedInitialDataOptions<Awaited<ReturnType<typeof joinOrganizationById>>, TError, Awaited<ReturnType<typeof joinOrganizationById>>>,
                "initialData"
            >;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useJoinOrganizationById<
    TData = Awaited<ReturnType<typeof joinOrganizationById>>,
    TError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse | NotFoundResponse,
>(
    id: number | string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof joinOrganizationById>>, TError, TData>> &
            Pick<
                UndefinedInitialDataOptions<Awaited<ReturnType<typeof joinOrganizationById>>, TError, Awaited<ReturnType<typeof joinOrganizationById>>>,
                "initialData"
            >;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useJoinOrganizationById<
    TData = Awaited<ReturnType<typeof joinOrganizationById>>,
    TError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse | NotFoundResponse,
>(
    id: number | string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof joinOrganizationById>>, TError, TData>>;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useJoinOrganizationById<
    TData = Awaited<ReturnType<typeof joinOrganizationById>>,
    TError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse | NotFoundResponse,
>(
    id: number | string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof joinOrganizationById>>, TError, TData>>;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const queryOptions = getJoinOrganizationByIdQueryOptions(id, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

    return withQueryKey(query, queryOptions.queryKey);
}

export const prefetchJoinOrganizationByIdQuery = async <
    TData = Awaited<ReturnType<typeof joinOrganizationById>>,
    TError = BadRequestResponse | NotConnectedResponse | ForbiddenResponse | NotFoundResponse,
>(
    queryClient: QueryClient,
    id: number | string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof joinOrganizationById>>, TError, TData>>;
        request?: SecondParameter<typeof fetchWithAuth>;
    }
): Promise<QueryClient> => {
    const queryOptions = getJoinOrganizationByIdQueryOptions(id, options);

    await queryClient.prefetchQuery(queryOptions);

    return queryClient;
};

export type getOrganizationLinksByIdResponse200 = {
    data: GetOrganizationLinksById200;
    status: 200;
};

export type getOrganizationLinksByIdResponse401 = {
    data: NotConnectedResponse;
    status: 401;
};

export type getOrganizationLinksByIdResponse403 = {
    data: ForbiddenResponse;
    status: 403;
};

export type getOrganizationLinksByIdResponse404 = {
    data: NotFoundResponse;
    status: 404;
};

export type getOrganizationLinksByIdResponseSuccess = getOrganizationLinksByIdResponse200 & {
    headers: Headers;
};
export type getOrganizationLinksByIdResponseError = (
    getOrganizationLinksByIdResponse401 | getOrganizationLinksByIdResponse403 | getOrganizationLinksByIdResponse404
) & {
    headers: Headers;
};

export type getOrganizationLinksByIdResponse = getOrganizationLinksByIdResponseSuccess | getOrganizationLinksByIdResponseError;

export const getGetOrganizationLinksByIdUrl = (id: number | string) => {
    return `${apiURL}/api/organizations/links/${id}`;
};

/**
 * Récupère les liens d'invitation de l'organisation. Seuls les propriétaires peuvent accéder à cette ressource.
 */
export const getOrganizationLinksById = async (
    id: number | string,
    options?: Parameters<typeof fetchWithAuth>[1]
): Promise<getOrganizationLinksByIdResponse> => {
    return fetchWithAuth<getOrganizationLinksByIdResponse>(getGetOrganizationLinksByIdUrl(id), {
        ...options,
        method: "GET",
    });
};

export const getGetOrganizationLinksByIdQueryKey = (id: number | string) => {
    return [`${apiURL}/api/organizations/links/${id}`] as const;
};

export const getGetOrganizationLinksByIdQueryOptions = <
    TData = Awaited<ReturnType<typeof getOrganizationLinksById>>,
    TError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse,
>(
    id: number | string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationLinksById>>, TError, TData>>;
        request?: SecondParameter<typeof fetchWithAuth>;
    }
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetOrganizationLinksByIdQueryKey(id);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getOrganizationLinksById>>> = ({ signal }) =>
        getOrganizationLinksById(id, { signal, ...requestOptions });

    return { queryKey, queryFn, enabled: id !== null && id !== undefined, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getOrganizationLinksById>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetOrganizationLinksByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getOrganizationLinksById>>>;
export type GetOrganizationLinksByIdQueryError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse;

export function useGetOrganizationLinksById<
    TData = Awaited<ReturnType<typeof getOrganizationLinksById>>,
    TError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse,
>(
    id: number | string,
    options: {
        query: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationLinksById>>, TError, TData>> &
            Pick<
                DefinedInitialDataOptions<Awaited<ReturnType<typeof getOrganizationLinksById>>, TError, Awaited<ReturnType<typeof getOrganizationLinksById>>>,
                "initialData"
            >;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetOrganizationLinksById<
    TData = Awaited<ReturnType<typeof getOrganizationLinksById>>,
    TError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse,
>(
    id: number | string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationLinksById>>, TError, TData>> &
            Pick<
                UndefinedInitialDataOptions<Awaited<ReturnType<typeof getOrganizationLinksById>>, TError, Awaited<ReturnType<typeof getOrganizationLinksById>>>,
                "initialData"
            >;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useGetOrganizationLinksById<
    TData = Awaited<ReturnType<typeof getOrganizationLinksById>>,
    TError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse,
>(
    id: number | string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationLinksById>>, TError, TData>>;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useGetOrganizationLinksById<
    TData = Awaited<ReturnType<typeof getOrganizationLinksById>>,
    TError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse,
>(
    id: number | string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationLinksById>>, TError, TData>>;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
    const queryOptions = getGetOrganizationLinksByIdQueryOptions(id, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

    return withQueryKey(query, queryOptions.queryKey);
}

export const prefetchGetOrganizationLinksByIdQuery = async <
    TData = Awaited<ReturnType<typeof getOrganizationLinksById>>,
    TError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse,
>(
    queryClient: QueryClient,
    id: number | string,
    options?: {
        query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getOrganizationLinksById>>, TError, TData>>;
        request?: SecondParameter<typeof fetchWithAuth>;
    }
): Promise<QueryClient> => {
    const queryOptions = getGetOrganizationLinksByIdQueryOptions(id, options);

    await queryClient.prefetchQuery(queryOptions);

    return queryClient;
};

export type addMemberToOrganizationResponse200 = {
    data: AddMemberToOrganization200;
    status: 200;
};

export type addMemberToOrganizationResponse401 = {
    data: NotConnectedResponse;
    status: 401;
};

export type addMemberToOrganizationResponse403 = {
    data: ForbiddenResponse;
    status: 403;
};

export type addMemberToOrganizationResponse404 = {
    data: NotFoundResponse;
    status: 404;
};

export type addMemberToOrganizationResponseSuccess = addMemberToOrganizationResponse200 & {
    headers: Headers;
};
export type addMemberToOrganizationResponseError = (
    addMemberToOrganizationResponse401 | addMemberToOrganizationResponse403 | addMemberToOrganizationResponse404
) & {
    headers: Headers;
};

export type addMemberToOrganizationResponse = addMemberToOrganizationResponseSuccess | addMemberToOrganizationResponseError;

export const getAddMemberToOrganizationUrl = (id: number | string, userId: string) => {
    return `${apiURL}/api/organizations/${id}/members/${userId}`;
};

/**
 * Ajoute un membre à l'organisation
 */
export const addMemberToOrganization = async (
    id: number | string,
    userId: string,
    addMemberToOrganizationBody: AddMemberToOrganizationBody,
    options?: Parameters<typeof fetchWithAuth>[1]
): Promise<addMemberToOrganizationResponse> => {
    const getHeaders = (h?: NonNullable<RequestInit["headers"]>): Record<string, string | readonly string[]> => {
        if (!h) return {};
        if (h instanceof Headers) return Object.fromEntries(h.entries());
        if (Symbol.iterator in h) {
            return Object.fromEntries(Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]));
        }
        const headers: Record<string, string | readonly string[]> = {};
        for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
            if (value !== undefined) headers[name] = value;
        }
        return headers;
    };
    return fetchWithAuth<addMemberToOrganizationResponse>(getAddMemberToOrganizationUrl(id, userId), {
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...getHeaders(options?.headers) },
        body: JSON.stringify(addMemberToOrganizationBody),
    });
};

export const getAddMemberToOrganizationMutationKey = () => ["addMemberToOrganization"] as const;

export const getAddMemberToOrganizationMutationOptions = <TError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof addMemberToOrganization>>, TError, AddMemberToOrganizationMutationVariables, TContext>;
    request?: SecondParameter<typeof fetchWithAuth>;
}): UseMutationOptions<Awaited<ReturnType<typeof addMemberToOrganization>>, TError, AddMemberToOrganizationMutationVariables, TContext> => {
    const mutationKey = getAddMemberToOrganizationMutationKey();
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<Awaited<ReturnType<typeof addMemberToOrganization>>, AddMemberToOrganizationMutationVariables> = (props) => {
        const { id, userId, data } = props ?? {};

        return addMemberToOrganization(id, userId, data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type AddMemberToOrganizationMutationResult = NonNullable<Awaited<ReturnType<typeof addMemberToOrganization>>>;
export type AddMemberToOrganizationMutationBody = AddMemberToOrganizationBody;
export type AddMemberToOrganizationMutationError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse;
export type AddMemberToOrganizationMutationVariables = { id: number | string; userId: string; data: AddMemberToOrganizationBody };

export const useAddMemberToOrganization = <TError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<Awaited<ReturnType<typeof addMemberToOrganization>>, TError, AddMemberToOrganizationMutationVariables, TContext>;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof addMemberToOrganization>>, TError, AddMemberToOrganizationMutationVariables, TContext> => {
    return useMutation(getAddMemberToOrganizationMutationOptions(options), queryClient);
};
export type deleteOrganizationMemberResponse204 = {
    data: DeletedResponse;
    status: 204;
};

export type deleteOrganizationMemberResponse401 = {
    data: NotConnectedResponse;
    status: 401;
};

export type deleteOrganizationMemberResponse403 = {
    data: ForbiddenResponse;
    status: 403;
};

export type deleteOrganizationMemberResponse404 = {
    data: NotFoundResponse;
    status: 404;
};

export type deleteOrganizationMemberResponseSuccess = deleteOrganizationMemberResponse204 & {
    headers: Headers;
};
export type deleteOrganizationMemberResponseError = (
    deleteOrganizationMemberResponse401 | deleteOrganizationMemberResponse403 | deleteOrganizationMemberResponse404
) & {
    headers: Headers;
};

export type deleteOrganizationMemberResponse = deleteOrganizationMemberResponseSuccess | deleteOrganizationMemberResponseError;

export const getDeleteOrganizationMemberUrl = (id: number | string, userId: string) => {
    return `${apiURL}/api/organizations/${id}/members/${userId}`;
};

/**
 * Enlève un membre de l'organisation. Un utilisateur peut se retirer lui-même, sinon un owner doit effectuer cette action.
 */
export const deleteOrganizationMember = async (
    id: number | string,
    userId: string,
    options?: Parameters<typeof fetchWithAuth>[1]
): Promise<deleteOrganizationMemberResponse> => {
    return fetchWithAuth<deleteOrganizationMemberResponse>(getDeleteOrganizationMemberUrl(id, userId), {
        ...options,
        method: "DELETE",
    });
};

export const getDeleteOrganizationMemberMutationKey = () => ["deleteOrganizationMember"] as const;

export const getDeleteOrganizationMemberMutationOptions = <TError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteOrganizationMember>>, TError, DeleteOrganizationMemberMutationVariables, TContext>;
    request?: SecondParameter<typeof fetchWithAuth>;
}): UseMutationOptions<Awaited<ReturnType<typeof deleteOrganizationMember>>, TError, DeleteOrganizationMemberMutationVariables, TContext> => {
    const mutationKey = getDeleteOrganizationMemberMutationKey();
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteOrganizationMember>>, DeleteOrganizationMemberMutationVariables> = (props) => {
        const { id, userId } = props ?? {};

        return deleteOrganizationMember(id, userId, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type DeleteOrganizationMemberMutationResult = NonNullable<Awaited<ReturnType<typeof deleteOrganizationMember>>>;

export type DeleteOrganizationMemberMutationError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse;
export type DeleteOrganizationMemberMutationVariables = { id: number | string; userId: string };

export const useDeleteOrganizationMember = <TError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<Awaited<ReturnType<typeof deleteOrganizationMember>>, TError, DeleteOrganizationMemberMutationVariables, TContext>;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof deleteOrganizationMember>>, TError, DeleteOrganizationMemberMutationVariables, TContext> => {
    return useMutation(getDeleteOrganizationMemberMutationOptions(options), queryClient);
};
export type putOrganizationMemberRoleResponse200 = {
    data: PutOrganizationMemberRole200;
    status: 200;
};

export type putOrganizationMemberRoleResponse401 = {
    data: NotConnectedResponse;
    status: 401;
};

export type putOrganizationMemberRoleResponse403 = {
    data: ForbiddenResponse;
    status: 403;
};

export type putOrganizationMemberRoleResponse404 = {
    data: NotFoundResponse;
    status: 404;
};

export type putOrganizationMemberRoleResponseSuccess = putOrganizationMemberRoleResponse200 & {
    headers: Headers;
};
export type putOrganizationMemberRoleResponseError = (
    putOrganizationMemberRoleResponse401 | putOrganizationMemberRoleResponse403 | putOrganizationMemberRoleResponse404
) & {
    headers: Headers;
};

export type putOrganizationMemberRoleResponse = putOrganizationMemberRoleResponseSuccess | putOrganizationMemberRoleResponseError;

export const getPutOrganizationMemberRoleUrl = (id: number | string, userId: string) => {
    return `${apiURL}/api/organizations/${id}/members/${userId}/role`;
};

/**
 * Modifie le rôle d'un membre dans l'organisation
 */
export const putOrganizationMemberRole = async (
    id: number | string,
    userId: string,
    putOrganizationMemberRoleBody: PutOrganizationMemberRoleBody,
    options?: Parameters<typeof fetchWithAuth>[1]
): Promise<putOrganizationMemberRoleResponse> => {
    const getHeaders = (h?: NonNullable<RequestInit["headers"]>): Record<string, string | readonly string[]> => {
        if (!h) return {};
        if (h instanceof Headers) return Object.fromEntries(h.entries());
        if (Symbol.iterator in h) {
            return Object.fromEntries(Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]));
        }
        const headers: Record<string, string | readonly string[]> = {};
        for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
            if (value !== undefined) headers[name] = value;
        }
        return headers;
    };
    return fetchWithAuth<putOrganizationMemberRoleResponse>(getPutOrganizationMemberRoleUrl(id, userId), {
        ...options,
        method: "PUT",
        headers: { "Content-Type": "application/json", ...getHeaders(options?.headers) },
        body: JSON.stringify(putOrganizationMemberRoleBody),
    });
};

export const getPutOrganizationMemberRoleMutationKey = () => ["putOrganizationMemberRole"] as const;

export const getPutOrganizationMemberRoleMutationOptions = <
    TError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<Awaited<ReturnType<typeof putOrganizationMemberRole>>, TError, PutOrganizationMemberRoleMutationVariables, TContext>;
    request?: SecondParameter<typeof fetchWithAuth>;
}): UseMutationOptions<Awaited<ReturnType<typeof putOrganizationMemberRole>>, TError, PutOrganizationMemberRoleMutationVariables, TContext> => {
    const mutationKey = getPutOrganizationMemberRoleMutationKey();
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation && "mutationKey" in options.mutation && options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<Awaited<ReturnType<typeof putOrganizationMemberRole>>, PutOrganizationMemberRoleMutationVariables> = (props) => {
        const { id, userId, data } = props ?? {};

        return putOrganizationMemberRole(id, userId, data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type PutOrganizationMemberRoleMutationResult = NonNullable<Awaited<ReturnType<typeof putOrganizationMemberRole>>>;
export type PutOrganizationMemberRoleMutationBody = PutOrganizationMemberRoleBody;
export type PutOrganizationMemberRoleMutationError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse;
export type PutOrganizationMemberRoleMutationVariables = { id: number | string; userId: string; data: PutOrganizationMemberRoleBody };

export const usePutOrganizationMemberRole = <TError = NotConnectedResponse | ForbiddenResponse | NotFoundResponse, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<Awaited<ReturnType<typeof putOrganizationMemberRole>>, TError, PutOrganizationMemberRoleMutationVariables, TContext>;
        request?: SecondParameter<typeof fetchWithAuth>;
    },
    queryClient?: QueryClient
): UseMutationResult<Awaited<ReturnType<typeof putOrganizationMemberRole>>, TError, PutOrganizationMemberRoleMutationVariables, TContext> => {
    return useMutation(getPutOrganizationMemberRoleMutationOptions(options), queryClient);
};
